bind 127.0.0.1
protected-mode yes
port 26388
requirepass u8glX8sSBZ6LF7JcxG5vcuiklDRfIMDG_4BWxxGMpkg
maxmemory 64mb
maxmemory-policy allkeys-lru
save ""
appendonly no
hash-max-listpack-entries 1024
hz 1
activedefrag no
slowlog-log-slower-than -1