package catalog

import (
	"dfolan/internal/catalog/pvf"
	"encoding/json"
	"fmt"
	"os"
)

// TutorialFlow preserves the per-job source route. Event-only routes must
// never replace a normal job's route, and large current IDs remain uint32.
type TutorialFlow struct {
	Job         string `json:"job"`
	Advancement *byte  `json:"advancement,omitempty"`
	EventOnly   bool   `json:"event_only,omitempty"`
	Dungeon     uint32 `json:"dungeon"`
	Intro       string `json:"intro"`
	IntroAfter  bool   `json:"intro_after_tutorial"`
	Town, Area  uint32
	Position    [2]uint16 `json:"position"`
	FirstQuest  uint32    `json:"first_quest,omitempty"`
}

type TutorialCatalog struct {
	Source pvf.ArchiveSnapshot `json:"source"`
	Script ScriptRecord        `json:"script"`
	Flows  []TutorialFlow      `json:"flows"`
}

func ParseTutorialFlows(s ScriptRecord) ([]TutorialFlow, error) {
	var out []TutorialFlow
	for i := 0; i < len(s.Cells); i++ {
		if s.Cells[i].Type != 3 || s.Cells[i].Text != "[tutorial flow]" {
			continue
		}
		start := i + 1
		for i++; i < len(s.Cells) && !(s.Cells[i].Type == 3 && s.Cells[i].Text == "[/tutorial flow]"); i++ {
		}
		if i == len(s.Cells) {
			return nil, fmt.Errorf("unterminated tutorial flow")
		}
		cells := s.Cells[start:i]
		if len(cells) == 0 || cells[0].Type != 6 {
			return nil, fmt.Errorf("tutorial job missing")
		}
		f := TutorialFlow{Job: cells[0].Text}
		if len(cells) > 1 && cells[1].Type == 0 {
			if cells[1].Value < 0 || cells[1].Value > 255 {
				return nil, fmt.Errorf("invalid tutorial grow type")
			}
			v := byte(cells[1].Value)
			f.Advancement = &v
		}
		ints := func(tag string, n int, max int32) ([]uint32, error) {
			v := sectionCells(cells, tag)
			if len(v) != n {
				return nil, fmt.Errorf("tutorial %s needs %d values", tag, n)
			}
			out := make([]uint32, n)
			for j, t := range v {
				if t.Type != 0 || t.Value < 0 || t.Value > max {
					return nil, fmt.Errorf("invalid tutorial %s value", tag)
				}
				out[j] = uint32(t.Value)
			}
			return out, nil
		}
		d, e := ints("[dungeon index]", 1, 2147483647)
		if e != nil {
			return nil, e
		}
		f.Dungeon = d[0]
		t, e := ints("[town]", 2, 65535)
		if e != nil {
			return nil, e
		}
		f.Town, f.Area = t[0], t[1]
		pos, e := ints("[startPos]", 2, 65535)
		if e != nil {
			return nil, e
		}
		f.Position = [2]uint16{uint16(pos[0]), uint16(pos[1])}
		order, e := ints("[after tutorial]", 1, 1)
		if e != nil {
			return nil, e
		}
		f.IntroAfter = order[0] == 1
		intro := sectionCells(cells, "[intro path]")
		if len(intro) != 1 || intro[0].Type != 6 || intro[0].Text == "" || f.Dungeon == 0 {
			return nil, fmt.Errorf("invalid tutorial intro/dungeon")
		}
		f.Intro = intro[0].Text
		if len(sectionCells(cells, "[first quest]")) > 0 {
			q, e := ints("[first quest]", 1, 65535)
			if e != nil {
				return nil, e
			}
			f.FirstQuest = q[0]
		}
		for _, c := range cells {
			if c.Type == 3 && c.Text == "[only for evnet]" {
				f.EventOnly = true
			}
		}
		out = append(out, f)
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("source has no tutorial routes")
	}
	return out, nil
}

func (c TutorialCatalog) Normal(job string, adv byte) (TutorialFlow, error) {
	var found *TutorialFlow
	for _, f := range c.Flows {
		if f.Job != job || f.EventOnly || f.Advancement != nil && *f.Advancement != adv {
			continue
		}
		if found != nil {
			return TutorialFlow{}, fmt.Errorf("ambiguous tutorial for %s", job)
		}
		v := f
		found = &v
	}
	if found == nil {
		return TutorialFlow{}, fmt.Errorf("source tutorial unavailable for %s", job)
	}
	return *found, nil
}

func LoadTutorialRoutes(path, source string) (*TutorialCatalog, error) {
	b, e := os.ReadFile(path)
	if e != nil {
		return nil, e
	}
	var c TutorialCatalog
	if e = json.Unmarshal(b, &c); e != nil {
		return nil, e
	}
	if c.Source.Checksum != source || len(c.Flows) == 0 {
		return nil, fmt.Errorf("tutorial route source mismatch")
	}
	// Reproject from the retained source script so a catalog generated by an
	// older parser can never silently supply a stale route.
	c.Flows, e = ParseTutorialFlows(c.Script)
	if e != nil {
		return nil, e
	}
	return &c, nil
}

func ImportTutorials(a *pvf.Archive) (TutorialCatalog, error) {
	c := TutorialCatalog{Source: a.Snapshot()}
	var e error
	c.Script, e = ReadScript(a, "etc/tutorial/tutorialflow.etc")
	if e != nil {
		return c, e
	}
	c.Flows, e = ParseTutorialFlows(c.Script)
	return c, e
}
