/*
 * probe-hook-meta.h -- addresses and the exact byte image of the code cave.
 *
 * This file is checked by tools/cavegen.py, which assembles src/probe-hook.s
 * with ml64, disassembles the result, and refuses to update anything unless the
 * layout still matches the contract below (in particular the two fields the
 * plugin patches at install time must sit at PROBE_OFF_SITEJMP+1 and
 * PROBE_OFF_STUB+6).
 *
 * ASCII only (it is included by a /utf-8 TU but stays 7-bit).
 */
#ifndef PROBE_HOOK_META_H
#define PROBE_HOOK_META_H

#include <stddef.h>

/* ---- the patch site ------------------------------------------------------
 * The getter has TWO exits with the identical `pop rdi / pop rsi / pop rbx /
 * ret` epilogue:
 *
 *   0x147220FFF   followed by `F2 48 0F 2C C6` (real code!) -> NOT patchable
 *   0x147221011   followed by 0xCC inter-function filler    -> the patch site
 *
 * Only the second one has filler bytes to borrow, so that is the one this
 * probe uses.  Consequence, stated honestly: samples that leave the getter
 * through 0x147220FFF (the `+0x30` "damage applied" branch) are not recorded.
 * See README "覆盖范围" for the arguments about which callers that affects.
 */
#define PROBE_SITE_VA        0x147221011ULL
#define PROBE_SITE_RVA       0x7221011ULL
#define PROBE_SITE_FILE      0x7221011ULL
#define PROBE_SITE_PATCHLEN  5
#define PROBE_SITE_HEX       "0x147221011"
#define PROBE_SITE_RVA_HEX   "0x7221011"
#define PROBE_SITE_FILE_HEX  "0x7221011"
#define PROBE_SITE_HEX_LAST  "0x147221015"
#define PROBE_SITE_EXPECTED_HEX "C3 CC CC CC CC"
#define PROBE_SITE_EXPECTED_BYTES {0xC3, 0xCC, 0xCC, 0xCC, 0xCC}

/* the other exit, kept here only so the log can name the known gap */
#define PROBE_SITE2_VA        0x147220FFFULL
#define PROBE_SITE2_HEX       "0x147220FFF"

/* ---- code cave layout (fixed by the PROBE_* equates in src/probe-hook.s) --
 *    +0x00  5 bytes   E9 <disp32>              jmp: getter exit -> cave
 *    +0x08 14 bytes   FF 25 00000000 <imm64>   jmp: cave -> probe_hp_entry()
 *    +0x16 ...        the trampoline proper
 *    +0x86  8 bytes   pointer slot used by the `lea rax,slot; call rax` idiom
 *    +0xE0  8 bytes   pointer slot used by the final `lea rax,slot; jmp rax`
 * The two offsets that vary if the .s file changes are emitted by
 * tools/cavegen.py into probe-hook-image.h (PROBE_OFF_LOG_SLOT /
 * PROBE_OFF_TAIL_SLOT); the constants below are the ones the .s file itself
 * pins with `org` directives.
 */
#define PROBE_OFF_SITEJMP 0    /* patched field at +1 (disp32) */
#define PROBE_OFF_STUB    8    /* patched field at +14 (imm64) */
#define PROBE_TOTAL_SIZE  0x400

/* First bytes of the cave image, used as a runtime sanity check.  The plugin
 * refuses to install if the embedded image does not start with these. */
#define PROBE_CAVEHEAD_BYTES {0xE9, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
#define PROBE_CAVEHEAD_LEN 8

/* ---- the cave's machine code ------------------------------------------- */
/* Generated by tools/cavegen.py from src/probe-hook.s (ml64 -> obj -> .text). */
#include "probe-hook-image.h"

/* ---- known direct/tail call sites of the getter (offline evidence) ------ */
typedef struct {
    const char *rva_hex;
    const char *va_hex;
    int flag;
    const char *note;
} probe_known_t;

#define PROBE_KNOWN_COUNT 25
static const probe_known_t PROBE_KNOWN[PROBE_KNOWN_COUNT] = {
    {"0x5B40B0",  "0x1405B40B0",  0, "XOR EDX,EDX"},
    {"0x26D1003", "0x1426D1003",  0, "XOR EDX,EDX"},
    {"0x26E8FCC", "0x1426E8FCC",  0, "XOR EDX,EDX"},
    {"0x30EC2FD", "0x1430EC2FD",  0, "XOR EDX,EDX"},
    {"0x30EC30A", "0x1430EC30A",  0, "XOR EDX,EDX"},
    {"0x4A678CF", "0x144A678CF",  0, "XOR EDX,EDX"},
    {"0x4F80AAD", "0x144F80AAD",  0, "XOR EDX,EDX"},
    {"0x5A06EB6", "0x145A06EB6",  1, "MOV DL,1 (in 0x145A06DB0) -- the x10 patch site"},
    {"0x5A06F56", "0x145A06F56",  1, "MOV DL,1 (in 0x145A06DB0) -- the x10 patch site"},
    {"0x5C199DB", "0x145C199DB",  0, "tail JMP from the vtable[0x12C8] thunk"},
    {"0x5C1D89E", "0x145C1D89E",  0, "tail JMP from a dispatcher"},
    {"0x5C334C8", "0x145C334C8",  0, "XOR EDX,EDX"},
    {"0x5C42457", "0x145C42457",  0, "XOR EDX,EDX"},
    {"0x5C4247E", "0x145C4247E",  0, "XOR EDX,EDX"},
    {"0x5C4252C", "0x145C4252C",  0, "XOR EDX,EDX"},
    {"0x5C7B636", "0x145C7B636",  0, "XOR EDX,EDX"},
    {"0x5D4EB76", "0x145D4EB76",  0, "XOR EDX,EDX"},
    {"0x5DB269E", "0x145DB269E",  0, "XOR EDX,EDX"},
    {"0x5E28EBA", "0x145E28EBA",  0, "XOR EDX,EDX"},
    {"0x65B1BB8", "0x1465B1BB8",  0, "XOR EDX,EDX"},
    {"0x6731D19", "0x146731D19",  0, "XOR EDX,EDX"},
    {"0x6731D28", "0x146731D28",  0, "XOR EDX,EDX"},
    {"0x7222838", "0x147222838",  0, "XOR EDX,EDX (hp-bar ratio family)"},
    {"0x72228E8", "0x1472228E8",  0, "XOR EDX,EDX (hp-bar ratio family)"},
    {"0x7800A38", "0x147800A38",  0, "XOR EDX,EDX"},
};

#endif /* PROBE_HOOK_META_H */
