// Code generated by modkit. DO NOT EDIT.
//
// 这个文件把**所有已安装的服务端 mod** import 进来，并暴露 RegisterMods()；
// 让服务端在启动时调用它们的 Register()（编译期注册）。
// 增删 mod 由 `modkit install/uninstall` 重写本文件——手工改它会被覆盖。
package mods

import (
	modpkg0 "dfolan/mods/odyssey.hardcore" // odyssey.hardcore
)

// RegisterMods 按稳定顺序调用每个 mod 的注册入口。
// 服务端在完成配置与存储初始化之后、开始监听之前调用它。
func RegisterMods() {
	modpkg0.Register()
}
