// Code generated by modkit. DO NOT EDIT.
//
// 这个文件把**所有已安装的服务端 mod** import 进来，并暴露 RegisterMods()；
// 由服务端主程序（cmd/wireprobe）import 调用，从而在各 mod 的 Register() 里
// 完成编译期钩子注册。增删 mod 由 `modkit install/uninstall` 重写本文件。
//
// 本文件与各 mod 的源码同处一个目录（服务端模块根的 mods/），
// 所以"服务端 mod 的一切"都在这一处可见。
package mods

import (
	"dfolan/mods/giveaway.random-equipment"
)

// RegisterMods 按稳定顺序调用每个 mod 的注册入口。
// 服务端在完成配置与存储初始化之后、开始监听之前调用它。
func RegisterMods() {
	modpkg.Register()
}
