// Code generated by modkit. DO NOT EDIT.
//
// 服务端侧的 mod 加载器：把各**已安装**的 mod 包 import 进来，并暴露 RegisterMods()，
// 让服务端在启动时调用它们的 Register()（编译期注册）—— 也就是说，
// 「哪些 mod 被编进这份程序」由这个文件决定。
// 增删 mod 由 `modkit install/uninstall` 重写本文件——手工改它会被覆盖。
//
// 仓库里提交的**必须是干净形态**（下面不 import 任何 mod 的合法加载器）：这份文件同时进
// 版本库，只有干净形态才保证「谁 clone 下来都编得过」。本机装了哪些 mod 由引擎写进本机这份：
// 装卸会写，启动器编译前还会按 mods/ 目录现状再重算一次（internal/serverbuild 的
// syncServerModsGen）。所以本机这份被谁推上去、或被本机改乱，都不影响**启动器**的构建；
// 但直接 `go build ./...`（CI、server/Build-Server.ps1）没有这层重算 —— 一份带着
// "只在本机存在的 mod" 的加载器被推上去，别人全新 clone 立刻编不过：
//
//	mods\zz_mods_gen.go:9:2: package dfolan/mods/<mod-id> is not in std
//
// （模块里找不到该导入路径时，Go 会把它当标准库候选去 GOROOT 找，报错因此长得不像"缺文件"。）
// 所以：**别把本机那份（它写着你这台机器装了哪些 mod）提交/推上去**。真要提交某个 mod，就把
// 它的源码一起入库（`git ls-files server/work/dfo-lan/mods/<mod-id>` 要有结果）；否则先在
// 启动器里卸载该 mod / 清空本加载器，再提交干净形态。server/Build-Server.ps1 编译前会机械
// 拦这一条（有 git 时中止并报错，没有 git 的解包目录只告警）。
package mods

// 当前没有已安装的服务端 mod：干净形态，RegisterMods() 什么都不注册。
func RegisterMods() {}
