package wire

import (
	"encoding/binary"
	"fmt"
)

// areaCipher implements the supplied build's slot 9 (16-byte key, 12 rounds).
// Key schedule: 146d90330; common block transform: 146d909f0. Constants and
// independent native fixtures are generated by area_cipher_oracle.py.
type areaCipher struct {
	encryptKeys [13][4]uint32
	decryptKeys [13][4]uint32
}

func newAreaCipher(key []byte) (*areaCipher, error) {
	if len(key) != 16 {
		return nil, fmt.Errorf("area cipher key length %d, expected 16", len(key))
	}
	c := new(areaCipher)
	var k [4]uint32
	for i := range k {
		k[i] = binary.BigEndian.Uint32(key[i*4:])
	}
	for round := 0; round <= 12; round++ {
		for j := 0; j < 4; j++ {
			shift := uint(24 - j*8)
			v := areaCipherT4[byte(k[3]>>shift)]
			for i := 2; i >= 0; i-- {
				v = areaCipherT4[byte(k[i]>>shift)] ^
					(areaCipherT5[byte(v>>24)] & 0xff000000) ^
					(areaCipherT5[byte(v>>16)] & 0x00ff0000) ^
					(areaCipherT5[byte(v>>8)] & 0x0000ff00) ^
					(areaCipherT5[byte(v)] & 0x000000ff)
			}
			c.encryptKeys[round][j] = v
		}
		if round == 12 {
			break
		}
		var next [4]uint32
		for i := range next {
			next[i] = areaCipherT0[byte(k[i]>>24)] ^
				areaCipherT1[byte(k[(i+3)%4]>>16)] ^
				areaCipherT2[byte(k[(i+2)%4]>>8)] ^
				areaCipherT3[byte(k[(i+1)%4])]
		}
		next[0] ^= areaCipherT6[round]
		k = next
	}
	c.decryptKeys[0], c.decryptKeys[12] = c.encryptKeys[12], c.encryptKeys[0]
	for r := 1; r < 12; r++ {
		for j, v := range c.encryptKeys[12-r] {
			c.decryptKeys[r][j] = areaCipherT0[byte(areaCipherT4[byte(v>>24)])] ^
				areaCipherT1[byte(areaCipherT4[byte(v>>16)])] ^
				areaCipherT2[byte(areaCipherT4[byte(v>>8)])] ^
				areaCipherT3[byte(areaCipherT4[byte(v)])]
		}
	}
	return c, nil
}

func (*areaCipher) BlockSize() int            { return 16 }
func (c *areaCipher) Encrypt(dst, src []byte) { areaCipherBlock(dst, src, &c.encryptKeys) }
func (c *areaCipher) Decrypt(dst, src []byte) { areaCipherBlock(dst, src, &c.decryptKeys) }

func areaCipherBlock(dst, src []byte, keys *[13][4]uint32) {
	if len(src) < 16 || len(dst) < 16 {
		panic("area cipher: short block")
	}
	var state [4]uint32
	for i := range state {
		state[i] = binary.BigEndian.Uint32(src[i*4:]) ^ keys[0][i]
	}
	for r := 1; r <= 12; r++ {
		var next [4]uint32
		for j := range next {
			shift := uint(24 - j*8)
			a, b := areaCipherT0[byte(state[0]>>shift)], areaCipherT1[byte(state[1]>>shift)]
			c, d := areaCipherT2[byte(state[2]>>shift)], areaCipherT3[byte(state[3]>>shift)]
			if r == 12 {
				a &= 0xff000000
				b &= 0x00ff0000
				c &= 0x0000ff00
				d &= 0x000000ff
			}
			next[j] = a ^ b ^ c ^ d ^ keys[r][j]
		}
		state = next
	}
	for i, v := range state {
		binary.BigEndian.PutUint32(dst[i*4:], v)
	}
}
