package wire

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// Independent vectors execute only the supplied client's pure native cipher
// routines in bounded emulation. They are not generated by this Go codec.
func TestNativeWorldCiphers(t *testing.T) {
	checkNativeWorldCiphers(t, "testdata/native_world_ciphers.json")
}
func TestNativeQuestCipher(t *testing.T) {
	checkNativeWorldCiphers(t, "testdata/native_quest_cipher.json")
}
func checkNativeWorldCiphers(t *testing.T, path string) {
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var rows []struct{ Algorithm, Key, Plain, Cipher string }
	if err = json.Unmarshal(b, &rows); err != nil {
		t.Fatal(err)
	}
	for _, r := range rows {
		t.Run(r.Algorithm+"/"+r.Key[:2], func(t *testing.T) {
			id := uint16(31)
			if r.Algorithm == "blowfish" {
				id = 35
			}
			if r.Algorithm == "kasumi" {
				id = 34
			}
			decode := func(s string) []byte {
				p, e := hex.DecodeString(s)
				if e != nil {
					t.Fatal(e)
				}
				return p
			}
			keys := make([]byte, SessionKeyBytes)
			off := 0
			for _, n := range keyLengths[:int(id)%14] {
				off += n
			}
			copy(keys[off:], decode(r.Key))
			p, c := decode(r.Plain), decode(r.Cipher)
			got, e := EncryptPayload(keys, id, p)
			if e != nil || !bytes.Equal(got, c) {
				t.Fatalf("native encrypt mismatch: %x %v", got, e)
			}
			got, e = DecryptPayload(keys, id, c)
			if e != nil || !bytes.Equal(got, p) {
				t.Fatalf("native decrypt mismatch: %x %v", got, e)
			}
		})
	}
}
