"""Slot11 pure-code native oracle and exact embedded table extraction."""
import json,struct
from pathlib import Path
from native_cipher_oracle import Oracle
o=Oracle();root=Path(__file__).parent.parent/'dfo-lan/internal/game/wire'
tables=[]
for i,address in enumerate([0x14b17c160,0x14b17c960,0x14b17d160,0x14b17d960,0x14b17e160,0x14b17e960,0x14b17f160,0x14b17b960]):
 v=struct.unpack('<256Q',o.pe.get_data(address-o.base,2048))
 tables.append('var combatT'+str(i)+' = [...]uint64{\n'+'\n'.join(' '+', '.join(f'0x{x:016x}' for x in v[j:j+4])+',' for j in range(0,256,4))+'\n}')
(root/'combat_cipher_tables.go').write_text('// Generated by combat_cipher_oracle.py from the supplied client.\npackage wire\n\n'+'\n'.join(tables),encoding='utf-8')
rows=[]
for seed in (0,1,71,238):
 key=bytes((i+seed)&255 for i in range(16));plain=bytes((i*7+seed)&255 for i in range(24))
 encrypted=o.cipher(key,plain,0x146d945d0,0x146d945c0,0x146d945a0,8,8)
 rows.append(dict(key=key.hex(),plain=plain.hex(),cipher=encrypted.hex(),setup='146d945d0',encrypt='146d945c0',decrypt='146d945a0'))
(root/'testdata/native_combat_cipher.json').write_text(json.dumps(rows,indent=2),encoding='utf-8')
print('slot11 native vectors',len(rows))
