// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adventure.sql

package sqlcgensqlite

import (
	"context"
	"encoding/json"
	"time"
)

const adventureCollectionEquipment = `-- name: AdventureCollectionEquipment :one
SELECT CAST(COALESCE(json_extract(a.data,'$.collection_equipment'),'{}') AS BLOB) AS equipment FROM characters c
LEFT JOIN account_adventures a ON a.account_id=c.account_id
WHERE c.account_id=?1 AND c.id=?2 AND c.deleted_at IS NULL
`

type AdventureCollectionEquipmentParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) AdventureCollectionEquipment(ctx context.Context, arg AdventureCollectionEquipmentParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, adventureCollectionEquipment, arg.AccountID, arg.CharacterID)
	var equipment []byte
	err := row.Scan(&equipment)
	return equipment, err
}

const adventureEquipmentRegistered = `-- name: AdventureEquipmentRegistered :one
SELECT CAST(COALESCE(json_extract(a.data,'$.collection_equipment.'||CAST(CAST(?1 AS INTEGER) AS TEXT)),0) AS BOOLEAN) AS registered
FROM characters c LEFT JOIN account_adventures a ON a.account_id=c.account_id
WHERE c.account_id=?2 AND c.id=?3 AND c.deleted_at IS NULL
`

type AdventureEquipmentRegisteredParams struct {
	Template    int64
	AccountID   int64
	CharacterID int64
}

func (q *Queries) AdventureEquipmentRegistered(ctx context.Context, arg AdventureEquipmentRegisteredParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, adventureEquipmentRegistered, arg.Template, arg.AccountID, arg.CharacterID)
	var registered bool
	err := row.Scan(&registered)
	return registered, err
}

const adventureEventReceipt = `-- name: AdventureEventReceipt :one
SELECT outcome FROM character_events WHERE character_id=?1
AND event_key=?2 AND model='account-adventure-v1'
`

type AdventureEventReceiptParams struct {
	CharacterID int64
	EventKey    string
}

func (q *Queries) AdventureEventReceipt(ctx context.Context, arg AdventureEventReceiptParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, adventureEventReceipt, arg.CharacterID, arg.EventKey)
	var outcome json.RawMessage
	err := row.Scan(&outcome)
	return outcome, err
}

const adventureLevel = `-- name: AdventureLevel :one

SELECT CAST(COALESCE(a.level,1) AS INTEGER) AS level FROM characters c
LEFT JOIN account_adventures a ON a.account_id=c.account_id
WHERE c.account_id=?1 AND c.id=?2 AND c.deleted_at IS NULL
`

type AdventureLevelParams struct {
	AccountID   int64
	CharacterID int64
}

// SQLite query fork of sql/postgres/queries/adventure.sql (dual-engine, S3).
//
// The PostgreSQL file stays untouched and remains authoritative for the PG path.
// Dialect rules applied here are the ones in docs/sqlite-query-port-guide.md and
// restated in context in the header of sqlite/queries/core.sql:
//   - FOR UPDATE / FOR NO KEY UPDATE / FOR SHARE -> REMOVED. SQLite has no row
//     locks and rejects the clause; writers are serialized by BEGIN IMMEDIATE.
//     Lock queries keep their name and their ownership predicate.
//   - sqlc.arg(x)::type -> CAST(sqlc.arg(x) AS type). Spike rule R-1: a bare
//     expression infers interface{} and cannot enter the shared query interface,
//     so every expression result gets an explicit CAST.
//   - JSON parameters are deliberately NOT wrapped in CAST(... AS TEXT): that
//     turns the parameter into a string, which database/sql cannot scan into
//     json.RawMessage. JSON columns are BLOB here, and a BLOB parameter/result is
//     generated as []byte, which json.RawMessage is assignable to.
//   - jsonb operators -> JSON1: data->'k' -> json_extract(x,'$.k'),
//     GREATEST(a,b) -> scalar max(a,b). now() -> integer microseconds, matching
//     the DDL defaults and the driver's unix_micro representation.
//   - DATE columns hold integer microseconds (DDL header, D29). npc_favor's
//     last_gift_day is therefore written from the caller's yyyy-mm-dd string
//     through julianday() and read back as yyyy-mm-dd text through strftime(),
//     which keeps the generated Go type string in both directions.
//   - account_bleeding_mine_teams.members is a PostgreSQL bigint[] and a JSON
//     array in a BLOB here (D27); sqlc types it []byte, so the caller owns the
//     JSON encoding.
//   - The RETURNING alias of ReserveFavorGift is not honoured by sqlc's SQLite
//     engine: the text day column is named positionally (Column3) where
//     PostgreSQL names it LastGiftDay. Value and Go type (string) are unchanged.
func (q *Queries) AdventureLevel(ctx context.Context, arg AdventureLevelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adventureLevel, arg.AccountID, arg.CharacterID)
	var level int64
	err := row.Scan(&level)
	return level, err
}

const bleedingMineTeams = `-- name: BleedingMineTeams :many
SELECT team,members FROM account_bleeding_mine_teams WHERE account_id=?1
`

type BleedingMineTeamsRow struct {
	Team    int32
	Members []byte
}

func (q *Queries) BleedingMineTeams(ctx context.Context, accountID int64) ([]BleedingMineTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, bleedingMineTeams, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BleedingMineTeamsRow
	for rows.Next() {
		var i BleedingMineTeamsRow
		if err := rows.Scan(&i.Team, &i.Members); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureAdventure = `-- name: EnsureAdventure :exec
INSERT INTO account_adventures(account_id,name,created_at)
SELECT id,CAST(?1 AS TEXT),created_at FROM accounts WHERE id=CAST(?2 AS INTEGER) ON CONFLICT DO NOTHING
`

type EnsureAdventureParams struct {
	Name      string
	AccountID int64
}

func (q *Queries) EnsureAdventure(ctx context.Context, arg EnsureAdventureParams) error {
	_, err := q.db.ExecContext(ctx, ensureAdventure, arg.Name, arg.AccountID)
	return err
}

const ensureBleedingMineRewards = `-- name: EnsureBleedingMineRewards :exec
INSERT INTO account_bleeding_mine_rewards(account_id) VALUES(?1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureBleedingMineRewards(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, ensureBleedingMineRewards, accountID)
	return err
}

const ensureOwnedAdventure = `-- name: EnsureOwnedAdventure :exec
INSERT INTO account_adventures(account_id,name,created_at)
SELECT a.id,CAST(?1 AS TEXT),a.created_at FROM accounts a JOIN characters c ON c.account_id=a.id
WHERE a.id=CAST(?2 AS INTEGER) AND c.id=CAST(?3 AS INTEGER) AND c.deleted_at IS NULL
ON CONFLICT(account_id) DO NOTHING
`

type EnsureOwnedAdventureParams struct {
	Name        string
	AccountID   int64
	CharacterID int64
}

func (q *Queries) EnsureOwnedAdventure(ctx context.Context, arg EnsureOwnedAdventureParams) error {
	_, err := q.db.ExecContext(ctx, ensureOwnedAdventure, arg.Name, arg.AccountID, arg.CharacterID)
	return err
}

const firstActiveCharacterName = `-- name: FirstActiveCharacterName :one
SELECT name FROM characters WHERE account_id=?1 AND deleted_at IS NULL ORDER BY id LIMIT 1
`

func (q *Queries) FirstActiveCharacterName(ctx context.Context, accountID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, firstActiveCharacterName, accountID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listFavor = `-- name: ListFavor :many
SELECT npc_id,point FROM npc_favor WHERE character_id=?1 AND point>0 ORDER BY npc_id
`

type ListFavorRow struct {
	NpcID int64
	Point int64
}

func (q *Queries) ListFavor(ctx context.Context, characterID int64) ([]ListFavorRow, error) {
	rows, err := q.db.QueryContext(ctx, listFavor, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavorRow
	for rows.Next() {
		var i ListFavorRow
		if err := rows.Scan(&i.NpcID, &i.Point); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAdventure = `-- name: LoadAdventure :one
SELECT a.name,a.level,a.experience,a.created_at,a.data FROM account_adventures a JOIN characters c ON c.account_id=a.account_id
WHERE a.account_id=?1 AND c.id=?2 AND c.deleted_at IS NULL
`

type LoadAdventureParams struct {
	AccountID   int64
	CharacterID int64
}

type LoadAdventureRow struct {
	Name       string
	Level      int32
	Experience int64
	CreatedAt  time.Time
	Data       json.RawMessage
}

func (q *Queries) LoadAdventure(ctx context.Context, arg LoadAdventureParams) (LoadAdventureRow, error) {
	row := q.db.QueryRowContext(ctx, loadAdventure, arg.AccountID, arg.CharacterID)
	var i LoadAdventureRow
	err := row.Scan(
		&i.Name,
		&i.Level,
		&i.Experience,
		&i.CreatedAt,
		&i.Data,
	)
	return i, err
}

const lockAdventure = `-- name: LockAdventure :one
SELECT name,level,experience,created_at,data FROM account_adventures WHERE account_id=?1
`

type LockAdventureRow struct {
	Name       string
	Level      int32
	Experience int64
	CreatedAt  time.Time
	Data       json.RawMessage
}

// Lock query; the FOR UPDATE is replaced by the engine-wide BEGIN IMMEDIATE write
// serialization. Name and projection are unchanged.
func (q *Queries) LockAdventure(ctx context.Context, accountID int64) (LockAdventureRow, error) {
	row := q.db.QueryRowContext(ctx, lockAdventure, accountID)
	var i LockAdventureRow
	err := row.Scan(
		&i.Name,
		&i.Level,
		&i.Experience,
		&i.CreatedAt,
		&i.Data,
	)
	return i, err
}

const lockBleedingMineRewards = `-- name: LockBleedingMineRewards :one
SELECT state FROM account_bleeding_mine_rewards WHERE account_id=?1
`

// Lock query; lock clause removed (see LockAdventure).
func (q *Queries) LockBleedingMineRewards(ctx context.Context, accountID int64) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, lockBleedingMineRewards, accountID)
	var state json.RawMessage
	err := row.Scan(&state)
	return state, err
}

const reserveFavorGift = `-- name: ReserveFavorGift :one
INSERT INTO npc_favor(character_id,npc_id,point,daily_count,last_gift_day)
VALUES(?1,?2,0,1,
CAST((julianday(CAST(?3 AS TEXT)) - 2440587.5) * 86400000000 AS DATE))
ON CONFLICT(character_id,npc_id) DO UPDATE SET
daily_count=CASE WHEN EXCLUDED.last_gift_day>npc_favor.last_gift_day OR npc_favor.last_gift_day IS NULL THEN 1 ELSE npc_favor.daily_count+1 END,
last_gift_day=max(EXCLUDED.last_gift_day,coalesce(npc_favor.last_gift_day,EXCLUDED.last_gift_day)),point=npc_favor.point,
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
RETURNING point,daily_count,CAST(strftime('%Y-%m-%d',last_gift_day/1000000,'unixepoch') AS TEXT) AS "last_gift_day"
`

type ReserveFavorGiftParams struct {
	CharacterID int64
	NpcID       int64
	Day         string
}

type ReserveFavorGiftRow struct {
	Point      int64
	DailyCount int32
	Column3    string
}

// GREATEST(a,b) -> max(a,b), with the NULL handling spelled out: the scalar
// max() returns NULL when any argument is NULL while GREATEST ignores NULLs, and
// npc_favor.last_gift_day is nullable. The day is stored as DATE microseconds
// (julianday) and returned as yyyy-mm-dd text (strftime).
func (q *Queries) ReserveFavorGift(ctx context.Context, arg ReserveFavorGiftParams) (ReserveFavorGiftRow, error) {
	row := q.db.QueryRowContext(ctx, reserveFavorGift, arg.CharacterID, arg.NpcID, arg.Day)
	var i ReserveFavorGiftRow
	err := row.Scan(&i.Point, &i.DailyCount, &i.Column3)
	return i, err
}

const saveAdventure = `-- name: SaveAdventure :exec
UPDATE account_adventures SET level=CAST(?1 AS INTEGER),experience=?2,data=?3
WHERE account_id=?4
`

type SaveAdventureParams struct {
	Level      int64
	Experience int64
	Data       json.RawMessage
	AccountID  int64
}

func (q *Queries) SaveAdventure(ctx context.Context, arg SaveAdventureParams) error {
	_, err := q.db.ExecContext(ctx, saveAdventure,
		arg.Level,
		arg.Experience,
		arg.Data,
		arg.AccountID,
	)
	return err
}

const saveBleedingMineRewards = `-- name: SaveBleedingMineRewards :exec
UPDATE account_bleeding_mine_rewards SET state=?1,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)) WHERE account_id=?2
`

type SaveBleedingMineRewardsParams struct {
	State     json.RawMessage
	AccountID int64
}

func (q *Queries) SaveBleedingMineRewards(ctx context.Context, arg SaveBleedingMineRewardsParams) error {
	_, err := q.db.ExecContext(ctx, saveBleedingMineRewards, arg.State, arg.AccountID)
	return err
}

const saveBleedingMineTeam = `-- name: SaveBleedingMineTeam :exec
INSERT INTO account_bleeding_mine_teams(account_id,team,members)
VALUES(?1,?2,?3)
ON CONFLICT(account_id,team) DO UPDATE SET members=EXCLUDED.members,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveBleedingMineTeamParams struct {
	AccountID int64
	Team      int32
	Members   []byte
}

func (q *Queries) SaveBleedingMineTeam(ctx context.Context, arg SaveBleedingMineTeamParams) error {
	_, err := q.db.ExecContext(ctx, saveBleedingMineTeam, arg.AccountID, arg.Team, arg.Members)
	return err
}

const saveFavorPoint = `-- name: SaveFavorPoint :exec
UPDATE npc_favor SET point=?1,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
WHERE character_id=?2 AND npc_id=?3
`

type SaveFavorPointParams struct {
	Point       int64
	CharacterID int64
	NpcID       int64
}

func (q *Queries) SaveFavorPoint(ctx context.Context, arg SaveFavorPointParams) error {
	_, err := q.db.ExecContext(ctx, saveFavorPoint, arg.Point, arg.CharacterID, arg.NpcID)
	return err
}
