// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package sqlcgensqlite

import (
	"context"
	"encoding/json"
	"time"
)

const accountCharacterStates = `-- name: AccountCharacterStates :many
SELECT state FROM characters WHERE account_id=?1
`

func (q *Queries) AccountCharacterStates(ctx context.Context, accountID int64) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, accountCharacterStates, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []json.RawMessage
	for rows.Next() {
		var state json.RawMessage
		if err := rows.Scan(&state); err != nil {
			return nil, err
		}
		items = append(items, state)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accounts = `-- name: Accounts :many
SELECT id,username FROM accounts ORDER BY id
`

type AccountsRow struct {
	ID       int64
	Username string
}

func (q *Queries) Accounts(ctx context.Context) ([]AccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, accounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountsRow
	for rows.Next() {
		var i AccountsRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminCharacter = `-- name: AdminCharacter :one
SELECT id,account_id,wire_id,name,profession,create_request,config_version,state,created_at,fixed_slot
FROM characters WHERE id=?1 AND deleted_at IS NULL
`

type AdminCharacterRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	CreatedAt     time.Time
	FixedSlot     int16
}

func (q *Queries) AdminCharacter(ctx context.Context, characterID int64) (AdminCharacterRow, error) {
	row := q.db.QueryRowContext(ctx, adminCharacter, characterID)
	var i AdminCharacterRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.WireID,
		&i.Name,
		&i.Profession,
		&i.CreateRequest,
		&i.ConfigVersion,
		&i.State,
		&i.CreatedAt,
		&i.FixedSlot,
	)
	return i, err
}

const adminCharacters = `-- name: AdminCharacters :many
SELECT id,account_id,wire_id,name,profession,create_request,config_version,state,created_at,fixed_slot
FROM characters WHERE account_id=?1 AND deleted_at IS NULL ORDER BY wire_id
`

type AdminCharactersRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	CreatedAt     time.Time
	FixedSlot     int16
}

func (q *Queries) AdminCharacters(ctx context.Context, accountID int64) ([]AdminCharactersRow, error) {
	rows, err := q.db.QueryContext(ctx, adminCharacters, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminCharactersRow
	for rows.Next() {
		var i AdminCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.WireID,
			&i.Name,
			&i.Profession,
			&i.CreateRequest,
			&i.ConfigVersion,
			&i.State,
			&i.CreatedAt,
			&i.FixedSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const archiveCharacter = `-- name: ArchiveCharacter :exec
UPDATE characters SET deleted_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
WHERE id=?1 AND account_id=?2 AND deleted_at IS NULL
`

type ArchiveCharacterParams struct {
	CharacterID int64
	AccountID   int64
}

func (q *Queries) ArchiveCharacter(ctx context.Context, arg ArchiveCharacterParams) error {
	_, err := q.db.ExecContext(ctx, archiveCharacter, arg.CharacterID, arg.AccountID)
	return err
}

const characterAllocation = `-- name: CharacterAllocation :one
SELECT count(*) FILTER (WHERE deleted_at IS NULL) AS active_count,
coalesce(max(wire_id),0)+1 AS next_wire_id,
CAST((coalesce(max(coalesce(roster_order,wire_id)),0)+1) AS INTEGER) AS next_roster_order
FROM characters WHERE account_id=?1
`

type CharacterAllocationRow struct {
	ActiveCount     int64
	NextWireID      int64
	NextRosterOrder int64
}

func (q *Queries) CharacterAllocation(ctx context.Context, accountID int64) (CharacterAllocationRow, error) {
	row := q.db.QueryRowContext(ctx, characterAllocation, accountID)
	var i CharacterAllocationRow
	err := row.Scan(&i.ActiveCount, &i.NextWireID, &i.NextRosterOrder)
	return i, err
}

const characterAtRosterSlot = `-- name: CharacterAtRosterSlot :one
SELECT id,name FROM characters WHERE account_id=?1 AND deleted_at IS NULL
ORDER BY coalesce(roster_order,wire_id),wire_id LIMIT 1 OFFSET CAST(?2 AS INTEGER)
`

type CharacterAtRosterSlotParams struct {
	AccountID  int64
	RosterSlot int64
}

type CharacterAtRosterSlotRow struct {
	ID   int64
	Name string
}

func (q *Queries) CharacterAtRosterSlot(ctx context.Context, arg CharacterAtRosterSlotParams) (CharacterAtRosterSlotRow, error) {
	row := q.db.QueryRowContext(ctx, characterAtRosterSlot, arg.AccountID, arg.RosterSlot)
	var i CharacterAtRosterSlotRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const characterEventModel = `-- name: CharacterEventModel :one
SELECT model FROM character_events WHERE character_id=?1 AND event_key=?2
`

type CharacterEventModelParams struct {
	CharacterID int64
	EventKey    string
}

func (q *Queries) CharacterEventModel(ctx context.Context, arg CharacterEventModelParams) (string, error) {
	row := q.db.QueryRowContext(ctx, characterEventModel, arg.CharacterID, arg.EventKey)
	var model string
	err := row.Scan(&model)
	return model, err
}

const characterEventReceipt = `-- name: CharacterEventReceipt :one
SELECT e.outcome FROM character_events e JOIN characters c ON c.id=e.character_id
WHERE c.account_id=?1 AND c.id=?2 AND e.event_key=?3
`

type CharacterEventReceiptParams struct {
	AccountID   int64
	CharacterID int64
	EventKey    string
}

func (q *Queries) CharacterEventReceipt(ctx context.Context, arg CharacterEventReceiptParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, characterEventReceipt, arg.AccountID, arg.CharacterID, arg.EventKey)
	var outcome json.RawMessage
	err := row.Scan(&outcome)
	return outcome, err
}

const characterOwned = `-- name: CharacterOwned :one
SELECT EXISTS(SELECT 1 FROM characters WHERE account_id=?1 AND id=?2)
`

type CharacterOwnedParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) CharacterOwned(ctx context.Context, arg CharacterOwnedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, characterOwned, arg.AccountID, arg.CharacterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const characterSeason = `-- name: CharacterSeason :one
SELECT CAST(json_object('season_level',json(COALESCE(json_extract(a.data,'$.season_level'),'{}'))) AS BLOB) AS state
FROM characters c LEFT JOIN account_adventures a ON a.account_id=c.account_id
WHERE c.account_id=?1 AND c.id=?2 AND c.deleted_at IS NULL
`

type CharacterSeasonParams struct {
	AccountID   int64
	CharacterID int64
}

// Same BLOB round trip as CharactersWithAdventure: json_object returns TEXT.
func (q *Queries) CharacterSeason(ctx context.Context, arg CharacterSeasonParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, characterSeason, arg.AccountID, arg.CharacterID)
	var state []byte
	err := row.Scan(&state)
	return state, err
}

const characters = `-- name: Characters :many
SELECT id,account_id,wire_id,name,profession,create_request,config_version,state,created_at,fixed_slot
FROM characters WHERE account_id=?1 AND deleted_at IS NULL
ORDER BY coalesce(roster_order,wire_id),wire_id
`

type CharactersRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	CreatedAt     time.Time
	FixedSlot     int16
}

func (q *Queries) Characters(ctx context.Context, accountID int64) ([]CharactersRow, error) {
	rows, err := q.db.QueryContext(ctx, characters, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharactersRow
	for rows.Next() {
		var i CharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.WireID,
			&i.Name,
			&i.Profession,
			&i.CreateRequest,
			&i.ConfigVersion,
			&i.State,
			&i.CreatedAt,
			&i.FixedSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const charactersWithAdventure = `-- name: CharactersWithAdventure :many
SELECT c.id,c.account_id,c.wire_id,c.name,c.profession,c.create_request,c.config_version,
CAST(json_set(c.state,'$.season_level',json(COALESCE(json_extract(a.data,'$.season_level'),'{}'))) AS BLOB) AS state,
c.created_at,c.fixed_slot FROM characters c LEFT JOIN account_adventures a ON a.account_id=c.account_id
WHERE c.account_id=?1 AND c.deleted_at IS NULL
ORDER BY coalesce(c.roster_order,c.wire_id),c.wire_id
`

type CharactersWithAdventureRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         []byte
	CreatedAt     time.Time
	FixedSlot     int16
}

// json_set returns TEXT, and a TEXT value in a BLOB json column cannot be scanned
// into json.RawMessage, so the result is cast back to BLOB. Wrapping the merged
// value in json(...) keeps it a JSON value rather than a quoted string.
func (q *Queries) CharactersWithAdventure(ctx context.Context, accountID int64) ([]CharactersWithAdventureRow, error) {
	rows, err := q.db.QueryContext(ctx, charactersWithAdventure, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharactersWithAdventureRow
	for rows.Next() {
		var i CharactersWithAdventureRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.WireID,
			&i.Name,
			&i.Profession,
			&i.CreateRequest,
			&i.ConfigVersion,
			&i.State,
			&i.CreatedAt,
			&i.FixedSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters(account_id,wire_id,name,profession,create_request,config_version,state,roster_order,fixed_slot)
VALUES(?1,?2,?3,?4,?5,
?6,?7,CAST(?8 AS INTEGER),0) RETURNING id,created_at
`

type CreateCharacterParams struct {
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	RosterOrder   int64
}

type CreateCharacterRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (CreateCharacterRow, error) {
	row := q.db.QueryRowContext(ctx, createCharacter,
		arg.AccountID,
		arg.WireID,
		arg.Name,
		arg.Profession,
		arg.CreateRequest,
		arg.ConfigVersion,
		arg.State,
		arg.RosterOrder,
	)
	var i CreateCharacterRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const developmentAccount = `-- name: DevelopmentAccount :one
INSERT INTO accounts(username,development_only) VALUES(?1,1)
ON CONFLICT(username) DO UPDATE SET username=EXCLUDED.username
WHERE accounts.development_only RETURNING id
`

func (q *Queries) DevelopmentAccount(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, developmentAccount, username)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const developmentCharacterAccount = `-- name: DevelopmentCharacterAccount :one
SELECT c.account_id FROM characters c JOIN accounts a ON a.id=c.account_id
WHERE c.id=?1 AND a.development_only
`

func (q *Queries) DevelopmentCharacterAccount(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, developmentCharacterAccount, characterID)
	var account_id int64
	err := row.Scan(&account_id)
	return account_id, err
}

const hasCharacterEvent = `-- name: HasCharacterEvent :one
SELECT EXISTS(SELECT 1 FROM character_events WHERE character_id=?1 AND event_key=?2)
`

type HasCharacterEventParams struct {
	CharacterID int64
	EventKey    string
}

func (q *Queries) HasCharacterEvent(ctx context.Context, arg HasCharacterEventParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasCharacterEvent, arg.CharacterID, arg.EventKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockAccount = `-- name: LockAccount :one
SELECT id FROM accounts WHERE id=?1
`

// Lock query; the FOR UPDATE is replaced by the engine-wide BEGIN IMMEDIATE write
// serialization (see the file header). Name and predicate are unchanged.
func (q *Queries) LockAccount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockAccount, accountID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockAccountState = `-- name: LockAccountState :one
SELECT id FROM accounts WHERE id=?1
`

// Serialize shared callback state; the account row is read inside the same
// serialized write transaction, so no row lock is required.
func (q *Queries) LockAccountState(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockAccountState, accountID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockActiveCharacterID = `-- name: LockActiveCharacterID :one
SELECT id FROM characters WHERE id=?1 AND deleted_at IS NULL
`

func (q *Queries) LockActiveCharacterID(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockActiveCharacterID, characterID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockActiveCharacterState = `-- name: LockActiveCharacterState :one
SELECT state FROM characters WHERE account_id=?1 AND id=?2 AND deleted_at IS NULL
`

type LockActiveCharacterStateParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) LockActiveCharacterState(ctx context.Context, arg LockActiveCharacterStateParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, lockActiveCharacterState, arg.AccountID, arg.CharacterID)
	var state json.RawMessage
	err := row.Scan(&state)
	return state, err
}

const lockCharacter = `-- name: LockCharacter :one
SELECT id,account_id,wire_id,name,profession,create_request,config_version,state,created_at,
0 AS fixed_slot FROM characters
WHERE account_id=?1 AND id=?2 AND deleted_at IS NULL
`

type LockCharacterParams struct {
	AccountID   int64
	CharacterID int64
}

type LockCharacterRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	CreatedAt     time.Time
	FixedSlot     int64
}

// Event callbacks historically leave FixedSlot at zero; preserve that projection.
func (q *Queries) LockCharacter(ctx context.Context, arg LockCharacterParams) (LockCharacterRow, error) {
	row := q.db.QueryRowContext(ctx, lockCharacter, arg.AccountID, arg.CharacterID)
	var i LockCharacterRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.WireID,
		&i.Name,
		&i.Profession,
		&i.CreateRequest,
		&i.ConfigVersion,
		&i.State,
		&i.CreatedAt,
		&i.FixedSlot,
	)
	return i, err
}

const lockCharacterOwner = `-- name: LockCharacterOwner :one
SELECT id FROM characters WHERE account_id=?1 AND id=?2
AND deleted_at IS NULL
`

type LockCharacterOwnerParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) LockCharacterOwner(ctx context.Context, arg LockCharacterOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockCharacterOwner, arg.AccountID, arg.CharacterID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockCharacterOwnerIncludingDeleted = `-- name: LockCharacterOwnerIncludingDeleted :one
SELECT id FROM characters WHERE account_id=?1 AND id=?2
`

type LockCharacterOwnerIncludingDeletedParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) LockCharacterOwnerIncludingDeleted(ctx context.Context, arg LockCharacterOwnerIncludingDeletedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockCharacterOwnerIncludingDeleted, arg.AccountID, arg.CharacterID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockCharacterRoster = `-- name: LockCharacterRoster :many
SELECT id,fixed_slot FROM characters WHERE account_id=?1 AND deleted_at IS NULL
ORDER BY coalesce(roster_order,wire_id),wire_id
`

type LockCharacterRosterRow struct {
	ID        int64
	FixedSlot int16
}

func (q *Queries) LockCharacterRoster(ctx context.Context, accountID int64) ([]LockCharacterRosterRow, error) {
	rows, err := q.db.QueryContext(ctx, lockCharacterRoster, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockCharacterRosterRow
	for rows.Next() {
		var i LockCharacterRosterRow
		if err := rows.Scan(&i.ID, &i.FixedSlot); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCharacterVersion = `-- name: LockCharacterVersion :one
SELECT config_version FROM characters WHERE account_id=?1 AND id=?2
AND deleted_at IS NULL
`

type LockCharacterVersionParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) LockCharacterVersion(ctx context.Context, arg LockCharacterVersionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lockCharacterVersion, arg.AccountID, arg.CharacterID)
	var config_version string
	err := row.Scan(&config_version)
	return config_version, err
}

const nameExists = `-- name: NameExists :one

SELECT EXISTS(SELECT 1 FROM characters WHERE lower(name)=lower(CAST(?1 AS TEXT)))
`

// SQLite query fork of sql/postgres/queries/core.sql (dual-engine, S3).
//
// Ported for the core slice only: accounts, characters, character_events. The
// PostgreSQL file stays untouched and remains authoritative for the PG path.
//
// Dialect rules applied (design doc sec.3.2, plus the S0 spike's two hard rules):
//   - FOR UPDATE / FOR NO KEY UPDATE / FOR SHARE -> REMOVED. SQLite has no row
//     locks and its grammar rejects the clause outright; the engine serializes
//     writers with BEGIN IMMEDIATE (DSN _txlock=immediate). Lock queries keep
//     their name and their ownership predicate, so callers are unchanged.
//   - `sqlc.arg(x)::type` -> CAST(sqlc.arg(x) AS type). SPIKE RULE R-1: an
//     expression sqlc cannot type infers interface{} and cannot enter the shared
//     query interface, so every bare expression gets an explicit CAST.
//   - JSON parameters are deliberately NOT cast. CAST(sqlc.arg(state) AS TEXT)
//     would make the generated parameter a string, and SQLite would then return a
//     string that database/sql cannot scan into json.RawMessage. Keeping the
//     value a []byte keeps json.RawMessage in BOTH directions (D24).
//   - jsonb operators -> json_extract / json_set (+ json() to keep a JSON value
//     a value rather than a string). Anything whose JSON semantics are subtle is
//     flagged for a runtime golden test in S4 rather than assumed here.
//   - now() -> integer microseconds, matching the DDL defaults and the driver's
//     _inttotime=1 + _time_integer_format=unix_micro representation.
//   - GREATEST(a,b) -> max(a,b) (SQLite scalar form).
//
// Still not ported, with reasons (design doc sec.3.5):
//   - TrySharedAdminGuard - PostgreSQL advisory lock; SQLite needs the lease-row
//     design (sec.3.3), so it cannot be translated into one statement.
//
// DatabaseName is ported below through pragma_database_list, and
// CharactersWithAdventure / CharacterSeason through json_set / json_object.
func (q *Queries) NameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, nameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const pendingMoonRewardRuns = `-- name: PendingMoonRewardRuns :many
SELECT substr(event_key,12) AS run_id FROM character_events e
WHERE e.character_id=?1 AND e.model=?2 AND e.event_key LIKE 'moon-clear:%'
AND NOT EXISTS(SELECT 1 FROM character_events g WHERE g.character_id=e.character_id
AND g.event_key='moon-grant:'||substr(e.event_key,12)) ORDER BY created_at LIMIT 16
`

type PendingMoonRewardRunsParams struct {
	CharacterID int64
	Model       string
}

func (q *Queries) PendingMoonRewardRuns(ctx context.Context, arg PendingMoonRewardRunsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, pendingMoonRewardRuns, arg.CharacterID, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var run_id string
		if err := rows.Scan(&run_id); err != nil {
			return nil, err
		}
		items = append(items, run_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCharacterEvent = `-- name: RecordCharacterEvent :exec
INSERT INTO character_events(character_id,event_key,config_version,model,outcome)
VALUES(?1,?2,?3,?4,?5)
`

type RecordCharacterEventParams struct {
	CharacterID   int64
	EventKey      string
	ConfigVersion string
	Model         string
	Outcome       json.RawMessage
}

func (q *Queries) RecordCharacterEvent(ctx context.Context, arg RecordCharacterEventParams) error {
	_, err := q.db.ExecContext(ctx, recordCharacterEvent,
		arg.CharacterID,
		arg.EventKey,
		arg.ConfigVersion,
		arg.Model,
		arg.Outcome,
	)
	return err
}

const recordCharacterFame = `-- name: RecordCharacterFame :one
UPDATE characters SET max_fame=max(max_fame,CAST(?1 AS INTEGER))
WHERE account_id=?2 AND id=?3 AND deleted_at IS NULL RETURNING max_fame
`

type RecordCharacterFameParams struct {
	CurrentFame int64
	AccountID   int64
	CharacterID int64
}

func (q *Queries) RecordCharacterFame(ctx context.Context, arg RecordCharacterFameParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, recordCharacterFame, arg.CurrentFame, arg.AccountID, arg.CharacterID)
	var max_fame int32
	err := row.Scan(&max_fame)
	return max_fame, err
}

const saveCharacterSlot = `-- name: SaveCharacterSlot :exec
UPDATE characters SET roster_order=CAST(?1 AS INTEGER),fixed_slot=?2
WHERE account_id=?3 AND id=?4
`

type SaveCharacterSlotParams struct {
	RosterOrder int64
	FixedSlot   int16
	AccountID   int64
	CharacterID int64
}

func (q *Queries) SaveCharacterSlot(ctx context.Context, arg SaveCharacterSlotParams) error {
	_, err := q.db.ExecContext(ctx, saveCharacterSlot,
		arg.RosterOrder,
		arg.FixedSlot,
		arg.AccountID,
		arg.CharacterID,
	)
	return err
}

const shareActiveCharacterIDs = `-- name: ShareActiveCharacterIDs :many
SELECT id FROM characters WHERE account_id=?1 AND deleted_at IS NULL ORDER BY id
`

func (q *Queries) ShareActiveCharacterIDs(ctx context.Context, accountID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, shareActiveCharacterIDs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shareActiveCharacterState = `-- name: ShareActiveCharacterState :one
SELECT state FROM characters WHERE account_id=?1 AND id=?2 AND deleted_at IS NULL
`

type ShareActiveCharacterStateParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) ShareActiveCharacterState(ctx context.Context, arg ShareActiveCharacterStateParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, shareActiveCharacterState, arg.AccountID, arg.CharacterID)
	var state json.RawMessage
	err := row.Scan(&state)
	return state, err
}

const updateCharacterState = `-- name: UpdateCharacterState :exec
UPDATE characters SET state=?1 WHERE id=?2
`

type UpdateCharacterStateParams struct {
	State       json.RawMessage
	CharacterID int64
}

func (q *Queries) UpdateCharacterState(ctx context.Context, arg UpdateCharacterStateParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterState, arg.State, arg.CharacterID)
	return err
}
