// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgensqlite

import (
	"context"
	"encoding/json"
	"time"
)

const blackPurgatoryEntryCounts = `-- name: BlackPurgatoryEntryCounts :one
SELECT count(CASE WHEN created_at >= CAST(?1 AS TIMESTAMP) THEN 1 END) AS daily,
count(*) AS weekly FROM character_events
WHERE character_id=?2 AND model='black-purgatory-entry-v1'
AND created_at >= CAST(?3 AS TIMESTAMP) AND json_extract(outcome,'$.stage') IN ('entered','cleared')
`

type BlackPurgatoryEntryCountsParams struct {
	DayStart    time.Time
	CharacterID int64
	WeekStart   time.Time
}

type BlackPurgatoryEntryCountsRow struct {
	Daily  int64
	Weekly int64
}

// DEVIATION, reported: the only place where FILTER (WHERE ...) could not be kept.
// sqlc v1.31.1's sqlite engine does not register a parameter that appears inside a
// FILTER clause: it pastes the literal text sqlc.arg(day_start) into the generated
// SQL instead of a placeholder, which cannot run. count(*) FILTER (WHERE c) is
// therefore written as the equivalent conditional aggregate
// count(CASE WHEN c THEN 1 END). FILTER is kept wherever its condition carries no
// parameter (MailboxDeliveryState unread, core.sql CharacterAllocation).
func (q *Queries) BlackPurgatoryEntryCounts(ctx context.Context, arg BlackPurgatoryEntryCountsParams) (BlackPurgatoryEntryCountsRow, error) {
	row := q.db.QueryRowContext(ctx, blackPurgatoryEntryCounts, arg.DayStart, arg.CharacterID, arg.WeekStart)
	var i BlackPurgatoryEntryCountsRow
	err := row.Scan(&i.Daily, &i.Weekly)
	return i, err
}

const blackPurgatoryEntryStage = `-- name: BlackPurgatoryEntryStage :one
SELECT CAST(json_extract(outcome,'$.stage') AS TEXT) AS stage FROM character_events
WHERE character_id=?1 AND event_key=?2 AND model='black-purgatory-entry-v1'
`

type BlackPurgatoryEntryStageParams struct {
	CharacterID int64
	EventKey    string
}

func (q *Queries) BlackPurgatoryEntryStage(ctx context.Context, arg BlackPurgatoryEntryStageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, blackPurgatoryEntryStage, arg.CharacterID, arg.EventKey)
	var stage string
	err := row.Scan(&stage)
	return stage, err
}

const characterEventStage = `-- name: CharacterEventStage :one
SELECT model,CAST(json_extract(outcome,'$.stage') AS TEXT) AS stage FROM character_events
WHERE character_id=?1 AND event_key=?2
`

type CharacterEventStageParams struct {
	CharacterID int64
	EventKey    string
}

type CharacterEventStageRow struct {
	Model string
	Stage string
}

func (q *Queries) CharacterEventStage(ctx context.Context, arg CharacterEventStageParams) (CharacterEventStageRow, error) {
	row := q.db.QueryRowContext(ctx, characterEventStage, arg.CharacterID, arg.EventKey)
	var i CharacterEventStageRow
	err := row.Scan(&i.Model, &i.Stage)
	return i, err
}

const normalizeCharacterIdentity = `-- name: NormalizeCharacterIdentity :execrows
UPDATE characters SET config_version=?1 WHERE config_version IS NOT ?1
`

func (q *Queries) NormalizeCharacterIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeCharacterIdentity, identity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const normalizeEventIdentity = `-- name: NormalizeEventIdentity :execrows
UPDATE character_events SET config_version=?1 WHERE config_version IS NOT ?1
`

func (q *Queries) NormalizeEventIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeEventIdentity, identity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const normalizeMapClearIdentity = `-- name: NormalizeMapClearIdentity :execrows
UPDATE character_map_clears SET source_version=?1 WHERE source_version IS NOT ?1
`

func (q *Queries) NormalizeMapClearIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeMapClearIdentity, identity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const normalizeQuestIdentity = `-- name: NormalizeQuestIdentity :execrows
UPDATE character_quests SET config_version=?1 WHERE config_version IS NOT ?1
`

func (q *Queries) NormalizeQuestIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeQuestIdentity, identity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const normalizeQuestRewardIdentity = `-- name: NormalizeQuestRewardIdentity :execrows
UPDATE character_quest_rewards SET source_version=?1 WHERE source_version IS NOT ?1
`

func (q *Queries) NormalizeQuestRewardIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeQuestRewardIdentity, identity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const normalizeWorldIdentity = `-- name: NormalizeWorldIdentity :execrows
UPDATE character_world SET config_version=?1 WHERE config_version IS NOT ?1
`

func (q *Queries) NormalizeWorldIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeWorldIdentity, identity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pendingBlackPurgatoryRewards = `-- name: PendingBlackPurgatoryRewards :many
SELECT e.outcome FROM character_events e JOIN characters c ON c.id=e.character_id
WHERE c.account_id=?1 AND c.id=?2 AND e.model=?3
AND e.event_key LIKE 'cardplan:%'
AND NOT EXISTS(SELECT 1 FROM character_events g WHERE g.character_id=e.character_id
AND g.event_key='black-purgatory-recovered:'||substr(e.event_key,10)) ORDER BY e.created_at LIMIT 16
`

type PendingBlackPurgatoryRewardsParams struct {
	AccountID   int64
	CharacterID int64
	Model       string
}

func (q *Queries) PendingBlackPurgatoryRewards(ctx context.Context, arg PendingBlackPurgatoryRewardsParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, pendingBlackPurgatoryRewards, arg.AccountID, arg.CharacterID, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []json.RawMessage
	for rows.Next() {
		var outcome json.RawMessage
		if err := rows.Scan(&outcome); err != nil {
			return nil, err
		}
		items = append(items, outcome)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundPendingBlackPurgatoryEntries = `-- name: RefundPendingBlackPurgatoryEntries :exec
UPDATE character_events SET outcome=CAST(json_set(outcome,'$.stage',json_quote('refunded')) AS BLOB)
WHERE character_id=?1 AND model='black-purgatory-entry-v1' AND json_extract(outcome,'$.stage')='entered'
`

func (q *Queries) RefundPendingBlackPurgatoryEntries(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, refundPendingBlackPurgatoryEntries, characterID)
	return err
}

const setCharacterEventStage = `-- name: SetCharacterEventStage :exec
UPDATE character_events SET outcome=CAST(json_set(outcome,'$.stage',json_quote(CAST(?1 AS TEXT))) AS BLOB)
WHERE character_id=?2 AND event_key=?3
`

type SetCharacterEventStageParams struct {
	Stage       string
	CharacterID int64
	EventKey    string
}

func (q *Queries) SetCharacterEventStage(ctx context.Context, arg SetCharacterEventStageParams) error {
	_, err := q.db.ExecContext(ctx, setCharacterEventStage, arg.Stage, arg.CharacterID, arg.EventKey)
	return err
}

const storedCharacterEvent = `-- name: StoredCharacterEvent :one

SELECT model,outcome FROM character_events
WHERE character_id=?1 AND event_key=?2
`

type StoredCharacterEventParams struct {
	CharacterID int64
	EventKey    string
}

type StoredCharacterEventRow struct {
	Model   string
	Outcome json.RawMessage
}

// SQLite query fork of sql/postgres/queries/events.sql (dual-engine, S3).
//
// The PostgreSQL file stays untouched and remains authoritative for the PG path.
//
// Dialect rules applied (docs/sqlite-query-port-guide.md, D22-D29):
//   - outcome->>'stage' -> json_extract(outcome,'$.stage'), wrapped in an explicit
//     CAST so the projected column is a Go string instead of interface{} (R-1).
//   - jsonb_set(outcome,'{stage}',to_jsonb(<text>)) becomes
//     json_set(outcome,'$.stage',json_quote(CAST(... AS TEXT))). json_quote is the
//     JSON1 equivalent of to_jsonb() for a scalar string: it emits a JSON string
//     and, unlike a bare text value, carries the JSON subtype that json_set
//     honours. Measured on the pinned driver (SQLite 3.53.4): a plain text value
//     is stored as the literal text (quotes included), while json_quote() gives
//     the intended JSON string. The same reason applies to the 'refunded' literal
//     below, where a bare '"refunded"' would be stored with its quotes.
//   - A json_set/json_patch RESULT is CAST back to BLOB. JSON1 returns TEXT, and a
//     TEXT value living in a BLOB json column is read back by database/sql as a Go
//     string, which cannot be scanned into json.RawMessage (D24; re-measured on the
//     pinned driver: "unsupported Scan, storing driver.Value type string into type
//     *json.RawMessage"). CAST(... AS BLOB) keeps the storage class the plain
//     parameter path already uses.
//   - created_at holds integer microseconds, so a timestamptz parameter is
//     CAST(sqlc.arg(x) AS TIMESTAMP) and binds through the driver's unix_micro
//     format (_inttotime=1 + _time_integer_format=unix_micro).
//   - Parameters bound to a column or a plain column projection are left bare: they
//     inherit the column's width and JSON type from the schema (character_id is
//     BIGINT -> int64, outcome is a json column -> json.RawMessage). CAST is added
//     only where sqlc would otherwise infer interface{}.
//   - IS DISTINCT FROM -> IS NOT. SQLite's IS / IS NOT are the null-safe
//     comparisons (they never yield NULL), so IS NOT is exactly IS DISTINCT FROM
//     here; both columns are NOT NULL. The rewrite is required because sqlc
//     v1.31.1's sqlite grammar rejects IS [NOT] DISTINCT FROM outright ("extraneous
//     input 'FROM'"), even though the pinned runtime driver accepts it.
//   - FILTER (WHERE ...) is kept where its condition has no parameter; see the
//     note on BlackPurgatoryEntryCounts below.
//   - This file has no FOR UPDATE / FOR NO KEY UPDATE / FOR SHARE clause.
func (q *Queries) StoredCharacterEvent(ctx context.Context, arg StoredCharacterEventParams) (StoredCharacterEventRow, error) {
	row := q.db.QueryRowContext(ctx, storedCharacterEvent, arg.CharacterID, arg.EventKey)
	var i StoredCharacterEventRow
	err := row.Scan(&i.Model, &i.Outcome)
	return i, err
}
