// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixtures.sql

package sqlcgensqlite

import (
	"context"
	"encoding/json"
)

const fixtureAccountCurrency = `-- name: FixtureAccountCurrency :exec

INSERT INTO account_currency(account_id,cera) VALUES(?1,?2)
ON CONFLICT(account_id) DO UPDATE SET cera=EXCLUDED.cera
`

type FixtureAccountCurrencyParams struct {
	AccountID int64
	Cera      int64
}

// SQLite query fork of sql/postgres/queries/fixtures.sql (dual-engine, S3).
//
// The PostgreSQL file stays untouched and remains authoritative for the PG path.
//
// What this file is: it is the query half of the isolated charactercheck fixture.
// The isolation itself is NOT expressed in this file - the PostgreSQL fixture
// creates a throwaway schema and sets search_path from Go
// (internal/database/fixture.go), and the SQLite fork isolates the same way with
// one temporary database file per test (design doc D18). Every statement below is
// ordinary DML against tables that exist in the SQLite schema, so porting it does
// not weaken the fixture's guarantee; the guarantee lives in the Go fixture.
//
// NOT PORTED: FixtureSchema (:one) ran SELECT current_schema()::text. That is a
// PostgreSQL catalog diagnostic with no SQLite equivalent (design doc D19 and
// section 3.4 list FixtureSchema as an engine-specific diagnostic); the SQLite
// fixture validates its container from Go instead (PRAGMA database_list / the
// temp file path). Omitted rather than guessed.
//
// Dialect rules applied:
//   - JSON parameters are never cast (D24): the columns are BLOB, so a plain
//     sqlc.arg keeps json.RawMessage in both directions. With the per-column json
//     overrides in sqlc.yaml this now holds for character_vaults.items as well.
//   - WHERE a JSON value is written with json_set/json_patch, the parameter is
//     wrapped in json(). Measured on the pinned driver: json_set/json_patch treat a
//     plain value as a literal, and a BLOB value is rejected outright ("JSON cannot
//     hold BLOB values"), so json() is what makes the parameter a JSON value (guide
//     section 1: "wrap in json(...) when a JSON value is needed"). The wrapper is
//     CAST(... AS BLOB) inside json() to give sqlc a concrete []byte parameter:
//     CAST(... AS JSON) would look right to sqlc (json.RawMessage) but SQLite gives
//     JSON NUMERIC affinity and destroys the value (measured: [1,2] -> 0,
//     {"a":1} -> 0), so it must not be used.
//   - The json_set/json_patch RESULT is CAST back to BLOB because JSON1 returns
//     TEXT, and a TEXT value in the BLOB column reads back as a Go string that
//     database/sql cannot scan into json.RawMessage (D24).
//   - state||fields (jsonb concatenation) -> json_patch(state,json(...)). For the
//     objects used here both are a right-biased merge of members; note that
//     json_patch follows RFC 7386 and therefore merges nested objects recursively
//     and deletes members whose value is null, while PG || replaces a top-level
//     member wholesale. The fixture only merges top-level scalars.
//   - (x IS NOT NULL)::boolean -> CAST((x IS NOT NULL) AS BOOLEAN).
//   - request->>'source' -> json_extract(request,'$.source') with CAST(... AS TEXT).
//   - Parameters bound to a column and plain column projections are bare, so they
//     keep the schema widths and json types (used/used_max int32, quest_id int32,
//     character_id int64, quest progress bigint via CAST because the PostgreSQL
//     file casts it to bigint). A parameter compared ONLY with a literal infers
//     interface{} (measured), so the 0-sentinels in FixtureEventCount,
//     FixtureQuestCount and FixtureCashInventoryCount keep an explicit CAST(... AS
//     INTEGER), matching the PostgreSQL bigint width.
func (q *Queries) FixtureAccountCurrency(ctx context.Context, arg FixtureAccountCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, fixtureAccountCurrency, arg.AccountID, arg.Cera)
	return err
}

const fixtureArchivedCharacter = `-- name: FixtureArchivedCharacter :one
SELECT CAST((deleted_at IS NOT NULL) AS BOOLEAN) AS archived,state FROM characters WHERE id=?1
`

type FixtureArchivedCharacterRow struct {
	Archived bool
	State    json.RawMessage
}

func (q *Queries) FixtureArchivedCharacter(ctx context.Context, characterID int64) (FixtureArchivedCharacterRow, error) {
	row := q.db.QueryRowContext(ctx, fixtureArchivedCharacter, characterID)
	var i FixtureArchivedCharacterRow
	err := row.Scan(&i.Archived, &i.State)
	return i, err
}

const fixtureCashInventoryCount = `-- name: FixtureCashInventoryCount :one
SELECT count(*) FROM cash_inventory WHERE account_id=?1
AND (CAST(?2 AS INTEGER)=0
 OR (CAST(?2 AS INTEGER)=1 AND claimed_at IS NULL)
 OR (CAST(?2 AS INTEGER)=2 AND claimed_at IS NOT NULL))
AND (template=CAST(?3 AS INTEGER) OR CAST(?3 AS INTEGER)=0)
AND (amount=?4 OR ?4=0)
`

type FixtureCashInventoryCountParams struct {
	AccountID  int64
	ClaimState int64
	Template   int64
	Amount     int64
}

func (q *Queries) FixtureCashInventoryCount(ctx context.Context, arg FixtureCashInventoryCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureCashInventoryCount,
		arg.AccountID,
		arg.ClaimState,
		arg.Template,
		arg.Amount,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureCashOrderCount = `-- name: FixtureCashOrderCount :one
SELECT count(*) FROM cash_orders WHERE account_id=?1
`

func (q *Queries) FixtureCashOrderCount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureCashOrderCount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureCashOrderSource = `-- name: FixtureCashOrderSource :one
SELECT CAST(coalesce(json_extract(request,'$.source'),'') AS TEXT) FROM cash_orders
WHERE account_id=?1 AND order_key=?2
`

type FixtureCashOrderSourceParams struct {
	AccountID int64
	OrderKey  string
}

func (q *Queries) FixtureCashOrderSource(ctx context.Context, arg FixtureCashOrderSourceParams) (string, error) {
	row := q.db.QueryRowContext(ctx, fixtureCashOrderSource, arg.AccountID, arg.OrderKey)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const fixtureCharacterSnapshot = `-- name: FixtureCharacterSnapshot :exec
UPDATE characters SET state=?1,config_version=?2
WHERE id=?3
`

type FixtureCharacterSnapshotParams struct {
	State         json.RawMessage
	ConfigVersion string
	CharacterID   int64
}

func (q *Queries) FixtureCharacterSnapshot(ctx context.Context, arg FixtureCharacterSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, fixtureCharacterSnapshot, arg.State, arg.ConfigVersion, arg.CharacterID)
	return err
}

const fixtureCharacterState = `-- name: FixtureCharacterState :one
SELECT state FROM characters WHERE id=?1
`

func (q *Queries) FixtureCharacterState(ctx context.Context, characterID int64) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, fixtureCharacterState, characterID)
	var state json.RawMessage
	err := row.Scan(&state)
	return state, err
}

const fixtureCompletedQuest = `-- name: FixtureCompletedQuest :exec
INSERT INTO character_quests(character_id,quest_id,status,progress,config_version,progress_model)
VALUES(?1,?2,'completed',0,?3,?4)
`

type FixtureCompletedQuestParams struct {
	CharacterID   int64
	QuestID       int32
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) FixtureCompletedQuest(ctx context.Context, arg FixtureCompletedQuestParams) error {
	_, err := q.db.ExecContext(ctx, fixtureCompletedQuest,
		arg.CharacterID,
		arg.QuestID,
		arg.ConfigVersion,
		arg.ProgressModel,
	)
	return err
}

const fixtureDeleteBirth = `-- name: FixtureDeleteBirth :exec
DELETE FROM character_birth WHERE character_id=?1
`

func (q *Queries) FixtureDeleteBirth(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, fixtureDeleteBirth, characterID)
	return err
}

const fixtureEventCount = `-- name: FixtureEventCount :one
SELECT count(*) FROM character_events WHERE (CAST(?1 AS INTEGER)=0 OR character_id=CAST(?1 AS INTEGER))
`

// CAST is required: a parameter compared only with the literal 0 infers
// interface{} (measured), while the PostgreSQL file casts it to bigint.
func (q *Queries) FixtureEventCount(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureEventCount, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureFatigueRoomStats = `-- name: FixtureFatigueRoomStats :one
SELECT count(*) AS count,CAST(coalesce(sum(cost),0) AS INTEGER) AS cost
FROM character_fatigue_rooms WHERE character_id=?1
`

type FixtureFatigueRoomStatsRow struct {
	Count int64
	Cost  int64
}

func (q *Queries) FixtureFatigueRoomStats(ctx context.Context, characterID int64) (FixtureFatigueRoomStatsRow, error) {
	row := q.db.QueryRowContext(ctx, fixtureFatigueRoomStats, characterID)
	var i FixtureFatigueRoomStatsRow
	err := row.Scan(&i.Count, &i.Cost)
	return i, err
}

const fixtureFatigueUsage = `-- name: FixtureFatigueUsage :exec
UPDATE character_fatigue SET used=?1,used_max=?2
WHERE character_id=?3
`

type FixtureFatigueUsageParams struct {
	Used        int32
	UsedMax     int32
	CharacterID int64
}

func (q *Queries) FixtureFatigueUsage(ctx context.Context, arg FixtureFatigueUsageParams) error {
	_, err := q.db.ExecContext(ctx, fixtureFatigueUsage, arg.Used, arg.UsedMax, arg.CharacterID)
	return err
}

const fixtureFatigueUsed = `-- name: FixtureFatigueUsed :exec
UPDATE character_fatigue SET used=?1 WHERE character_id=?2
`

type FixtureFatigueUsedParams struct {
	Used        int32
	CharacterID int64
}

func (q *Queries) FixtureFatigueUsed(ctx context.Context, arg FixtureFatigueUsedParams) error {
	_, err := q.db.ExecContext(ctx, fixtureFatigueUsed, arg.Used, arg.CharacterID)
	return err
}

const fixtureInventoryItems = `-- name: FixtureInventoryItems :exec
UPDATE characters SET state=CAST(json_set(state,'$.inventory.items',json(CAST(?1 AS BLOB))) AS BLOB)
WHERE id=?2
`

type FixtureInventoryItemsParams struct {
	Items       []byte
	CharacterID int64
}

func (q *Queries) FixtureInventoryItems(ctx context.Context, arg FixtureInventoryItemsParams) error {
	_, err := q.db.ExecContext(ctx, fixtureInventoryItems, arg.Items, arg.CharacterID)
	return err
}

const fixtureLegacyQuest = `-- name: FixtureLegacyQuest :exec
UPDATE character_quests SET progress=0,progress_model='legacy-zero'
WHERE character_id=?1 AND quest_id=?2
`

type FixtureLegacyQuestParams struct {
	CharacterID int64
	QuestID     int32
}

func (q *Queries) FixtureLegacyQuest(ctx context.Context, arg FixtureLegacyQuestParams) error {
	_, err := q.db.ExecContext(ctx, fixtureLegacyQuest, arg.CharacterID, arg.QuestID)
	return err
}

const fixtureMapClearCount = `-- name: FixtureMapClearCount :one
SELECT count(*) FROM character_map_clears WHERE character_id=?1 AND run_id=?2
`

type FixtureMapClearCountParams struct {
	CharacterID int64
	RunID       string
}

func (q *Queries) FixtureMapClearCount(ctx context.Context, arg FixtureMapClearCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureMapClearCount, arg.CharacterID, arg.RunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureMergeCharacterFields = `-- name: FixtureMergeCharacterFields :exec
UPDATE characters SET state=CAST(json_patch(state,json(CAST(?1 AS BLOB))) AS BLOB) WHERE id=?2
`

type FixtureMergeCharacterFieldsParams struct {
	Fields      []byte
	CharacterID int64
}

func (q *Queries) FixtureMergeCharacterFields(ctx context.Context, arg FixtureMergeCharacterFieldsParams) error {
	_, err := q.db.ExecContext(ctx, fixtureMergeCharacterFields, arg.Fields, arg.CharacterID)
	return err
}

const fixtureMonsterEventCount = `-- name: FixtureMonsterEventCount :one
SELECT count(*) FROM character_events
WHERE character_id=?1 AND event_key LIKE 'monster:%'
`

func (q *Queries) FixtureMonsterEventCount(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureMonsterEventCount, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureQuestCount = `-- name: FixtureQuestCount :one
SELECT count(*) FROM character_quests
WHERE (CAST(?1 AS INTEGER)=0 OR character_id=CAST(?1 AS INTEGER))
`

func (q *Queries) FixtureQuestCount(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureQuestCount, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureQuestProgress = `-- name: FixtureQuestProgress :exec
UPDATE character_quests SET progress=CAST(?1 AS INTEGER)
WHERE character_id=?2 AND quest_id=?3
`

type FixtureQuestProgressParams struct {
	Progress    int64
	CharacterID int64
	QuestID     int32
}

func (q *Queries) FixtureQuestProgress(ctx context.Context, arg FixtureQuestProgressParams) error {
	_, err := q.db.ExecContext(ctx, fixtureQuestProgress, arg.Progress, arg.CharacterID, arg.QuestID)
	return err
}

const fixtureQuestRecord = `-- name: FixtureQuestRecord :one
SELECT status,progress_model FROM character_quests
WHERE character_id=?1 AND quest_id=?2
`

type FixtureQuestRecordParams struct {
	CharacterID int64
	QuestID     int32
}

type FixtureQuestRecordRow struct {
	Status        string
	ProgressModel string
}

func (q *Queries) FixtureQuestRecord(ctx context.Context, arg FixtureQuestRecordParams) (FixtureQuestRecordRow, error) {
	row := q.db.QueryRowContext(ctx, fixtureQuestRecord, arg.CharacterID, arg.QuestID)
	var i FixtureQuestRecordRow
	err := row.Scan(&i.Status, &i.ProgressModel)
	return i, err
}

const fixtureQuestRecordSeed = `-- name: FixtureQuestRecordSeed :exec
INSERT INTO character_quests(character_id,quest_id,status,config_version,progress_model)
VALUES(?1,?2,?3,?4,?5)
`

type FixtureQuestRecordSeedParams struct {
	CharacterID   int64
	QuestID       int32
	Status        string
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) FixtureQuestRecordSeed(ctx context.Context, arg FixtureQuestRecordSeedParams) error {
	_, err := q.db.ExecContext(ctx, fixtureQuestRecordSeed,
		arg.CharacterID,
		arg.QuestID,
		arg.Status,
		arg.ConfigVersion,
		arg.ProgressModel,
	)
	return err
}

const fixtureQuestRepairCount = `-- name: FixtureQuestRepairCount :one
SELECT count(*) FROM character_quest_repairs WHERE character_id=?1
`

func (q *Queries) FixtureQuestRepairCount(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureQuestRepairCount, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureQuestRewardCount = `-- name: FixtureQuestRewardCount :one
SELECT count(*) FROM character_quest_rewards WHERE character_id=?1
AND (quest_id=?2 OR ?2=0)
`

type FixtureQuestRewardCountParams struct {
	CharacterID int64
	QuestID     int32
}

func (q *Queries) FixtureQuestRewardCount(ctx context.Context, arg FixtureQuestRewardCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureQuestRewardCount, arg.CharacterID, arg.QuestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureReadCharacterSnapshot = `-- name: FixtureReadCharacterSnapshot :one
SELECT state,config_version FROM characters WHERE id=?1
`

type FixtureReadCharacterSnapshotRow struct {
	State         json.RawMessage
	ConfigVersion string
}

func (q *Queries) FixtureReadCharacterSnapshot(ctx context.Context, characterID int64) (FixtureReadCharacterSnapshotRow, error) {
	row := q.db.QueryRowContext(ctx, fixtureReadCharacterSnapshot, characterID)
	var i FixtureReadCharacterSnapshotRow
	err := row.Scan(&i.State, &i.ConfigVersion)
	return i, err
}

const fixtureVaultItems = `-- name: FixtureVaultItems :exec
UPDATE character_vaults SET items=?1 WHERE character_id=?2
`

type FixtureVaultItemsParams struct {
	Items       json.RawMessage
	CharacterID int64
}

func (q *Queries) FixtureVaultItems(ctx context.Context, arg FixtureVaultItemsParams) error {
	_, err := q.db.ExecContext(ctx, fixtureVaultItems, arg.Items, arg.CharacterID)
	return err
}

const fixtureWalletGold = `-- name: FixtureWalletGold :exec
UPDATE characters SET state=CAST(json_set(state,'$.inventory.gold',json(CAST(?1 AS BLOB))) AS BLOB)
WHERE id=?2
`

type FixtureWalletGoldParams struct {
	Gold        []byte
	CharacterID int64
}

func (q *Queries) FixtureWalletGold(ctx context.Context, arg FixtureWalletGoldParams) error {
	_, err := q.db.ExecContext(ctx, fixtureWalletGold, arg.Gold, arg.CharacterID)
	return err
}
