// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gm.sql

package sqlcgensqlite

import (
	"context"
	"time"
)

const listGMMail = `-- name: ListGMMail :many
SELECT id,to_account_id,to_character_id,template,amount,title,status,created_at
FROM gm_mail
WHERE (CAST(?1 AS INTEGER) <= 0 OR to_account_id=CAST(?1 AS INTEGER))
AND (CAST(?2 AS TEXT)='' OR status=CAST(?2 AS TEXT))
ORDER BY id DESC LIMIT 200
`

type ListGMMailParams struct {
	AccountID int64
	Status    string
}

type ListGMMailRow struct {
	ID            int64
	ToAccountID   int64
	ToCharacterID int64
	Template      int64
	Amount        int64
	Title         string
	Status        string
	CreatedAt     time.Time
}

// CAST is required on both sentinels: a parameter compared only with the literal
// 0 (or with ”) infers interface{} (measured).
func (q *Queries) ListGMMail(ctx context.Context, arg ListGMMailParams) ([]ListGMMailRow, error) {
	rows, err := q.db.QueryContext(ctx, listGMMail, arg.AccountID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGMMailRow
	for rows.Next() {
		var i ListGMMailRow
		if err := rows.Scan(
			&i.ID,
			&i.ToAccountID,
			&i.ToCharacterID,
			&i.Template,
			&i.Amount,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGMMail = `-- name: RevokeGMMail :one
UPDATE gm_mail SET status='revoked'
WHERE id=?1 AND status IN ('unread','read') RETURNING id
`

func (q *Queries) RevokeGMMail(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, revokeGMMail, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const sendGMMail = `-- name: SendGMMail :one

INSERT INTO gm_mail(to_account_id,to_character_id,template,amount,title,body)
VALUES(?1,?2,?3,?4,?5,?6) RETURNING id
`

type SendGMMailParams struct {
	AccountID   int64
	CharacterID int64
	Template    int64
	Amount      int64
	Title       string
	Body        string
}

// SQLite query fork of sql/postgres/queries/gm.sql (dual-engine, S3).
//
// The PostgreSQL file stays untouched and remains authoritative for the PG path.
//
// Dialect rules applied:
//   - Parameters bound to a column are left bare so they inherit the column width
//     (gm_mail.to_account_id BIGINT -> int64, to_character_id INTEGER -> int32,
//     template/amount BIGINT -> int64). CAST(... AS INTEGER) is deliberately not
//     added: it would always produce int64 and lose the schema widths.
//   - ListGMMail's two sentinels (account_id <= 0 and status = ”) carry an
//     explicit CAST: a parameter compared only with a literal infers interface{}
//     (measured), so CAST(... AS INTEGER) / CAST(... AS TEXT) reproduce the
//     PostgreSQL ::bigint / ::text widths.
//   - INSERT ... RETURNING and UPDATE ... RETURNING are supported (>= 3.35).
//   - No locking clause in this file.
func (q *Queries) SendGMMail(ctx context.Context, arg SendGMMailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sendGMMail,
		arg.AccountID,
		arg.CharacterID,
		arg.Template,
		arg.Amount,
		arg.Title,
		arg.Body,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
