// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail.sql

package sqlcgensqlite

import (
	"context"
	"encoding/json"
	"time"
)

const insertPlayerMail = `-- name: InsertPlayerMail :one
INSERT INTO character_mail(sender_id,recipient_id,sender_name,body,assets,expires_at)
VALUES(?1,?2,?3,?4,?5,
(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER) + 1296000000000)) RETURNING id
`

type InsertPlayerMailParams struct {
	SenderID    *int64
	RecipientID int64
	SenderName  string
	Body        string
	Assets      json.RawMessage
}

func (q *Queries) InsertPlayerMail(ctx context.Context, arg InsertPlayerMailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPlayerMail,
		arg.SenderID,
		arg.RecipientID,
		arg.SenderName,
		arg.Body,
		arg.Assets,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSystemMail = `-- name: InsertSystemMail :one
INSERT INTO character_mail(recipient_id,sender_name,body,assets,expires_at)
VALUES(?1,?2,?3,?4,
(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER) + 1296000000000)) RETURNING id
`

type InsertSystemMailParams struct {
	RecipientID int64
	SenderName  string
	Body        string
	Assets      json.RawMessage
}

func (q *Queries) InsertSystemMail(ctx context.Context, arg InsertSystemMailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSystemMail,
		arg.RecipientID,
		arg.SenderName,
		arg.Body,
		arg.Assets,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockMailCharacters = `-- name: LockMailCharacters :many
SELECT id,account_id,wire_id,name,profession,create_request,config_version,state,created_at,
0 AS fixed_slot FROM characters WHERE id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
AND deleted_at IS NULL ORDER BY id
`

type LockMailCharactersRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	CreatedAt     time.Time
	FixedSlot     int64
}

// Lock query; FOR UPDATE removed, engine-wide write serialization instead.
func (q *Queries) LockMailCharacters(ctx context.Context, characterIds string) ([]LockMailCharactersRow, error) {
	rows, err := q.db.QueryContext(ctx, lockMailCharacters, characterIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockMailCharactersRow
	for rows.Next() {
		var i LockMailCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.WireID,
			&i.Name,
			&i.Profession,
			&i.CreateRequest,
			&i.ConfigVersion,
			&i.State,
			&i.CreatedAt,
			&i.FixedSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMailbox = `-- name: LockMailbox :many
SELECT m.id,coalesce(m.sender_id,0) AS sender_id,m.recipient_id,m.sender_name,
m.body,m.status,m.assets,m.expires_at,CAST((m.deleted_at IS NOT NULL) AS BOOLEAN) AS deleted
FROM character_mail m WHERE recipient_id=?1
AND (CAST(?2 AS BOOLEAN) OR (deleted_at IS NULL AND (expires_at>(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)) OR status=3)))
AND (CAST(?3 AS TEXT) IS NULL OR id IN (SELECT value FROM json_each(CAST(?3 AS TEXT)))) ORDER BY id
`

type LockMailboxParams struct {
	RecipientID    int64
	IncludeDeleted bool
	MessageIds     *string
}

type LockMailboxRow struct {
	ID          int64
	SenderID    int64
	RecipientID int64
	SenderName  string
	Body        string
	Status      int16
	Assets      json.RawMessage
	ExpiresAt   time.Time
	Deleted     bool
}

// Lock query; FOR UPDATE removed, engine-wide write serialization instead.
func (q *Queries) LockMailbox(ctx context.Context, arg LockMailboxParams) ([]LockMailboxRow, error) {
	rows, err := q.db.QueryContext(ctx, lockMailbox, arg.RecipientID, arg.IncludeDeleted, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockMailboxRow
	for rows.Next() {
		var i LockMailboxRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.SenderName,
			&i.Body,
			&i.Status,
			&i.Assets,
			&i.ExpiresAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailRecipient = `-- name: MailRecipient :one

SELECT id,account_id,wire_id,name,profession,create_request,config_version,state,created_at,
0 AS fixed_slot FROM characters WHERE lower(name)=lower(CAST(?1 AS TEXT)) AND deleted_at IS NULL
`

type MailRecipientRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	CreatedAt     time.Time
	FixedSlot     int64
}

// SQLite query fork of sql/postgres/queries/mail.sql (dual-engine, S3).
//
// The PostgreSQL file stays untouched and remains authoritative for the PG path.
//
// Dialect rules applied (docs/sqlite-query-port-guide.md, D22-D29):
//   - FOR UPDATE is deleted from LockMailCharacters / LockMailbox; SQLite has no
//     row locks and the engine serializes writers with BEGIN IMMEDIATE
//     (_txlock=immediate). Names and predicates are unchanged.
//   - id=ANY(sqlc.arg(ids)::bigint[]) -> id IN (SELECT value FROM
//     json_each(CAST(sqlc.arg(ids) AS TEXT))): the caller passes the id set as a
//     JSON array text (guide section 1, D9). The same mapping is used for the
//     optional sqlc.narg(message_ids) set; CAST is required there so the
//     parameter is a string instead of interface{}.
//   - now() -> (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)),
//     integer microseconds, matching the DDL defaults and the driver's
//     _inttotime=1 + _time_integer_format=unix_micro representation. Every
//     expires_at comparison therefore compares integers.
//   - (x IS NOT NULL)::boolean -> CAST((x IS NOT NULL) AS BOOLEAN) so the
//     projected column stays a Go bool.
//   - jsonb_array_elements(m.assets) -> json_each(m.assets) (JSON1 accepts the
//     BLOB storage class); the element payload is read with
//     json_extract(a.value,'$.claimed'), and NOT coalesce(<that>,0) reproduces
//     "NOT coalesce((a->>'claimed')::boolean,false)" for the JSON booleans the
//     server writes.
//   - Projections and parameters bound to a column are bare, so they keep the
//     schema widths (m.status SMALLINT -> int16, m.assets json -> json.RawMessage,
//     coalesce(m.sender_id,0) -> int64 from sender_id BIGINT). CAST is used only
//     where sqlc would infer interface{}: coalesce(max(m.id),0) and
//     coalesce(sum(...),0) (both bigint in PostgreSQL).
//
// NOT PORTED: NextMailID (:one) ran nextval('mailbox_id_seq')::bigint. The target
// schema has no sequence: character_mail.id is INTEGER PRIMARY KEY AUTOINCREMENT
// (sqlite/migrations/0001_initial.sql, section 0036_mailbox; the PostgreSQL
// sequence is gone). AUTOINCREMENT allocates the id at INSERT time, so there is no
// portable statement that pre-allocates it, and a max(id)+1 stand-in would change
// the "attachment ids are allocated before the message id and share one number
// space" invariant (design doc D3 / section 6.2). Omitted rather than guessed.
//
// DEVIATION, reported: InsertPlayerMail / InsertSystemMail compute
// now()+interval '15 days'. SQLite has no interval type and datetime('now','+15
// days') would produce TEXT, which cannot live in an integer-microsecond TIMESTAMP
// column. The interval is therefore expressed as exact integer-microsecond
// arithmetic (15 days = 1296000000000 us) on top of the same now() expression the
// rest of the tree uses. If the port wants the expiry computed in Go instead, the
// term is the only thing to change.
func (q *Queries) MailRecipient(ctx context.Context, name string) (MailRecipientRow, error) {
	row := q.db.QueryRowContext(ctx, mailRecipient, name)
	var i MailRecipientRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.WireID,
		&i.Name,
		&i.Profession,
		&i.CreateRequest,
		&i.ConfigVersion,
		&i.State,
		&i.CreatedAt,
		&i.FixedSlot,
	)
	return i, err
}

const mailRecipientID = `-- name: MailRecipientID :one
SELECT id FROM characters WHERE lower(name)=lower(CAST(?1 AS TEXT)) AND deleted_at IS NULL
`

func (q *Queries) MailRecipientID(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, mailRecipientID, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const mailSendReceipt = `-- name: MailSendReceipt :one
SELECT outcome FROM character_events WHERE character_id=?1
AND event_key=?2 AND model='mail-send-v1'
`

type MailSendReceiptParams struct {
	CharacterID int64
	EventKey    string
}

func (q *Queries) MailSendReceipt(ctx context.Context, arg MailSendReceiptParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, mailSendReceipt, arg.CharacterID, arg.EventKey)
	var outcome json.RawMessage
	err := row.Scan(&outcome)
	return outcome, err
}

const mailbox = `-- name: Mailbox :many
SELECT m.id,coalesce(m.sender_id,0) AS sender_id,m.recipient_id,m.sender_name,
m.body,m.status,m.assets,m.expires_at,CAST((m.deleted_at IS NOT NULL) AS BOOLEAN) AS deleted
FROM character_mail m JOIN characters c ON c.id=m.recipient_id
WHERE c.account_id=?1 AND c.id=?2 AND c.deleted_at IS NULL
AND m.deleted_at IS NULL AND (m.expires_at>(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)) OR m.status=3) ORDER BY m.id
`

type MailboxParams struct {
	AccountID   int64
	CharacterID int64
}

type MailboxRow struct {
	ID          int64
	SenderID    int64
	RecipientID int64
	SenderName  string
	Body        string
	Status      int16
	Assets      json.RawMessage
	ExpiresAt   time.Time
	Deleted     bool
}

func (q *Queries) Mailbox(ctx context.Context, arg MailboxParams) ([]MailboxRow, error) {
	rows, err := q.db.QueryContext(ctx, mailbox, arg.AccountID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailboxRow
	for rows.Next() {
		var i MailboxRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.SenderName,
			&i.Body,
			&i.Status,
			&i.Assets,
			&i.ExpiresAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailboxCapacity = `-- name: MailboxCapacity :one
SELECT count(*) AS messages,
CAST(coalesce(sum((SELECT count(*) FROM json_each(m.assets) a
WHERE NOT coalesce(json_extract(a.value,'$.claimed'),0))),0) AS INTEGER) AS unclaimed_assets
FROM character_mail m WHERE recipient_id=?1 AND deleted_at IS NULL
AND (expires_at>(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)) OR status=3)
`

type MailboxCapacityRow struct {
	Messages        int64
	UnclaimedAssets int64
}

func (q *Queries) MailboxCapacity(ctx context.Context, recipientID int64) (MailboxCapacityRow, error) {
	row := q.db.QueryRowContext(ctx, mailboxCapacity, recipientID)
	var i MailboxCapacityRow
	err := row.Scan(&i.Messages, &i.UnclaimedAssets)
	return i, err
}

const mailboxDeliveryState = `-- name: MailboxDeliveryState :one
SELECT CAST(coalesce(max(m.id),0) AS INTEGER) AS latest_id,
count(*) FILTER (WHERE m.status=1) AS unread
FROM character_mail m JOIN characters c ON c.id=m.recipient_id
WHERE c.account_id=?1 AND c.id=?2 AND c.deleted_at IS NULL
AND m.deleted_at IS NULL AND m.expires_at>(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type MailboxDeliveryStateParams struct {
	AccountID   int64
	CharacterID int64
}

type MailboxDeliveryStateRow struct {
	LatestID int64
	Unread   int64
}

func (q *Queries) MailboxDeliveryState(ctx context.Context, arg MailboxDeliveryStateParams) (MailboxDeliveryStateRow, error) {
	row := q.db.QueryRowContext(ctx, mailboxDeliveryState, arg.AccountID, arg.CharacterID)
	var i MailboxDeliveryStateRow
	err := row.Scan(&i.LatestID, &i.Unread)
	return i, err
}

const updateMail = `-- name: UpdateMail :execrows
UPDATE character_mail SET assets=?1,status=?2,
deleted_at=CASE WHEN CAST(?3 AS BOOLEAN) THEN (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)) ELSE NULL END
WHERE id=?4 AND recipient_id=?5 AND deleted_at IS NULL
`

type UpdateMailParams struct {
	Assets      json.RawMessage
	Status      int16
	Deleted     bool
	MailID      int64
	RecipientID int64
}

func (q *Queries) UpdateMail(ctx context.Context, arg UpdateMailParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMail,
		arg.Assets,
		arg.Status,
		arg.Deleted,
		arg.MailID,
		arg.RecipientID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
