// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oath.sql

package sqlcgensqlite

import (
	"context"
)

const equippedOathSelection = `-- name: EquippedOathSelection :one

SELECT selected_option FROM character_oath_options WHERE character_id=?1 AND core_instance_key=?2
`

type EquippedOathSelectionParams struct {
	CharacterID     int64
	CoreInstanceKey string
}

// SQLite query fork of sql/postgres/queries/oath.sql (dual-engine, S3).
//
// The PostgreSQL file stays untouched and remains authoritative for the PG path.
//
// Dialect rules applied:
//   - FOR UPDATE is deleted from LockOathOptionRevision; SQLite has no row locks
//     and the engine serializes writers with BEGIN IMMEDIATE (_txlock=immediate).
//     Name and predicate are unchanged.
//   - selected_option is written through CAST(sqlc.arg(x) AS INTEGER) because the
//     PostgreSQL file casts that parameter to bigint (int64) in three statements,
//     while the column itself is INTEGER; a bare parameter in those INSERT ...
//     VALUES positions would inherit the column's int32 and diverge from the PG
//     signature. revision is a BIGINT column and is left bare (int64 either way).
//   - now() -> (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)),
//     integer microseconds, matching the DDL default and the driver's
//     _inttotime=1 + _time_integer_format=unix_micro representation.
//   - ON CONFLICT ... DO UPDATE ... EXCLUDED is supported as written; the
//     DO UPDATE clause carries no parameter, so nothing can be lost there.
func (q *Queries) EquippedOathSelection(ctx context.Context, arg EquippedOathSelectionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, equippedOathSelection, arg.CharacterID, arg.CoreInstanceKey)
	var selected_option int32
	err := row.Scan(&selected_option)
	return selected_option, err
}

const insertOathOption = `-- name: InsertOathOption :exec
INSERT INTO character_oath_options(character_id,core_instance_key,selected_option,revision,updated_at)
VALUES(?1,?2,CAST(?3 AS INTEGER),?4,(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)))
`

type InsertOathOptionParams struct {
	CharacterID     int64
	CoreInstanceKey string
	SelectedOption  int64
	Revision        int64
}

func (q *Queries) InsertOathOption(ctx context.Context, arg InsertOathOptionParams) error {
	_, err := q.db.ExecContext(ctx, insertOathOption,
		arg.CharacterID,
		arg.CoreInstanceKey,
		arg.SelectedOption,
		arg.Revision,
	)
	return err
}

const lockOathOptionRevision = `-- name: LockOathOptionRevision :one
SELECT revision FROM character_oath_options WHERE character_id=?1 AND core_instance_key=?2
`

type LockOathOptionRevisionParams struct {
	CharacterID     int64
	CoreInstanceKey string
}

// Lock query; FOR UPDATE removed, engine-wide write serialization instead.
func (q *Queries) LockOathOptionRevision(ctx context.Context, arg LockOathOptionRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockOathOptionRevision, arg.CharacterID, arg.CoreInstanceKey)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const oathOption = `-- name: OathOption :one
SELECT character_id,core_instance_key,selected_option,revision FROM character_oath_options
WHERE character_id=?1 AND core_instance_key=?2
`

type OathOptionParams struct {
	CharacterID     int64
	CoreInstanceKey string
}

type OathOptionRow struct {
	CharacterID     int64
	CoreInstanceKey string
	SelectedOption  int32
	Revision        int64
}

func (q *Queries) OathOption(ctx context.Context, arg OathOptionParams) (OathOptionRow, error) {
	row := q.db.QueryRowContext(ctx, oathOption, arg.CharacterID, arg.CoreInstanceKey)
	var i OathOptionRow
	err := row.Scan(
		&i.CharacterID,
		&i.CoreInstanceKey,
		&i.SelectedOption,
		&i.Revision,
	)
	return i, err
}

const selectEquippedOathOption = `-- name: SelectEquippedOathOption :exec
INSERT INTO character_oath_options(character_id,core_instance_key,selected_option,revision,updated_at)
VALUES(?1,?2,CAST(?3 AS INTEGER),1,(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)))
ON CONFLICT(character_id,core_instance_key) DO UPDATE SET selected_option=EXCLUDED.selected_option,
revision=character_oath_options.revision+1,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SelectEquippedOathOptionParams struct {
	CharacterID     int64
	CoreInstanceKey string
	SelectedOption  int64
}

func (q *Queries) SelectEquippedOathOption(ctx context.Context, arg SelectEquippedOathOptionParams) error {
	_, err := q.db.ExecContext(ctx, selectEquippedOathOption, arg.CharacterID, arg.CoreInstanceKey, arg.SelectedOption)
	return err
}

const updateOathOption = `-- name: UpdateOathOption :exec
UPDATE character_oath_options SET selected_option=CAST(?1 AS INTEGER),revision=?2,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
WHERE character_id=?3 AND core_instance_key=?4
`

type UpdateOathOptionParams struct {
	SelectedOption  int64
	Revision        int64
	CharacterID     int64
	CoreInstanceKey string
}

func (q *Queries) UpdateOathOption(ctx context.Context, arg UpdateOathOptionParams) error {
	_, err := q.db.ExecContext(ctx, updateOathOption,
		arg.SelectedOption,
		arg.Revision,
		arg.CharacterID,
		arg.CoreInstanceKey,
	)
	return err
}
