// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progression.sql

package sqlcgensqlite

import (
	"context"
	"encoding/json"
	"time"
)

const activeCharacterOwned = `-- name: ActiveCharacterOwned :one
SELECT EXISTS(SELECT 1 FROM characters WHERE account_id=?1
AND id=?2 AND deleted_at IS NULL)
`

type ActiveCharacterOwnedParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) ActiveCharacterOwned(ctx context.Context, arg ActiveCharacterOwnedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, activeCharacterOwned, arg.AccountID, arg.CharacterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const advanceBirth = `-- name: AdvanceBirth :execrows
UPDATE character_birth SET stage=?1,dungeon=?2,
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
WHERE EXISTS(SELECT 1 FROM characters c WHERE c.id=character_birth.character_id AND c.account_id=?3
AND c.deleted_at IS NULL)
AND character_id=?4 AND stage<?1
`

type AdvanceBirthParams struct {
	Stage       int16
	Dungeon     int64
	AccountID   int64
	CharacterID int64
}

func (q *Queries) AdvanceBirth(ctx context.Context, arg AdvanceBirthParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceBirth,
		arg.Stage,
		arg.Dungeon,
		arg.AccountID,
		arg.CharacterID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceTowerFloor = `-- name: AdvanceTowerFloor :one
UPDATE account_tower_progress SET highest_cleared=?1,last_run_id=?2
WHERE account_id=?3 AND tower_key=?4
AND highest_cleared=?1-1 AND entries_today>0
RETURNING highest_cleared,CAST(COALESCE(entry_day,'') AS TEXT) AS entry_day,entries_today,last_run_id
`

type AdvanceTowerFloorParams struct {
	Floor     int16
	RunID     string
	AccountID int64
	TowerKey  string
}

type AdvanceTowerFloorRow struct {
	HighestCleared int16
	Column2        string
	EntriesToday   int16
	LastRunID      string
}

// PostgreSQL wraps the returned date in COALESCE(entry_day::text,”), and that
// expression is returned unchanged here: the sqlc sqlite engine names an
// aliased RETURNING expression ColumnN (see the header), so this one result
// column is generated as Column2 instead of EntryDay.
func (q *Queries) AdvanceTowerFloor(ctx context.Context, arg AdvanceTowerFloorParams) (AdvanceTowerFloorRow, error) {
	row := q.db.QueryRowContext(ctx, advanceTowerFloor,
		arg.Floor,
		arg.RunID,
		arg.AccountID,
		arg.TowerKey,
	)
	var i AdvanceTowerFloorRow
	err := row.Scan(
		&i.HighestCleared,
		&i.Column2,
		&i.EntriesToday,
		&i.LastRunID,
	)
	return i, err
}

const advanceTowerGrief = `-- name: AdvanceTowerGrief :one
UPDATE account_tower_grief_progress SET highest_cleared=?1,
cleared_day=CAST(?2 AS TEXT),last_run_id=?3
WHERE account_id=?4 AND highest_cleared=?1-1
AND (cleared_day IS NULL OR cleared_day<>CAST(?2 AS TEXT))
RETURNING highest_cleared,CAST(cleared_day AS TEXT) AS cleared_day,last_run_id
`

type AdvanceTowerGriefParams struct {
	Floor     int16
	Day       string
	RunID     string
	AccountID int64
}

type AdvanceTowerGriefRow struct {
	HighestCleared int16
	ClearedDay     string
	LastRunID      string
}

// cleared_day is assigned in this same statement, so the returned
// CAST(cleared_day AS TEXT) is non-NULL and matches cleared_day::text.
func (q *Queries) AdvanceTowerGrief(ctx context.Context, arg AdvanceTowerGriefParams) (AdvanceTowerGriefRow, error) {
	row := q.db.QueryRowContext(ctx, advanceTowerGrief,
		arg.Floor,
		arg.Day,
		arg.RunID,
		arg.AccountID,
	)
	var i AdvanceTowerGriefRow
	err := row.Scan(&i.HighestCleared, &i.ClearedDay, &i.LastRunID)
	return i, err
}

const backfillBirth = `-- name: BackfillBirth :exec
INSERT INTO character_birth(character_id,stage)
SELECT id,?1 FROM characters WHERE true ON CONFLICT(character_id) DO NOTHING
`

// `WHERE true` is required by SQLite: an upsert clause attached to an
// INSERT ... SELECT needs the SELECT to have a WHERE clause, otherwise the
// statement fails at runtime with `near "DO": syntax error` (measured). The
// predicate is a tautology, so the inserted rows are unchanged.
func (q *Queries) BackfillBirth(ctx context.Context, stage int16) error {
	_, err := q.db.ExecContext(ctx, backfillBirth, stage)
	return err
}

const birthStage = `-- name: BirthStage :one
SELECT b.stage,b.dungeon FROM character_birth b JOIN characters c ON c.id=b.character_id
WHERE c.account_id=?1 AND c.id=?2 AND c.deleted_at IS NULL
`

type BirthStageParams struct {
	AccountID   int64
	CharacterID int64
}

type BirthStageRow struct {
	Stage   int16
	Dungeon int64
}

func (q *Queries) BirthStage(ctx context.Context, arg BirthStageParams) (BirthStageRow, error) {
	row := q.db.QueryRowContext(ctx, birthStage, arg.AccountID, arg.CharacterID)
	var i BirthStageRow
	err := row.Scan(&i.Stage, &i.Dungeon)
	return i, err
}

const ensureTowerGriefProgress = `-- name: EnsureTowerGriefProgress :exec
INSERT INTO account_tower_grief_progress(account_id,highest_cleared)
VALUES(?1,?2) ON CONFLICT(account_id) DO NOTHING
`

type EnsureTowerGriefProgressParams struct {
	AccountID      int64
	HighestCleared int16
}

func (q *Queries) EnsureTowerGriefProgress(ctx context.Context, arg EnsureTowerGriefProgressParams) error {
	_, err := q.db.ExecContext(ctx, ensureTowerGriefProgress, arg.AccountID, arg.HighestCleared)
	return err
}

const ensureTowerProgress = `-- name: EnsureTowerProgress :exec
INSERT INTO account_tower_progress(account_id,tower_key,highest_cleared)
VALUES(?1,?2,?3) ON CONFLICT(account_id,tower_key) DO NOTHING
`

type EnsureTowerProgressParams struct {
	AccountID      int64
	TowerKey       string
	HighestCleared int16
}

func (q *Queries) EnsureTowerProgress(ctx context.Context, arg EnsureTowerProgressParams) error {
	_, err := q.db.ExecContext(ctx, ensureTowerProgress, arg.AccountID, arg.TowerKey, arg.HighestCleared)
	return err
}

const ensureWorld = `-- name: EnsureWorld :exec

INSERT INTO character_world(character_id,position,config_version)
SELECT id,?1,?2 FROM characters
WHERE id=?3 AND account_id=?4 ON CONFLICT DO NOTHING
`

type EnsureWorldParams struct {
	Position      json.RawMessage
	ConfigVersion string
	CharacterID   int64
	AccountID     int64
}

// SQLite query fork of sql/postgres/queries/progression.sql (dual-engine, S3).
//
// Ported for the progression slice: world/channel position, birth, fatigue,
// fatigue recovery, omen state, oath progress, tower progress and the run
// ledgers. The PostgreSQL file stays untouched and remains authoritative for the
// PostgreSQL path; every `-- name:` marker below is byte-identical to it.
//
// Dialect rules applied (port guide sec.1, design doc sec.3.2):
//   - FOR UPDATE is removed (LockOathProgress). SQLite has no row locks; the
//     engine serializes writers with BEGIN IMMEDIATE. The query keeps its name
//     and its full ownership predicate, so callers are unchanged.
//   - `UPDATE ... FROM` is rewritten as a correlated EXISTS ownership guard (see
//     SaveWorld and AdvanceBirth); the sqlc sqlite grammar rejects the clause
//     outright (`no viable alternative at input 'UPDATE character_world w'`).
//     characters.id is the primary key, so the PostgreSQL join matched at most
//     one row and the rewrite updates exactly the same rows. Outer columns are
//     qualified with the table name; argument order is kept identical.
//   - Integer parameters are left bare so they inherit the column width from the
//     sqlite DDL, which mirrors the PostgreSQL widths (SMALLINT/INTEGER/BIGINT).
//     A CAST type name ignores those overrides and always yields int64, so CAST
//     is only used where an expression genuinely needs a type (R-1).
//   - now() -> (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)),
//     the integer-microsecond expression already used by core.sql.
//   - `(x ->> 'k')::bigint` -> CAST(json_extract(x,'$.k') AS INTEGER).
//   - jsonb_build_object -> json_object, GREATEST -> scalar max.
//   - `= ANY(sqlc.arg(towns)::bigint[])` -> `IN (SELECT ... FROM json_each(...))`
//     with the list passed as JSON text (D9).
//
// DATE columns: they are written and read as ISO-8601 'YYYY-MM-DD' TEXT here.
//   - `$n::text::date` -> CAST(sqlc.arg(d) AS TEXT). Callers already build the
//     string as time.Now().Format("2006-01-02") (internal/character/fatigue.go),
//     so the stored bytes are exactly what PostgreSQL stored for the same call.
//   - `col::text` (a date) -> CAST(col AS TEXT), and `GREATEST(a,b)` -> max(a,b).
//     Fixed-width ISO text orders lexicographically exactly like a date, so the
//     rollover comparisons in LoadFatigue and the `<>` test in AdvanceTowerGrief
//     keep PostgreSQL's chronological semantics. Verified against the pinned
//     driver (modernc.org/sqlite, SQLite 3.53.4): typeof() is 'text' and the
//     round-trip through LoadFatigue/ReserveTowerEntry/AdvanceTower* is exact.
//   - This is deliberately NOT the integer-microsecond DATE representation the
//     sqlite DDL header describes for the general case; design doc D14 allows
//     either ("TEXT/integer storage"). SQLite only reports a decltype for a bare
//     column reference, and the driver's _inttotime conversion needs that
//     decltype, so a bare DATE column scans as time.Time. The PostgreSQL queries
//     here return a date *string* (`day::text`), and the only way to produce a
//     string with the PostgreSQL field name is CAST(<column> AS TEXT) over TEXT
//     storage. Every DATE column in this file (character_fatigue.day,
//     character_fatigue_rooms.day, character_fatigue_recovery.day,
//     account_tower_progress.entry_day, account_tower_grief_progress.cleared_day)
//     is written and read only by the queries below, so it stays self-consistent.
//     npc_favor.last_gift_day belongs to adventure.sql and is not in this slice.
//
// sqlc v1.31.1 sqlite-engine traps verified against this schema and worked around
// below (each would otherwise generate code that fails only at runtime):
//   - A parameter inside `FILTER (WHERE ...)` is dropped: the clause is copied
//     through verbatim, the generated struct loses the parameter entirely, and
//     the literal text `sqlc.arg(day)` ships inside the SQL. `daily_uses` is
//     therefore spelled COALESCE(SUM(CASE WHEN day=<d> THEN 1 ELSE 0 END),0) --
//     the exact equivalent of count(*) FILTER (WHERE day=<d>), including 0 rather
//     than NULL when no row matches. (A FILTER with no parameter inside is fine;
//     that is why core.sql keeps one.)
//   - A parameter inside `ON CONFLICT ... DO UPDATE SET`/`WHERE` is likewise
//     copied through unbound. No query here has one: the DO UPDATE clauses only
//     reference EXCLUDED/character_* columns and now().
//   - An alias in `RETURNING <expr> AS <name>` is ignored for naming: only a
//     bare column or CAST(<column> ...) comes back under its PostgreSQL name.
//     AdvanceTowerFloor keeps PostgreSQL's defensive COALESCE(entry_day::text,”)
//     (value semantics preserved) and therefore exposes that one result column as
//     `Column2` instead of `EntryDay`; every other returned date expression is
//     either a plain CAST of a column or assigned in the same statement, so it
//     keeps its PostgreSQL name.
//
// Known divergences from the PostgreSQL side that no SQL rewrite can fix (each
// needs an out-of-file decision; reported to the caller):
//   - Integer widths where the two DDLs disagree. PostgreSQL declares
//     character_omen_state.dungeon_id, character_oath_progress.dungeon_id and
//     character_fatigue_recovery.template as bigint, while the sqlite DDL
//     currently declares them INTEGER, so bare parameters bound to those columns
//     infer int32 instead of int64 (measured with the current sqlc.yaml). The
//     five tower `floor` parameters are int16 here against PostgreSQL int32,
//     because PostgreSQL casts them to integer explicitly
//     (`$1::integer`) while the column they are compared with is smallint and a
//     CAST type name always yields int64 on the sqlite side. Both are integer
//     width differences only, which generated_parity_test.go's widthEquivalent
//     tolerates; the three columns align automatically once the sqlite DDL uses
//     bigint.
//   - FatigueRecoveryUsage.last_used is `int64` here (integer microseconds, 0 for
//     the empty case, which is exactly COALESCE(max(used_at),'epoch')) where
//     PostgreSQL returns time.Time. The driver converts an integer to time.Time
//     only when SQLite reports a DATE/DATETIME/TIMESTAMP decltype, and that is
//     only reported for a bare column reference -- an aggregate such as
//     max(used_at) has no decltype, so a time.Time scan target fails with
//     "unsupported Scan, storing driver.Value type int64 into type *time.Time"
//     (measured on modernc.org/sqlite v1.59.0 + SQLite 3.53.4). The adapter must
//     convert these microseconds to time.Time.
//   - ScrubPollutedWorldPositions takes its bigint[] as JSON text, so the
//     parameter is `string` here and `[]int64` in PostgreSQL (D9: the adapter
//     owns the encoding).
//   - AdvanceTowerFloorRow.EntryDay is generated as Column2 (see the RETURNING
//     trap above).
//   - json_object emits keys in the written order; PostgreSQL jsonb canonicalizes
//     key order, so the stored bytes of a fresh RecordIspinsWeeklyClear outcome
//     can differ in key order. The JSON value itself is identical.
//
// The INSERT ... SELECT carries a WHERE clause: SQLite requires one whenever an
// upsert clause follows a SELECT, so BackfillBirth adds `WHERE true` below. This
// query already has a real predicate.
func (q *Queries) EnsureWorld(ctx context.Context, arg EnsureWorldParams) error {
	_, err := q.db.ExecContext(ctx, ensureWorld,
		arg.Position,
		arg.ConfigVersion,
		arg.CharacterID,
		arg.AccountID,
	)
	return err
}

const enterChannelWorld = `-- name: EnterChannelWorld :exec
INSERT INTO character_channel_world(character_id,channel_type,position,config_version)
SELECT id,?1,?2,?3 FROM characters
WHERE id=?4 AND account_id=?5
ON CONFLICT (character_id,channel_type) DO UPDATE SET position=EXCLUDED.position,
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type EnterChannelWorldParams struct {
	ChannelType   int32
	Position      json.RawMessage
	ConfigVersion string
	CharacterID   int64
	AccountID     int64
}

func (q *Queries) EnterChannelWorld(ctx context.Context, arg EnterChannelWorldParams) error {
	_, err := q.db.ExecContext(ctx, enterChannelWorld,
		arg.ChannelType,
		arg.Position,
		arg.ConfigVersion,
		arg.CharacterID,
		arg.AccountID,
	)
	return err
}

const fatigueRecoveryUsage = `-- name: FatigueRecoveryUsage :one
SELECT CAST(COALESCE(SUM(CASE WHEN day=CAST(?1 AS TEXT) THEN 1 ELSE 0 END),0) AS INTEGER) AS daily_uses,
CAST(COALESCE(max(used_at),0) AS INTEGER) AS last_used,
CAST(count(*)>0 AS BOOLEAN) AS has_last_used FROM character_fatigue_recovery
WHERE character_id=?2 AND template=?3
`

type FatigueRecoveryUsageParams struct {
	Day         string
	CharacterID int64
	Template    int64
}

type FatigueRecoveryUsageRow struct {
	DailyUses   int64
	LastUsed    int64
	HasLastUsed bool
}

func (q *Queries) FatigueRecoveryUsage(ctx context.Context, arg FatigueRecoveryUsageParams) (FatigueRecoveryUsageRow, error) {
	row := q.db.QueryRowContext(ctx, fatigueRecoveryUsage, arg.Day, arg.CharacterID, arg.Template)
	var i FatigueRecoveryUsageRow
	err := row.Scan(&i.DailyUses, &i.LastUsed, &i.HasLastUsed)
	return i, err
}

const fatigueRoomRecorded = `-- name: FatigueRoomRecorded :one
SELECT EXISTS(SELECT 1 FROM character_fatigue_rooms WHERE character_id=?1
AND run_id=?2 AND map_id=?3)
`

type FatigueRoomRecordedParams struct {
	CharacterID int64
	RunID       string
	MapID       int64
}

func (q *Queries) FatigueRoomRecorded(ctx context.Context, arg FatigueRoomRecordedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, fatigueRoomRecorded, arg.CharacterID, arg.RunID, arg.MapID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ispinsWeeklyUsed = `-- name: IspinsWeeklyUsed :one
SELECT EXISTS(SELECT 1 FROM character_events e JOIN characters c ON c.id=e.character_id
WHERE c.id=?1 AND c.account_id=?2 AND c.deleted_at IS NULL
AND e.model=?3 AND json_extract(e.outcome,'$.week')=CAST(?4 AS TEXT))
`

type IspinsWeeklyUsedParams struct {
	CharacterID int64
	AccountID   int64
	Model       string
	Week        string
}

func (q *Queries) IspinsWeeklyUsed(ctx context.Context, arg IspinsWeeklyUsedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, ispinsWeeklyUsed,
		arg.CharacterID,
		arg.AccountID,
		arg.Model,
		arg.Week,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const loadFatigue = `-- name: LoadFatigue :one
INSERT INTO character_fatigue(character_id,day,daily_limit)
SELECT id,CAST(?1 AS TEXT),?2 FROM characters
WHERE account_id=?3 AND id=?4
ON CONFLICT(character_id) DO UPDATE SET
used=CASE WHEN EXCLUDED.day>character_fatigue.day THEN 0 ELSE character_fatigue.used END,
used_max=CASE WHEN EXCLUDED.day>character_fatigue.day THEN 0 ELSE character_fatigue.used_max END,
daily_limit=CASE WHEN EXCLUDED.day>=character_fatigue.day THEN EXCLUDED.daily_limit ELSE character_fatigue.daily_limit END,
day=CAST(max(EXCLUDED.day,character_fatigue.day) AS TEXT),
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
RETURNING CAST(day AS TEXT) AS day,used,daily_limit,used_max
`

type LoadFatigueParams struct {
	Day         string
	DailyLimit  int32
	AccountID   int64
	CharacterID int64
}

type LoadFatigueRow struct {
	Day        string
	Used       int32
	DailyLimit int32
	UsedMax    int32
}

func (q *Queries) LoadFatigue(ctx context.Context, arg LoadFatigueParams) (LoadFatigueRow, error) {
	row := q.db.QueryRowContext(ctx, loadFatigue,
		arg.Day,
		arg.DailyLimit,
		arg.AccountID,
		arg.CharacterID,
	)
	var i LoadFatigueRow
	err := row.Scan(
		&i.Day,
		&i.Used,
		&i.DailyLimit,
		&i.UsedMax,
	)
	return i, err
}

const loadLockedCharacterFatigue = `-- name: LoadLockedCharacterFatigue :one
INSERT INTO character_fatigue(character_id,day,daily_limit)
VALUES(?1,CAST(?2 AS TEXT),?3)
ON CONFLICT(character_id) DO UPDATE SET
used=CASE WHEN EXCLUDED.day>character_fatigue.day THEN 0 ELSE character_fatigue.used END,
used_max=CASE WHEN EXCLUDED.day>character_fatigue.day THEN 0 ELSE character_fatigue.used_max END,
daily_limit=CASE WHEN EXCLUDED.day>=character_fatigue.day THEN EXCLUDED.daily_limit ELSE character_fatigue.daily_limit END,
day=CAST(max(EXCLUDED.day,character_fatigue.day) AS TEXT),
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
RETURNING CAST(day AS TEXT) AS day,used,daily_limit,used_max
`

type LoadLockedCharacterFatigueParams struct {
	CharacterID int64
	Day         string
	DailyLimit  int32
}

type LoadLockedCharacterFatigueRow struct {
	Day        string
	Used       int32
	DailyLimit int32
	UsedMax    int32
}

func (q *Queries) LoadLockedCharacterFatigue(ctx context.Context, arg LoadLockedCharacterFatigueParams) (LoadLockedCharacterFatigueRow, error) {
	row := q.db.QueryRowContext(ctx, loadLockedCharacterFatigue, arg.CharacterID, arg.Day, arg.DailyLimit)
	var i LoadLockedCharacterFatigueRow
	err := row.Scan(
		&i.Day,
		&i.Used,
		&i.DailyLimit,
		&i.UsedMax,
	)
	return i, err
}

const loadWorld = `-- name: LoadWorld :one
SELECT w.position,w.revision,w.config_version FROM character_world w JOIN characters c ON c.id=w.character_id
WHERE c.account_id=?1 AND c.id=?2
`

type LoadWorldParams struct {
	AccountID   int64
	CharacterID int64
}

type LoadWorldRow struct {
	Position      json.RawMessage
	Revision      int64
	ConfigVersion string
}

func (q *Queries) LoadWorld(ctx context.Context, arg LoadWorldParams) (LoadWorldRow, error) {
	row := q.db.QueryRowContext(ctx, loadWorld, arg.AccountID, arg.CharacterID)
	var i LoadWorldRow
	err := row.Scan(&i.Position, &i.Revision, &i.ConfigVersion)
	return i, err
}

const lockOathProgress = `-- name: LockOathProgress :one
SELECT clears FROM character_oath_progress WHERE character_id=?1 AND dungeon_id=?2
`

type LockOathProgressParams struct {
	CharacterID int64
	DungeonID   int64
}

// Lock query; the FOR UPDATE clause is replaced by the engine-wide BEGIN
// IMMEDIATE write serialization (see the file header). Name and predicate are
// unchanged, so the caller sees the same API.
func (q *Queries) LockOathProgress(ctx context.Context, arg LockOathProgressParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, lockOathProgress, arg.CharacterID, arg.DungeonID)
	var clears int32
	err := row.Scan(&clears)
	return clears, err
}

const lockedIspinsWeeklyUsed = `-- name: LockedIspinsWeeklyUsed :one
SELECT EXISTS(SELECT 1 FROM character_events WHERE character_id=?1
AND model=?2 AND json_extract(outcome,'$.week')=CAST(?3 AS TEXT))
`

type LockedIspinsWeeklyUsedParams struct {
	CharacterID int64
	Model       string
	Week        string
}

func (q *Queries) LockedIspinsWeeklyUsed(ctx context.Context, arg LockedIspinsWeeklyUsedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, lockedIspinsWeeklyUsed, arg.CharacterID, arg.Model, arg.Week)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const oathProgressClears = `-- name: OathProgressClears :one
SELECT clears FROM character_oath_progress WHERE character_id=?1 AND dungeon_id=?2
`

type OathProgressClearsParams struct {
	CharacterID int64
	DungeonID   int64
}

func (q *Queries) OathProgressClears(ctx context.Context, arg OathProgressClearsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, oathProgressClears, arg.CharacterID, arg.DungeonID)
	var clears int32
	err := row.Scan(&clears)
	return clears, err
}

const odysseyGraduationAlreadyPaid = `-- name: OdysseyGraduationAlreadyPaid :one
SELECT EXISTS(SELECT 1 FROM character_events WHERE character_id=?1
AND event_key IN('odyssey-graduate-reward-v1','odyssey-honor-mail-v1'))
`

func (q *Queries) OdysseyGraduationAlreadyPaid(ctx context.Context, characterID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, odysseyGraduationAlreadyPaid, characterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const omenState = `-- name: OmenState :one
SELECT held,orthaire_pending,misses FROM character_omen_state WHERE character_id=?1 AND dungeon_id=?2
`

type OmenStateParams struct {
	CharacterID int64
	DungeonID   int64
}

type OmenStateRow struct {
	Held            int32
	OrthairePending bool
	Misses          int32
}

func (q *Queries) OmenState(ctx context.Context, arg OmenStateParams) (OmenStateRow, error) {
	row := q.db.QueryRowContext(ctx, omenState, arg.CharacterID, arg.DungeonID)
	var i OmenStateRow
	err := row.Scan(&i.Held, &i.OrthairePending, &i.Misses)
	return i, err
}

const readTowerGriefProgress = `-- name: ReadTowerGriefProgress :one
SELECT highest_cleared,CAST(COALESCE(cleared_day,'') AS TEXT) AS cleared_day,last_run_id
FROM account_tower_grief_progress WHERE account_id=?1
`

type ReadTowerGriefProgressRow struct {
	HighestCleared int16
	ClearedDay     string
	LastRunID      string
}

func (q *Queries) ReadTowerGriefProgress(ctx context.Context, accountID int64) (ReadTowerGriefProgressRow, error) {
	row := q.db.QueryRowContext(ctx, readTowerGriefProgress, accountID)
	var i ReadTowerGriefProgressRow
	err := row.Scan(&i.HighestCleared, &i.ClearedDay, &i.LastRunID)
	return i, err
}

const readTowerProgress = `-- name: ReadTowerProgress :one
SELECT highest_cleared,CAST(COALESCE(entry_day,'') AS TEXT) AS entry_day,entries_today,last_run_id
FROM account_tower_progress WHERE account_id=?1 AND tower_key=?2
`

type ReadTowerProgressParams struct {
	AccountID int64
	TowerKey  string
}

type ReadTowerProgressRow struct {
	HighestCleared int16
	EntryDay       string
	EntriesToday   int16
	LastRunID      string
}

func (q *Queries) ReadTowerProgress(ctx context.Context, arg ReadTowerProgressParams) (ReadTowerProgressRow, error) {
	row := q.db.QueryRowContext(ctx, readTowerProgress, arg.AccountID, arg.TowerKey)
	var i ReadTowerProgressRow
	err := row.Scan(
		&i.HighestCleared,
		&i.EntryDay,
		&i.EntriesToday,
		&i.LastRunID,
	)
	return i, err
}

const recordFatigueRecovery = `-- name: RecordFatigueRecovery :exec
INSERT INTO character_fatigue_recovery(character_id,template,day,ordinal,restored,used_at)
VALUES(?1,?2,CAST(?3 AS TEXT),
CAST(?4 AS INTEGER),?5,?6)
`

type RecordFatigueRecoveryParams struct {
	CharacterID int64
	Template    int64
	Day         string
	Ordinal     int64
	Restored    int32
	UsedAt      time.Time
}

// `ordinal` is PostgreSQL `::bigint`, so it keeps the int64 width via the CAST.
func (q *Queries) RecordFatigueRecovery(ctx context.Context, arg RecordFatigueRecoveryParams) error {
	_, err := q.db.ExecContext(ctx, recordFatigueRecovery,
		arg.CharacterID,
		arg.Template,
		arg.Day,
		arg.Ordinal,
		arg.Restored,
		arg.UsedAt,
	)
	return err
}

const recordFatigueRoom = `-- name: RecordFatigueRoom :exec
INSERT INTO character_fatigue_rooms(character_id,run_id,map_id,day,cost)
VALUES(?1,?2,?3,CAST(?4 AS TEXT),?5)
`

type RecordFatigueRoomParams struct {
	CharacterID int64
	RunID       string
	MapID       int64
	Day         string
	Cost        int32
}

func (q *Queries) RecordFatigueRoom(ctx context.Context, arg RecordFatigueRoomParams) error {
	_, err := q.db.ExecContext(ctx, recordFatigueRoom,
		arg.CharacterID,
		arg.RunID,
		arg.MapID,
		arg.Day,
		arg.Cost,
	)
	return err
}

const recordIspinsWeeklyClear = `-- name: RecordIspinsWeeklyClear :exec
INSERT INTO character_events(character_id,event_key,config_version,model,outcome)
VALUES(?1,?2,?3,?4,
CAST(json_object('week',CAST(?5 AS TEXT),'run',CAST(?6 AS TEXT)) AS BLOB))
`

type RecordIspinsWeeklyClearParams struct {
	CharacterID   int64
	EventKey      string
	ConfigVersion string
	Model         string
	Week          string
	Run           string
}

// json_object returns TEXT; character_events.outcome is a BLOB column with BLOB
// affinity, which stores TEXT unchanged, so the JSON is cast to BLOB to keep the
// byte round-trip database/sql needs for a json.RawMessage scan target (D24).
func (q *Queries) RecordIspinsWeeklyClear(ctx context.Context, arg RecordIspinsWeeklyClearParams) error {
	_, err := q.db.ExecContext(ctx, recordIspinsWeeklyClear,
		arg.CharacterID,
		arg.EventKey,
		arg.ConfigVersion,
		arg.Model,
		arg.Week,
		arg.Run,
	)
	return err
}

const reserveTowerEntry = `-- name: ReserveTowerEntry :one
UPDATE account_tower_progress SET entry_day=CAST(?1 AS TEXT),
entries_today=CASE WHEN entry_day=CAST(?1 AS TEXT) THEN entries_today+1 ELSE 1 END
WHERE account_id=?2 AND tower_key=?3 AND highest_cleared+1=?4
RETURNING highest_cleared,CAST(entry_day AS TEXT) AS entry_day,entries_today,last_run_id
`

type ReserveTowerEntryParams struct {
	Day       string
	AccountID int64
	TowerKey  string
	Floor     int16
}

type ReserveTowerEntryRow struct {
	HighestCleared int16
	EntryDay       string
	EntriesToday   int16
	LastRunID      string
}

// entry_day is assigned in this same statement, so the returned
// CAST(entry_day AS TEXT) is non-NULL and keeps the plain `string` shape
// PostgreSQL returns from entry_day::text.
func (q *Queries) ReserveTowerEntry(ctx context.Context, arg ReserveTowerEntryParams) (ReserveTowerEntryRow, error) {
	row := q.db.QueryRowContext(ctx, reserveTowerEntry,
		arg.Day,
		arg.AccountID,
		arg.TowerKey,
		arg.Floor,
	)
	var i ReserveTowerEntryRow
	err := row.Scan(
		&i.HighestCleared,
		&i.EntryDay,
		&i.EntriesToday,
		&i.LastRunID,
	)
	return i, err
}

const runFatigueLedger = `-- name: RunFatigueLedger :one
SELECT CAST(COALESCE(SUM(f.cost),0) AS INTEGER) AS charged,CAST(COUNT(*) AS INTEGER) AS rooms
FROM character_fatigue_rooms f JOIN characters c ON c.id=f.character_id
WHERE c.account_id=?1 AND c.id=?2 AND f.run_id=?3
`

type RunFatigueLedgerParams struct {
	AccountID   int64
	CharacterID int64
	RunID       string
}

type RunFatigueLedgerRow struct {
	Charged int64
	Rooms   int64
}

func (q *Queries) RunFatigueLedger(ctx context.Context, arg RunFatigueLedgerParams) (RunFatigueLedgerRow, error) {
	row := q.db.QueryRowContext(ctx, runFatigueLedger, arg.AccountID, arg.CharacterID, arg.RunID)
	var i RunFatigueLedgerRow
	err := row.Scan(&i.Charged, &i.Rooms)
	return i, err
}

const runMonsterExperience = `-- name: RunMonsterExperience :one
SELECT CAST(COALESCE(SUM(CAST(json_extract(e.outcome,'$.gain') AS INTEGER)),0) AS INTEGER) AS total
FROM character_events e JOIN characters c ON c.id=e.character_id
WHERE c.account_id=?1 AND c.id=?2 AND e.event_key LIKE ?3
`

type RunMonsterExperienceParams struct {
	AccountID    int64
	CharacterID  int64
	EventPattern string
}

func (q *Queries) RunMonsterExperience(ctx context.Context, arg RunMonsterExperienceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, runMonsterExperience, arg.AccountID, arg.CharacterID, arg.EventPattern)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const runPaidFatigue = `-- name: RunPaidFatigue :one
SELECT EXISTS(SELECT 1 FROM character_fatigue_rooms WHERE character_id=?1
AND run_id=?2 AND cost>0)
`

type RunPaidFatigueParams struct {
	CharacterID int64
	RunID       string
}

func (q *Queries) RunPaidFatigue(ctx context.Context, arg RunPaidFatigueParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, runPaidFatigue, arg.CharacterID, arg.RunID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const saveFatigueCharge = `-- name: SaveFatigueCharge :exec
UPDATE character_fatigue SET used=?1,used_max=?2,
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
WHERE character_id=?3
`

type SaveFatigueChargeParams struct {
	Used        int32
	UsedMax     int32
	CharacterID int64
}

func (q *Queries) SaveFatigueCharge(ctx context.Context, arg SaveFatigueChargeParams) error {
	_, err := q.db.ExecContext(ctx, saveFatigueCharge, arg.Used, arg.UsedMax, arg.CharacterID)
	return err
}

const saveFatigueRecovery = `-- name: SaveFatigueRecovery :exec
UPDATE character_fatigue SET used=?1,
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)) WHERE character_id=?2
`

type SaveFatigueRecoveryParams struct {
	Used        int32
	CharacterID int64
}

func (q *Queries) SaveFatigueRecovery(ctx context.Context, arg SaveFatigueRecoveryParams) error {
	_, err := q.db.ExecContext(ctx, saveFatigueRecovery, arg.Used, arg.CharacterID)
	return err
}

const saveOathProgress = `-- name: SaveOathProgress :exec
INSERT INTO character_oath_progress(character_id,dungeon_id,clears,updated_at)
VALUES(?1,?2,CAST(?3 AS INTEGER),
(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)))
ON CONFLICT(character_id,dungeon_id) DO UPDATE SET clears=EXCLUDED.clears,
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveOathProgressParams struct {
	CharacterID int64
	DungeonID   int64
	Clears      int64
}

// `clears` is PostgreSQL `::bigint`, so it keeps the int64 width via the CAST.
func (q *Queries) SaveOathProgress(ctx context.Context, arg SaveOathProgressParams) error {
	_, err := q.db.ExecContext(ctx, saveOathProgress, arg.CharacterID, arg.DungeonID, arg.Clears)
	return err
}

const saveOmenHeld = `-- name: SaveOmenHeld :exec
INSERT INTO character_omen_state(character_id,dungeon_id,held,updated_at)
VALUES(?1,?2,CAST(?3 AS INTEGER),
(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)))
ON CONFLICT(character_id,dungeon_id) DO UPDATE SET held=EXCLUDED.held,
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveOmenHeldParams struct {
	CharacterID int64
	DungeonID   int64
	Held        int64
}

// PostgreSQL casts `held` to bigint even though the column is integer, so the
// CAST keeps the int64 width on this side too (measured: CAST(... AS INTEGER)
// ignores the yaml width overrides and always yields int64).
func (q *Queries) SaveOmenHeld(ctx context.Context, arg SaveOmenHeldParams) error {
	_, err := q.db.ExecContext(ctx, saveOmenHeld, arg.CharacterID, arg.DungeonID, arg.Held)
	return err
}

const saveOmenMisses = `-- name: SaveOmenMisses :exec
INSERT INTO character_omen_state(character_id,dungeon_id,misses,updated_at)
VALUES(?1,?2,CAST(?3 AS INTEGER),
(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)))
ON CONFLICT(character_id,dungeon_id) DO UPDATE SET misses=EXCLUDED.misses,
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveOmenMissesParams struct {
	CharacterID int64
	DungeonID   int64
	Misses      int64
}

// 宽度与 SaveOmenHeld 一致：CAST(?3 AS INTEGER) 在 SQLite 上始终是 int64。
func (q *Queries) SaveOmenMisses(ctx context.Context, arg SaveOmenMissesParams) error {
	_, err := q.db.ExecContext(ctx, saveOmenMisses, arg.CharacterID, arg.DungeonID, arg.Misses)
	return err
}

const saveWorld = `-- name: SaveWorld :execrows
UPDATE character_world SET position=?1,revision=revision+1,
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
WHERE EXISTS(SELECT 1 FROM characters c WHERE c.id=character_world.character_id AND c.account_id=?2)
AND character_id=?3 AND revision=?4
`

type SaveWorldParams struct {
	Position    json.RawMessage
	AccountID   int64
	CharacterID int64
	Revision    int64
}

func (q *Queries) SaveWorld(ctx context.Context, arg SaveWorldParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveWorld,
		arg.Position,
		arg.AccountID,
		arg.CharacterID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const scrubPollutedWorldPositions = `-- name: ScrubPollutedWorldPositions :execrows
DELETE FROM character_world
WHERE CAST(json_extract(position,'$.town') AS INTEGER)
IN (SELECT CAST(value AS INTEGER) FROM json_each(CAST(?1 AS TEXT)))
`

func (q *Queries) ScrubPollutedWorldPositions(ctx context.Context, towns string) (int64, error) {
	result, err := q.db.ExecContext(ctx, scrubPollutedWorldPositions, towns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setOmenPending = `-- name: SetOmenPending :exec
INSERT INTO character_omen_state(character_id,dungeon_id,orthaire_pending,updated_at)
VALUES(?1,?2,?3,
(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)))
ON CONFLICT(character_id,dungeon_id) DO UPDATE SET orthaire_pending=EXCLUDED.orthaire_pending,
updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SetOmenPendingParams struct {
	CharacterID int64
	DungeonID   int64
	Pending     bool
}

func (q *Queries) SetOmenPending(ctx context.Context, arg SetOmenPendingParams) error {
	_, err := q.db.ExecContext(ctx, setOmenPending, arg.CharacterID, arg.DungeonID, arg.Pending)
	return err
}

const startBirth = `-- name: StartBirth :execrows
INSERT INTO character_birth(character_id,stage)
SELECT id,?1 FROM characters
WHERE account_id=?2 AND id=?3 ON CONFLICT(character_id) DO NOTHING
`

type StartBirthParams struct {
	Stage       int16
	AccountID   int64
	CharacterID int64
}

func (q *Queries) StartBirth(ctx context.Context, arg StartBirthParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startBirth, arg.Stage, arg.AccountID, arg.CharacterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
