// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quests.sql

package sqlcgensqlite

import (
	"context"
	"encoding/json"
	"time"
)

const abandonQuest = `-- name: AbandonQuest :execrows
DELETE FROM character_quests WHERE character_quests.character_id=?1
AND character_quests.quest_id=?2 AND character_quests.status='accepted'
AND EXISTS(SELECT 1 FROM characters c WHERE c.id=character_quests.character_id AND c.account_id=?3)
`

type AbandonQuestParams struct {
	CharacterID int64
	QuestID     int32
	AccountID   int64
}

// PostgreSQL: DELETE FROM character_quests q USING characters c WHERE ... The
// USING join is not SQLite grammar, so it becomes the equivalent correlated
// EXISTS with the same ownership predicate.
func (q *Queries) AbandonQuest(ctx context.Context, arg AbandonQuestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, abandonQuest, arg.CharacterID, arg.QuestID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const acceptQuest = `-- name: AcceptQuest :exec
INSERT INTO character_quests(character_id,quest_id,status,config_version,progress,progress_model)
VALUES(?1,?2,'accepted',?3,?4,?5)
`

type AcceptQuestParams struct {
	CharacterID   int64
	QuestID       int32
	ConfigVersion string
	Progress      int64
	ProgressModel string
}

func (q *Queries) AcceptQuest(ctx context.Context, arg AcceptQuestParams) error {
	_, err := q.db.ExecContext(ctx, acceptQuest,
		arg.CharacterID,
		arg.QuestID,
		arg.ConfigVersion,
		arg.Progress,
		arg.ProgressModel,
	)
	return err
}

const clearActQuests = `-- name: ClearActQuests :execrows
UPDATE character_quests SET status='completed',progress=0,progress_model='act-clear-v2',completed_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
WHERE character_id=?1 AND quest_id IN(SELECT value FROM json_each(CAST(?2 AS TEXT)))
AND status='accepted' AND config_version=?3
`

type ClearActQuestsParams struct {
	CharacterID   int64
	QuestIds      string
	ConfigVersion string
}

func (q *Queries) ClearActQuests(ctx context.Context, arg ClearActQuestsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearActQuests, arg.CharacterID, arg.QuestIds, arg.ConfigVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearQuests = `-- name: ClearQuests :execrows
INSERT INTO character_quests(character_id,quest_id,status,config_version,progress,progress_model)
SELECT c.id,CAST(j.value AS INTEGER),'completed',CAST(?1 AS TEXT),0,'odyssey-skip-v1'
FROM json_each(CAST(?2 AS TEXT)) j
JOIN characters c ON c.id=CAST(?3 AS INTEGER) AND c.account_id=CAST(?4 AS INTEGER) AND c.deleted_at IS NULL
ON CONFLICT(character_id,quest_id) DO NOTHING
`

type ClearQuestsParams struct {
	ConfigVersion string
	QuestIds      string
	CharacterID   int64
	AccountID     int64
}

func (q *Queries) ClearQuests(ctx context.Context, arg ClearQuestsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearQuests,
		arg.ConfigVersion,
		arg.QuestIds,
		arg.CharacterID,
		arg.AccountID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeGraduationQuests = `-- name: CompleteGraduationQuests :exec
INSERT INTO character_quests(character_id,quest_id,status,config_version,progress,progress_model,completed_at)
SELECT CAST(?1 AS INTEGER),CAST(j.value AS INTEGER),'completed',CAST(?2 AS TEXT),0,CAST(?3 AS TEXT),
(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
FROM json_each(CAST(?4 AS TEXT)) j
WHERE 1=1
ON CONFLICT(character_id,quest_id) DO UPDATE SET status='completed',progress=0,
progress_model=EXCLUDED.progress_model,config_version=EXCLUDED.config_version,
completed_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
WHERE character_quests.status='accepted'
`

type CompleteGraduationQuestsParams struct {
	CharacterID   int64
	ConfigVersion string
	ProgressModel string
	QuestIds      string
}

// unnest(...) becomes json_each(...); the ids arrive as a JSON array text.
// WHERE 1=1 is required, not decorative: when an INSERT ... SELECT ends on a bare
// table reference the SQLite parser reads the following ON as a join constraint and
// rejects ON CONFLICT ("near DO: syntax error"). A WHERE clause removes the
// ambiguity and is a no-op for the row set.
func (q *Queries) CompleteGraduationQuests(ctx context.Context, arg CompleteGraduationQuestsParams) error {
	_, err := q.db.ExecContext(ctx, completeGraduationQuests,
		arg.CharacterID,
		arg.ConfigVersion,
		arg.ProgressModel,
		arg.QuestIds,
	)
	return err
}

const completeQuestMapObjective = `-- name: CompleteQuestMapObjective :exec
UPDATE character_quests SET progress=0 WHERE character_id=?1
AND quest_id=?2 AND status='accepted' AND progress=1
AND config_version=?3 AND progress_model=?4
`

type CompleteQuestMapObjectiveParams struct {
	CharacterID   int64
	QuestID       int32
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) CompleteQuestMapObjective(ctx context.Context, arg CompleteQuestMapObjectiveParams) error {
	_, err := q.db.ExecContext(ctx, completeQuestMapObjective,
		arg.CharacterID,
		arg.QuestID,
		arg.ConfigVersion,
		arg.ProgressModel,
	)
	return err
}

const completeQuestObjective = `-- name: CompleteQuestObjective :execrows
UPDATE character_quests SET progress=0
WHERE character_quests.quest_id=?1 AND character_quests.status='accepted'
AND character_quests.config_version=?2 AND character_quests.progress_model=?3
AND character_quests.progress<>0
AND EXISTS(SELECT 1 FROM characters c WHERE c.id=character_quests.character_id
AND c.account_id=?4 AND c.id=?5 AND c.deleted_at IS NULL)
`

type CompleteQuestObjectiveParams struct {
	QuestID       int32
	ConfigVersion string
	ProgressModel string
	AccountID     int64
	CharacterID   int64
}

// PostgreSQL: UPDATE ... FROM characters c. Rewritten as a correlated EXISTS.
func (q *Queries) CompleteQuestObjective(ctx context.Context, arg CompleteQuestObjectiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeQuestObjective,
		arg.QuestID,
		arg.ConfigVersion,
		arg.ProgressModel,
		arg.AccountID,
		arg.CharacterID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeQuestUseObjective = `-- name: CompleteQuestUseObjective :execrows
UPDATE character_quests SET progress=0
WHERE character_quests.quest_id=?1 AND character_quests.status='accepted'
AND character_quests.config_version=?2 AND character_quests.progress_model=?3
AND character_quests.progress=1
AND EXISTS(SELECT 1 FROM characters c JOIN character_events e ON e.character_id=c.id
WHERE c.id=character_quests.character_id AND c.account_id=?4 AND c.id=?5
AND c.deleted_at IS NULL AND e.event_key=?6 AND e.config_version=?2
AND json_extract(e.outcome,'$.template')=CAST(?7 AS TEXT) AND e.created_at>=character_quests.accepted_at)
`

type CompleteQuestUseObjectiveParams struct {
	QuestID       int32
	ConfigVersion string
	ProgressModel string
	AccountID     int64
	CharacterID   int64
	EventKey      string
	Template      string
}

// PostgreSQL: UPDATE ... FROM characters c,character_events e. Rewritten as a
// correlated EXISTS over the same join, including the accepted_at bound.
func (q *Queries) CompleteQuestUseObjective(ctx context.Context, arg CompleteQuestUseObjectiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeQuestUseObjective,
		arg.QuestID,
		arg.ConfigVersion,
		arg.ProgressModel,
		arg.AccountID,
		arg.CharacterID,
		arg.EventKey,
		arg.Template,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeRewardedQuest = `-- name: CompleteRewardedQuest :exec
UPDATE character_quests SET status='completed',completed_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
WHERE character_id=?1 AND quest_id=?2
`

type CompleteRewardedQuestParams struct {
	CharacterID int64
	QuestID     int32
}

func (q *Queries) CompleteRewardedQuest(ctx context.Context, arg CompleteRewardedQuestParams) error {
	_, err := q.db.ExecContext(ctx, completeRewardedQuest, arg.CharacterID, arg.QuestID)
	return err
}

const completedQuestIDs = `-- name: CompletedQuestIDs :many
SELECT q.character_id,q.quest_id FROM character_quests q JOIN characters c ON c.id=q.character_id
WHERE c.account_id=?1 AND c.deleted_at IS NULL
AND q.status='completed' AND q.config_version=?2
AND q.quest_id IN(SELECT value FROM json_each(CAST(?3 AS TEXT)))
`

type CompletedQuestIDsParams struct {
	AccountID     int64
	ConfigVersion string
	QuestIds      string
}

type CompletedQuestIDsRow struct {
	CharacterID int64
	QuestID     int32
}

func (q *Queries) CompletedQuestIDs(ctx context.Context, arg CompletedQuestIDsParams) ([]CompletedQuestIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, completedQuestIDs, arg.AccountID, arg.ConfigVersion, arg.QuestIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompletedQuestIDsRow
	for rows.Next() {
		var i CompletedQuestIDsRow
		if err := rows.Scan(&i.CharacterID, &i.QuestID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasCompletedQuest = `-- name: HasCompletedQuest :one
SELECT EXISTS(SELECT 1 FROM character_quests WHERE character_id=?1
AND quest_id=?2 AND status='completed')
`

type HasCompletedQuestParams struct {
	CharacterID int64
	QuestID     int32
}

func (q *Queries) HasCompletedQuest(ctx context.Context, arg HasCompletedQuestParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasCompletedQuest, arg.CharacterID, arg.QuestID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockOwnedCharacterIncludingDeleted = `-- name: LockOwnedCharacterIncludingDeleted :one
SELECT id,account_id,wire_id,name,profession,create_request,config_version,state,created_at,
CAST(0 AS INTEGER) AS fixed_slot FROM characters
WHERE account_id=?1 AND id=?2
`

type LockOwnedCharacterIncludingDeletedParams struct {
	AccountID   int64
	CharacterID int64
}

type LockOwnedCharacterIncludingDeletedRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	CreatedAt     time.Time
	FixedSlot     int64
}

// Lock query; lock clause removed. The PostgreSQL 0::smallint projection is kept
// as an explicit CAST so sqlc does not infer interface{}.
func (q *Queries) LockOwnedCharacterIncludingDeleted(ctx context.Context, arg LockOwnedCharacterIncludingDeletedParams) (LockOwnedCharacterIncludingDeletedRow, error) {
	row := q.db.QueryRowContext(ctx, lockOwnedCharacterIncludingDeleted, arg.AccountID, arg.CharacterID)
	var i LockOwnedCharacterIncludingDeletedRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.WireID,
		&i.Name,
		&i.Profession,
		&i.CreateRequest,
		&i.ConfigVersion,
		&i.State,
		&i.CreatedAt,
		&i.FixedSlot,
	)
	return i, err
}

const lockOwnedCharacterState = `-- name: LockOwnedCharacterState :one

SELECT state FROM characters WHERE id=?1 AND account_id=?2
`

type LockOwnedCharacterStateParams struct {
	CharacterID int64
	AccountID   int64
}

// SQLite query fork of sql/postgres/queries/quests.sql (dual-engine, S3).
//
// The PostgreSQL file stays untouched and remains authoritative for the PG path.
// Dialect rules applied here are the ones in docs/sqlite-query-port-guide.md and
// restated in context in the header of sqlite/queries/core.sql:
//   - FOR UPDATE / FOR NO KEY UPDATE / FOR SHARE -> REMOVED. SQLite has no row
//     locks and rejects the clause; writers are serialized by BEGIN IMMEDIATE.
//     Lock queries keep their name and their ownership predicate.
//   - sqlc.arg(x)::type -> CAST(sqlc.arg(x) AS type). Spike rule R-1: a bare
//     expression infers interface{} and cannot enter the shared query interface,
//     so every expression result gets an explicit CAST.
//   - JSON parameters (before_state, after_state, receipt) are deliberately NOT
//     wrapped in CAST(... AS TEXT): that turns the parameter into a string, which
//     database/sql cannot scan into json.RawMessage. They are BLOB here, and a
//     BLOB parameter/result is generated as []byte, which json.RawMessage is
//     assignable to.
//   - unnest(sqlc.arg(ids)::integer[]) -> json_each(CAST(sqlc.arg(ids) AS TEXT));
//     the id list travels as a JSON array text and each element is cast back with
//     CAST(j.value AS INTEGER).
//   - quest_id=ANY(sqlc.arg(ids)::integer[]) -> quest_id IN (SELECT value FROM
//     json_each(CAST(sqlc.arg(ids) AS TEXT))).
//   - now() -> integer microseconds, matching the DDL defaults and the driver's
//     unix_micro representation.
//   - UPDATE ... FROM and DELETE ... USING are rejected by the SQLite grammar
//     (and by sqlc's SQLite parser). The five statements that used them keep the
//     identical ownership predicate, spelled as a correlated EXISTS over the same
//     characters/character_events join. Every outer column is table-qualified
//     because characters also has character_id/config_version.
//   - outcome->>'template' -> json_extract(outcome,'$.template'), compared against
//     a text parameter (CAST(sqlc.arg(template) AS TEXT)).
//
// Lock query; the FOR UPDATE is replaced by the engine-wide BEGIN IMMEDIATE write
// serialization. Name and ownership predicate are unchanged.
func (q *Queries) LockOwnedCharacterState(ctx context.Context, arg LockOwnedCharacterStateParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, lockOwnedCharacterState, arg.CharacterID, arg.AccountID)
	var state json.RawMessage
	err := row.Scan(&state)
	return state, err
}

const lockQuest = `-- name: LockQuest :one
SELECT status,progress,config_version,progress_model FROM character_quests
WHERE character_id=?1 AND quest_id=?2
`

type LockQuestParams struct {
	CharacterID int64
	QuestID     int32
}

type LockQuestRow struct {
	Status        string
	Progress      int64
	ConfigVersion string
	ProgressModel string
}

// Lock query; lock clause removed (see LockOwnedCharacterState).
func (q *Queries) LockQuest(ctx context.Context, arg LockQuestParams) (LockQuestRow, error) {
	row := q.db.QueryRowContext(ctx, lockQuest, arg.CharacterID, arg.QuestID)
	var i LockQuestRow
	err := row.Scan(
		&i.Status,
		&i.Progress,
		&i.ConfigVersion,
		&i.ProgressModel,
	)
	return i, err
}

const markMeetNPCQuest = `-- name: MarkMeetNPCQuest :execrows
UPDATE character_quests SET progress=0
WHERE character_quests.quest_id=?1 AND character_quests.status='accepted'
AND character_quests.config_version=?2 AND character_quests.progress_model=?3
AND character_quests.progress IN(0,1)
AND EXISTS(SELECT 1 FROM characters c WHERE c.id=character_quests.character_id
AND c.account_id=?4 AND c.id=?5 AND c.deleted_at IS NULL)
`

type MarkMeetNPCQuestParams struct {
	QuestID       int32
	ConfigVersion string
	ProgressModel string
	AccountID     int64
	CharacterID   int64
}

// PostgreSQL: UPDATE ... FROM characters c. Rewritten as a correlated EXISTS.
func (q *Queries) MarkMeetNPCQuest(ctx context.Context, arg MarkMeetNPCQuestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMeetNPCQuest,
		arg.QuestID,
		arg.ConfigVersion,
		arg.ProgressModel,
		arg.AccountID,
		arg.CharacterID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const quest = `-- name: Quest :one
SELECT status,progress,config_version,progress_model FROM character_quests
WHERE character_id=?1 AND quest_id=?2
`

type QuestParams struct {
	CharacterID int64
	QuestID     int32
}

type QuestRow struct {
	Status        string
	Progress      int64
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) Quest(ctx context.Context, arg QuestParams) (QuestRow, error) {
	row := q.db.QueryRowContext(ctx, quest, arg.CharacterID, arg.QuestID)
	var i QuestRow
	err := row.Scan(
		&i.Status,
		&i.Progress,
		&i.ConfigVersion,
		&i.ProgressModel,
	)
	return i, err
}

const questRewardReceipt = `-- name: QuestRewardReceipt :one
SELECT receipt FROM character_quest_rewards WHERE character_id=?1
AND quest_id=?2 AND source_version=?3
`

type QuestRewardReceiptParams struct {
	CharacterID   int64
	QuestID       int32
	SourceVersion string
}

func (q *Queries) QuestRewardReceipt(ctx context.Context, arg QuestRewardReceiptParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, questRewardReceipt, arg.CharacterID, arg.QuestID, arg.SourceVersion)
	var receipt json.RawMessage
	err := row.Scan(&receipt)
	return receipt, err
}

const quests = `-- name: Quests :many
SELECT quest_id,status,progress,config_version,progress_model FROM character_quests
WHERE character_id=?1 ORDER BY quest_id
`

type QuestsRow struct {
	QuestID       int32
	Status        string
	Progress      int64
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) Quests(ctx context.Context, characterID int64) ([]QuestsRow, error) {
	rows, err := q.db.QueryContext(ctx, quests, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsRow
	for rows.Next() {
		var i QuestsRow
		if err := rows.Scan(
			&i.QuestID,
			&i.Status,
			&i.Progress,
			&i.ConfigVersion,
			&i.ProgressModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLegacyQuestRepair = `-- name: RecordLegacyQuestRepair :exec
INSERT INTO character_quest_repairs(character_id,quest_id,reason,before_state,after_state)
VALUES(?1,?2,'initial-zero-false-completion',?3,?4)
`

type RecordLegacyQuestRepairParams struct {
	CharacterID int64
	QuestID     int32
	BeforeState json.RawMessage
	AfterState  json.RawMessage
}

func (q *Queries) RecordLegacyQuestRepair(ctx context.Context, arg RecordLegacyQuestRepairParams) error {
	_, err := q.db.ExecContext(ctx, recordLegacyQuestRepair,
		arg.CharacterID,
		arg.QuestID,
		arg.BeforeState,
		arg.AfterState,
	)
	return err
}

const recordQuestMapClear = `-- name: RecordQuestMapClear :execrows
INSERT INTO character_map_clears(character_id,run_id,map_id,source_version)
VALUES(?1,?2,?3,?4) ON CONFLICT DO NOTHING
`

type RecordQuestMapClearParams struct {
	CharacterID   int64
	RunID         string
	MapID         int64
	SourceVersion string
}

func (q *Queries) RecordQuestMapClear(ctx context.Context, arg RecordQuestMapClearParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordQuestMapClear,
		arg.CharacterID,
		arg.RunID,
		arg.MapID,
		arg.SourceVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordQuestReward = `-- name: RecordQuestReward :exec
INSERT INTO character_quest_rewards(character_id,quest_id,source_version,model,receipt)
VALUES(?1,?2,?3,?4,?5)
`

type RecordQuestRewardParams struct {
	CharacterID   int64
	QuestID       int32
	SourceVersion string
	Model         string
	Receipt       json.RawMessage
}

func (q *Queries) RecordQuestReward(ctx context.Context, arg RecordQuestRewardParams) error {
	_, err := q.db.ExecContext(ctx, recordQuestReward,
		arg.CharacterID,
		arg.QuestID,
		arg.SourceVersion,
		arg.Model,
		arg.Receipt,
	)
	return err
}

const repairLegacyQuest = `-- name: RepairLegacyQuest :execrows
UPDATE character_quests SET progress=?1,progress_model=?2
WHERE character_quests.quest_id=?3 AND character_quests.status='accepted'
AND character_quests.progress=0 AND character_quests.progress_model='legacy-zero'
AND character_quests.config_version=?4
AND EXISTS(SELECT 1 FROM characters c WHERE c.id=character_quests.character_id
AND c.account_id=?5 AND c.id=?6)
`

type RepairLegacyQuestParams struct {
	Progress      int64
	ProgressModel string
	QuestID       int32
	ConfigVersion string
	AccountID     int64
	CharacterID   int64
}

// PostgreSQL: UPDATE ... FROM characters c. Rewritten as a correlated EXISTS.
func (q *Queries) RepairLegacyQuest(ctx context.Context, arg RepairLegacyQuestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, repairLegacyQuest,
		arg.Progress,
		arg.ProgressModel,
		arg.QuestID,
		arg.ConfigVersion,
		arg.AccountID,
		arg.CharacterID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
