// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgensqlite

import (
	"context"
	"encoding/json"
	"time"
)

const accountGamepadSettings = `-- name: AccountGamepadSettings :one
SELECT mapping_tsv,options FROM account_gamepad_settings WHERE account_id=?1
`

type AccountGamepadSettingsRow struct {
	MappingTsv []byte
	Options    []byte
}

func (q *Queries) AccountGamepadSettings(ctx context.Context, accountID int64) (AccountGamepadSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, accountGamepadSettings, accountID)
	var i AccountGamepadSettingsRow
	err := row.Scan(&i.MappingTsv, &i.Options)
	return i, err
}

const accountHotkeys = `-- name: AccountHotkeys :many
SELECT slot_index, keycode FROM account_hotkeys WHERE account_id=?1 AND subtype=?2
`

type AccountHotkeysParams struct {
	AccountID int64
	Subtype   int16
}

type AccountHotkeysRow struct {
	SlotIndex int16
	Keycode   int32
}

func (q *Queries) AccountHotkeys(ctx context.Context, arg AccountHotkeysParams) ([]AccountHotkeysRow, error) {
	rows, err := q.db.QueryContext(ctx, accountHotkeys, arg.AccountID, arg.Subtype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountHotkeysRow
	for rows.Next() {
		var i AccountHotkeysRow
		if err := rows.Scan(&i.SlotIndex, &i.Keycode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountUnifiedOptions = `-- name: AccountUnifiedOptions :many
SELECT opt_index,value FROM account_unified_options WHERE account_id=?1 AND value <> 65535
`

type AccountUnifiedOptionsRow struct {
	OptIndex int32
	Value    int32
}

func (q *Queries) AccountUnifiedOptions(ctx context.Context, accountID int64) ([]AccountUnifiedOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, accountUnifiedOptions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountUnifiedOptionsRow
	for rows.Next() {
		var i AccountUnifiedOptionsRow
		if err := rows.Scan(&i.OptIndex, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountWarpFavorites = `-- name: AccountWarpFavorites :many
SELECT slot_index,value FROM account_warp_favorites WHERE account_id=?1 ORDER BY slot_index
`

type AccountWarpFavoritesRow struct {
	SlotIndex int16
	Value     []byte
}

func (q *Queries) AccountWarpFavorites(ctx context.Context, accountID int64) ([]AccountWarpFavoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, accountWarpFavorites, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountWarpFavoritesRow
	for rows.Next() {
		var i AccountWarpFavoritesRow
		if err := rows.Scan(&i.SlotIndex, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addSkillLock = `-- name: AddSkillLock :exec
INSERT INTO character_skill_locks(character_id,skill_id) VALUES(?1,?2)
`

type AddSkillLockParams struct {
	CharacterID int64
	SkillID     int32
}

func (q *Queries) AddSkillLock(ctx context.Context, arg AddSkillLockParams) error {
	_, err := q.db.ExecContext(ctx, addSkillLock, arg.CharacterID, arg.SkillID)
	return err
}

const addSkinFavorite = `-- name: AddSkinFavorite :exec
INSERT INTO character_skin_favorite(character_id,page,skin_key) VALUES(?1,?2,?3) ON CONFLICT DO NOTHING
`

type AddSkinFavoriteParams struct {
	CharacterID int64
	Page        int64
	SkinKey     int64
}

func (q *Queries) AddSkinFavorite(ctx context.Context, arg AddSkinFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, addSkinFavorite, arg.CharacterID, arg.Page, arg.SkinKey)
	return err
}

const addSkinSelectionList = `-- name: AddSkinSelectionList :exec
INSERT INTO character_skin_selection_list(character_id,category,skin_key) VALUES(?1,?2,?3) ON CONFLICT DO NOTHING
`

type AddSkinSelectionListParams struct {
	CharacterID int64
	Category    int64
	SkinKey     int64
}

func (q *Queries) AddSkinSelectionList(ctx context.Context, arg AddSkinSelectionListParams) error {
	_, err := q.db.ExecContext(ctx, addSkinSelectionList, arg.CharacterID, arg.Category, arg.SkinKey)
	return err
}

const addSkinSelectionSlot = `-- name: AddSkinSelectionSlot :exec
INSERT INTO character_skin_selection_slot(character_id,category,slot,skin_key) VALUES(?1,?2,?3,?4)
`

type AddSkinSelectionSlotParams struct {
	CharacterID int64
	Category    int64
	Slot        int64
	SkinKey     int64
}

func (q *Queries) AddSkinSelectionSlot(ctx context.Context, arg AddSkinSelectionSlotParams) error {
	_, err := q.db.ExecContext(ctx, addSkinSelectionSlot,
		arg.CharacterID,
		arg.Category,
		arg.Slot,
		arg.SkinKey,
	)
	return err
}

const characterGamepadSettings = `-- name: CharacterGamepadSettings :one
SELECT mapping_tsv,options FROM character_gamepad_settings WHERE character_id=?1
`

type CharacterGamepadSettingsRow struct {
	MappingTsv []byte
	Options    []byte
}

func (q *Queries) CharacterGamepadSettings(ctx context.Context, characterID int64) (CharacterGamepadSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, characterGamepadSettings, characterID)
	var i CharacterGamepadSettingsRow
	err := row.Scan(&i.MappingTsv, &i.Options)
	return i, err
}

const characterHotkeys = `-- name: CharacterHotkeys :many
SELECT slot_index, keycode FROM character_hotkeys WHERE character_id=?1 AND subtype=?2
`

type CharacterHotkeysParams struct {
	CharacterID int64
	Subtype     int16
}

type CharacterHotkeysRow struct {
	SlotIndex int16
	Keycode   int32
}

func (q *Queries) CharacterHotkeys(ctx context.Context, arg CharacterHotkeysParams) ([]CharacterHotkeysRow, error) {
	rows, err := q.db.QueryContext(ctx, characterHotkeys, arg.CharacterID, arg.Subtype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterHotkeysRow
	for rows.Next() {
		var i CharacterHotkeysRow
		if err := rows.Scan(&i.SlotIndex, &i.Keycode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const characterNoticeSeen = `-- name: CharacterNoticeSeen :many
SELECT notice_id FROM character_notice_seen WHERE account_id=?1 AND character_id=?2
AND tree=?3 ORDER BY notice_id
`

type CharacterNoticeSeenParams struct {
	AccountID   int64
	CharacterID int64
	Tree        int16
}

func (q *Queries) CharacterNoticeSeen(ctx context.Context, arg CharacterNoticeSeenParams) ([]int16, error) {
	rows, err := q.db.QueryContext(ctx, characterNoticeSeen, arg.AccountID, arg.CharacterID, arg.Tree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var notice_id int16
		if err := rows.Scan(&notice_id); err != nil {
			return nil, err
		}
		items = append(items, notice_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const characterUnifiedOptionGroup = `-- name: CharacterUnifiedOptionGroup :many
SELECT opt_index,value FROM character_unified_option_groups WHERE character_id=?1 AND subtype=?2
`

type CharacterUnifiedOptionGroupParams struct {
	CharacterID int64
	Subtype     int16
}

type CharacterUnifiedOptionGroupRow struct {
	OptIndex int32
	Value    int32
}

func (q *Queries) CharacterUnifiedOptionGroup(ctx context.Context, arg CharacterUnifiedOptionGroupParams) ([]CharacterUnifiedOptionGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, characterUnifiedOptionGroup, arg.CharacterID, arg.Subtype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterUnifiedOptionGroupRow
	for rows.Next() {
		var i CharacterUnifiedOptionGroupRow
		if err := rows.Scan(&i.OptIndex, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const characterUnifiedOptions = `-- name: CharacterUnifiedOptions :many
SELECT opt_index,value FROM character_unified_options WHERE character_id=?1
`

type CharacterUnifiedOptionsRow struct {
	OptIndex int32
	Value    int32
}

func (q *Queries) CharacterUnifiedOptions(ctx context.Context, characterID int64) ([]CharacterUnifiedOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, characterUnifiedOptions, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterUnifiedOptionsRow
	for rows.Next() {
		var i CharacterUnifiedOptionsRow
		if err := rows.Scan(&i.OptIndex, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearAccountCharacterGamepadSettings = `-- name: ClearAccountCharacterGamepadSettings :exec
DELETE FROM character_gamepad_settings WHERE account_id = ?1
`

func (q *Queries) ClearAccountCharacterGamepadSettings(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, clearAccountCharacterGamepadSettings, accountID)
	return err
}

const clearAccountCharacterHotkeys = `-- name: ClearAccountCharacterHotkeys :exec
DELETE FROM character_hotkeys
WHERE character_id IN (SELECT id FROM characters WHERE account_id = ?1)
  AND subtype = ?2
`

type ClearAccountCharacterHotkeysParams struct {
	AccountID int64
	Subtype   int16
}

func (q *Queries) ClearAccountCharacterHotkeys(ctx context.Context, arg ClearAccountCharacterHotkeysParams) error {
	_, err := q.db.ExecContext(ctx, clearAccountCharacterHotkeys, arg.AccountID, arg.Subtype)
	return err
}

const clearCharacterGamepadSettings = `-- name: ClearCharacterGamepadSettings :exec
DELETE FROM character_gamepad_settings WHERE character_id = ?1
`

func (q *Queries) ClearCharacterGamepadSettings(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, clearCharacterGamepadSettings, characterID)
	return err
}

const clearEquipmentSkill = `-- name: ClearEquipmentSkill :exec
DELETE FROM character_equipment_skill WHERE character_id=?1
`

func (q *Queries) ClearEquipmentSkill(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, clearEquipmentSkill, characterID)
	return err
}

const clearSkillLocks = `-- name: ClearSkillLocks :exec
DELETE FROM character_skill_locks WHERE character_id=?1
`

func (q *Queries) ClearSkillLocks(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, clearSkillLocks, characterID)
	return err
}

const clearSkinSelectionList = `-- name: ClearSkinSelectionList :exec
DELETE FROM character_skin_selection_list WHERE character_id=?1 AND category=?2
`

type ClearSkinSelectionListParams struct {
	CharacterID int64
	Category    int64
}

func (q *Queries) ClearSkinSelectionList(ctx context.Context, arg ClearSkinSelectionListParams) error {
	_, err := q.db.ExecContext(ctx, clearSkinSelectionList, arg.CharacterID, arg.Category)
	return err
}

const clearSkinSelectionSlots = `-- name: ClearSkinSelectionSlots :exec
DELETE FROM character_skin_selection_slot WHERE character_id=?1 AND category=?2
`

type ClearSkinSelectionSlotsParams struct {
	CharacterID int64
	Category    int64
}

func (q *Queries) ClearSkinSelectionSlots(ctx context.Context, arg ClearSkinSelectionSlotsParams) error {
	_, err := q.db.ExecContext(ctx, clearSkinSelectionSlots, arg.CharacterID, arg.Category)
	return err
}

const copyAccountHotkeysToCharacter = `-- name: CopyAccountHotkeysToCharacter :exec
INSERT INTO character_hotkeys (character_id, subtype, slot_index, keycode, updated_at)
SELECT CAST(?1 AS INTEGER), h.subtype, h.slot_index, h.keycode, (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
FROM account_hotkeys h
WHERE h.account_id = ?2 AND h.subtype = ?3
ON CONFLICT (character_id, subtype, slot_index) DO NOTHING
`

type CopyAccountHotkeysToCharacterParams struct {
	CharacterID int64
	AccountID   int64
	Subtype     int16
}

func (q *Queries) CopyAccountHotkeysToCharacter(ctx context.Context, arg CopyAccountHotkeysToCharacterParams) error {
	_, err := q.db.ExecContext(ctx, copyAccountHotkeysToCharacter, arg.CharacterID, arg.AccountID, arg.Subtype)
	return err
}

const countSkinFavorites = `-- name: CountSkinFavorites :one
SELECT count(*) FROM character_skin_favorite WHERE character_id=?1 AND page=?2
`

type CountSkinFavoritesParams struct {
	CharacterID int64
	Page        int64
}

func (q *Queries) CountSkinFavorites(ctx context.Context, arg CountSkinFavoritesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSkinFavorites, arg.CharacterID, arg.Page)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const equipmentSkillSnapshots = `-- name: EquipmentSkillSnapshots :one
SELECT s.skills,s.commands FROM characters c LEFT JOIN character_equipment_skill s ON s.character_id=c.id
WHERE c.id=?1 AND c.account_id=?2
`

type EquipmentSkillSnapshotsParams struct {
	CharacterID int64
	AccountID   int64
}

type EquipmentSkillSnapshotsRow struct {
	Skills   []byte
	Commands []byte
}

func (q *Queries) EquipmentSkillSnapshots(ctx context.Context, arg EquipmentSkillSnapshotsParams) (EquipmentSkillSnapshotsRow, error) {
	row := q.db.QueryRowContext(ctx, equipmentSkillSnapshots, arg.CharacterID, arg.AccountID)
	var i EquipmentSkillSnapshotsRow
	err := row.Scan(&i.Skills, &i.Commands)
	return i, err
}

const initializeProfileSkins = `-- name: InitializeProfileSkins :exec
INSERT INTO character_profile_skins(character_id,state) VALUES(?1,?2)
ON CONFLICT(character_id) DO NOTHING
`

type InitializeProfileSkinsParams struct {
	CharacterID int64
	State       json.RawMessage
}

func (q *Queries) InitializeProfileSkins(ctx context.Context, arg InitializeProfileSkinsParams) error {
	_, err := q.db.ExecContext(ctx, initializeProfileSkins, arg.CharacterID, arg.State)
	return err
}

const listSkins = `-- name: ListSkins :many
SELECT source_template,skin_key,unlocked_at FROM account_skin_cargo WHERE account_id=?1 AND skin_key<>0 ORDER BY source_template
`

type ListSkinsRow struct {
	SourceTemplate int64
	SkinKey        int64
	UnlockedAt     time.Time
}

func (q *Queries) ListSkins(ctx context.Context, accountID int64) ([]ListSkinsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSkins, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkinsRow
	for rows.Next() {
		var i ListSkinsRow
		if err := rows.Scan(&i.SourceTemplate, &i.SkinKey, &i.UnlockedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCharacterNotice = `-- name: MarkCharacterNotice :exec

INSERT INTO character_notice_seen(account_id,character_id,tree,notice_id)
VALUES(?1,?2,?3,?4) ON CONFLICT DO NOTHING
`

type MarkCharacterNoticeParams struct {
	AccountID   int64
	CharacterID int64
	Tree        int16
	NoticeID    int16
}

// SQLite query fork of sql/postgres/queries/settings.sql (dual-engine, S3).
//
// The PostgreSQL file stays untouched and remains authoritative for the PG path;
// this fork only has to expose the same query names to the SQLite package.
//
// Dialect rules applied (docs/sqlite-query-port-guide.md; core.sql's header has
// the same list in context):
//   - The PostgreSQL source has no FOR UPDATE / FOR NO KEY UPDATE / FOR SHARE
//     clause in this file, so nothing had to be deleted here.
//   - The sqlite DDL mirrors the PostgreSQL column widths (BIGINT / SMALLINT /
//     INTEGER) and sqlc types a bare sqlc.arg() bound to such a column from that
//     column, so arguments stay uncast wherever the column supplies the width.
//     An explicit CAST(... AS INTEGER) is used only where the PostgreSQL side is
//     a bigint expression, because a cast type name is NOT covered by the db_type
//     overrides and always resolves to int64 (see RosterBackgroundUnlocks and
//     SkinFavorites). SPIKE RULE R-1 asks for the cast only when sqlc would
//     otherwise infer interface{}; every generated type was inspected and no
//     parameter in this file regressed to interface{}.
//   - The JSON parameter of InitializeProfileSkins (`state`) is deliberately NOT
//     cast: CAST(sqlc.arg(state) AS TEXT) would turn the parameter into a string,
//     which database/sql cannot scan into json.RawMessage (see core.sql, D24).
//     character_profile_skins.state has a per-column override, so the parameter
//     and the ProfileSkins result both stay json.RawMessage.
//   - now() -> integer microseconds, matching the sqlite DDL defaults and the
//     driver's _inttotime=1 + _time_integer_format=unix_micro representation.
//   - IS DISTINCT FROM is NOT kept as written. The bundled driver (SQLite
//     3.53.4) does implement it, but sqlc v1.31.1's SQLite grammar does not
//     parse it ("extraneous input 'FROM'", also seen in a plain UPDATE ... WHERE).
//     SQLite's null-safe `IS NOT` is the exact equivalent and is used instead
//     (both columns are NOT NULL, so `<>` would also be equivalent).
//   - Parameters inside an ON CONFLICT ... DO UPDATE clause (SET or WHERE) are
//     emitted VERBATIM by the SQLite engine -- sqlc does not rewrite
//     sqlc.arg(...) to a placeholder there, which would ship a broken statement
//     and still exit 0. UnlockRosterBackground therefore hoists its guard into
//     the parsed SELECT of the INSERT (see the comment on that query). Every
//     other upsert in this file has a parameter-free DO UPDATE clause.
//   - Everything else -- the plain ON CONFLICT DO NOTHING upserts, the
//     parameter-free DO UPDATE upserts and count(*) in CountSkinFavorites -- is
//     unchanged apart from the now() and JSON rules above.
//   - LIMIT/OFFSET: no LIMIT or OFFSET appears in this file, so the ordering rule
//     (LIMIT before OFFSET) has nothing to apply to here.
//
// Nothing in the source needed the PostgreSQL-only escape hatch: there is no
// current_database(), pg_try_advisory_lock*, pg_advisory_*, nextval, unnest,
// plainto_tsquery or `= ANY(...)` in settings.sql. All 55 queries are ported.
func (q *Queries) MarkCharacterNotice(ctx context.Context, arg MarkCharacterNoticeParams) error {
	_, err := q.db.ExecContext(ctx, markCharacterNotice,
		arg.AccountID,
		arg.CharacterID,
		arg.Tree,
		arg.NoticeID,
	)
	return err
}

const profileSkins = `-- name: ProfileSkins :one
SELECT state FROM character_profile_skins WHERE character_id=?1
`

func (q *Queries) ProfileSkins(ctx context.Context, characterID int64) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, profileSkins, characterID)
	var state json.RawMessage
	err := row.Scan(&state)
	return state, err
}

const promoteCharacterHotkeysToAccount = `-- name: PromoteCharacterHotkeysToAccount :exec
INSERT INTO account_hotkeys (account_id, subtype, slot_index, keycode, updated_at)
SELECT CAST(?1 AS INTEGER), h.subtype, h.slot_index, h.keycode, (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
FROM character_hotkeys h
WHERE h.character_id = ?2 AND h.subtype = ?3
ON CONFLICT (account_id, subtype, slot_index)
DO UPDATE SET keycode = EXCLUDED.keycode, updated_at = (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type PromoteCharacterHotkeysToAccountParams struct {
	AccountID   int64
	CharacterID int64
	Subtype     int16
}

func (q *Queries) PromoteCharacterHotkeysToAccount(ctx context.Context, arg PromoteCharacterHotkeysToAccountParams) error {
	_, err := q.db.ExecContext(ctx, promoteCharacterHotkeysToAccount, arg.AccountID, arg.CharacterID, arg.Subtype)
	return err
}

const removeSkinFavorite = `-- name: RemoveSkinFavorite :exec
DELETE FROM character_skin_favorite WHERE character_id=?1 AND page=?2 AND skin_key=?3
`

type RemoveSkinFavoriteParams struct {
	CharacterID int64
	Page        int64
	SkinKey     int64
}

func (q *Queries) RemoveSkinFavorite(ctx context.Context, arg RemoveSkinFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeSkinFavorite, arg.CharacterID, arg.Page, arg.SkinKey)
	return err
}

const rosterBackgroundUnlocks = `-- name: RosterBackgroundUnlocks :many
SELECT category,background_id,expires_at FROM account_roster_background_unlocks
WHERE account_id=?1 AND (expires_at=0 OR expires_at>CAST(?2 AS INTEGER))
ORDER BY category,background_id
`

type RosterBackgroundUnlocksParams struct {
	AccountID int64
	NowUnix   int64
}

type RosterBackgroundUnlocksRow struct {
	Category     int16
	BackgroundID int32
	ExpiresAt    int64
}

func (q *Queries) RosterBackgroundUnlocks(ctx context.Context, arg RosterBackgroundUnlocksParams) ([]RosterBackgroundUnlocksRow, error) {
	rows, err := q.db.QueryContext(ctx, rosterBackgroundUnlocks, arg.AccountID, arg.NowUnix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RosterBackgroundUnlocksRow
	for rows.Next() {
		var i RosterBackgroundUnlocksRow
		if err := rows.Scan(&i.Category, &i.BackgroundID, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rosterBackgrounds = `-- name: RosterBackgrounds :many
SELECT page,category,background_id FROM account_roster_backgrounds WHERE account_id=?1 ORDER BY page
`

type RosterBackgroundsRow struct {
	Page         int16
	Category     int16
	BackgroundID int32
}

func (q *Queries) RosterBackgrounds(ctx context.Context, accountID int64) ([]RosterBackgroundsRow, error) {
	rows, err := q.db.QueryContext(ctx, rosterBackgrounds, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RosterBackgroundsRow
	for rows.Next() {
		var i RosterBackgroundsRow
		if err := rows.Scan(&i.Page, &i.Category, &i.BackgroundID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAccountGamepadKeys = `-- name: SaveAccountGamepadKeys :exec
INSERT INTO account_gamepad_settings(account_id, mapping_tsv, updated_at)
VALUES(?1, ?2, (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)))
ON CONFLICT (account_id)
DO UPDATE SET mapping_tsv = EXCLUDED.mapping_tsv, updated_at = (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveAccountGamepadKeysParams struct {
	AccountID  int64
	MappingTsv []byte
}

func (q *Queries) SaveAccountGamepadKeys(ctx context.Context, arg SaveAccountGamepadKeysParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountGamepadKeys, arg.AccountID, arg.MappingTsv)
	return err
}

const saveAccountGamepadOptions = `-- name: SaveAccountGamepadOptions :exec
INSERT INTO account_gamepad_settings(account_id, options, updated_at)
VALUES(?1, ?2, (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)))
ON CONFLICT (account_id)
DO UPDATE SET options = EXCLUDED.options, updated_at = (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveAccountGamepadOptionsParams struct {
	AccountID int64
	Options   []byte
}

func (q *Queries) SaveAccountGamepadOptions(ctx context.Context, arg SaveAccountGamepadOptionsParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountGamepadOptions, arg.AccountID, arg.Options)
	return err
}

const saveAccountHotkey = `-- name: SaveAccountHotkey :exec
INSERT INTO account_hotkeys(account_id, subtype, slot_index, keycode)
VALUES(?1, ?2, ?3, ?4)
ON CONFLICT(account_id, subtype, slot_index) DO UPDATE SET keycode=EXCLUDED.keycode, updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveAccountHotkeyParams struct {
	AccountID int64
	Subtype   int16
	SlotIndex int16
	Keycode   int32
}

func (q *Queries) SaveAccountHotkey(ctx context.Context, arg SaveAccountHotkeyParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountHotkey,
		arg.AccountID,
		arg.Subtype,
		arg.SlotIndex,
		arg.Keycode,
	)
	return err
}

const saveAccountUnifiedOption = `-- name: SaveAccountUnifiedOption :exec
INSERT INTO account_unified_options(account_id,opt_index,value) VALUES(?1,?2,?3)
 ON CONFLICT(account_id,opt_index) DO UPDATE SET value=EXCLUDED.value,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveAccountUnifiedOptionParams struct {
	AccountID int64
	OptIndex  int32
	Value     int32
}

func (q *Queries) SaveAccountUnifiedOption(ctx context.Context, arg SaveAccountUnifiedOptionParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountUnifiedOption, arg.AccountID, arg.OptIndex, arg.Value)
	return err
}

const saveAccountWarpFavorite = `-- name: SaveAccountWarpFavorite :exec
INSERT INTO account_warp_favorites(account_id,slot_index,value)
VALUES(?1,?2,?3)
ON CONFLICT(account_id,slot_index) DO UPDATE SET value=EXCLUDED.value,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
WHERE account_warp_favorites.value IS NOT EXCLUDED.value
`

type SaveAccountWarpFavoriteParams struct {
	AccountID int64
	SlotIndex int16
	Value     []byte
}

func (q *Queries) SaveAccountWarpFavorite(ctx context.Context, arg SaveAccountWarpFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountWarpFavorite, arg.AccountID, arg.SlotIndex, arg.Value)
	return err
}

const saveCharacterGamepadKeys = `-- name: SaveCharacterGamepadKeys :exec
INSERT INTO character_gamepad_settings(character_id, account_id, mapping_tsv, updated_at)
VALUES(?1, ?2, ?3, (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)))
ON CONFLICT (character_id)
DO UPDATE SET account_id = EXCLUDED.account_id, mapping_tsv = EXCLUDED.mapping_tsv, updated_at = (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveCharacterGamepadKeysParams struct {
	CharacterID int64
	AccountID   int64
	MappingTsv  []byte
}

func (q *Queries) SaveCharacterGamepadKeys(ctx context.Context, arg SaveCharacterGamepadKeysParams) error {
	_, err := q.db.ExecContext(ctx, saveCharacterGamepadKeys, arg.CharacterID, arg.AccountID, arg.MappingTsv)
	return err
}

const saveCharacterGamepadOptions = `-- name: SaveCharacterGamepadOptions :exec
INSERT INTO character_gamepad_settings(character_id, account_id, options, updated_at)
VALUES(?1, ?2, ?3, (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER)))
ON CONFLICT (character_id)
DO UPDATE SET account_id = EXCLUDED.account_id, options = EXCLUDED.options, updated_at = (CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveCharacterGamepadOptionsParams struct {
	CharacterID int64
	AccountID   int64
	Options     []byte
}

func (q *Queries) SaveCharacterGamepadOptions(ctx context.Context, arg SaveCharacterGamepadOptionsParams) error {
	_, err := q.db.ExecContext(ctx, saveCharacterGamepadOptions, arg.CharacterID, arg.AccountID, arg.Options)
	return err
}

const saveCharacterHotkey = `-- name: SaveCharacterHotkey :exec
INSERT INTO character_hotkeys(character_id, subtype, slot_index, keycode)
VALUES(?1, ?2, ?3, ?4)
ON CONFLICT(character_id, subtype, slot_index) DO UPDATE SET keycode=EXCLUDED.keycode, updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveCharacterHotkeyParams struct {
	CharacterID int64
	Subtype     int16
	SlotIndex   int16
	Keycode     int32
}

func (q *Queries) SaveCharacterHotkey(ctx context.Context, arg SaveCharacterHotkeyParams) error {
	_, err := q.db.ExecContext(ctx, saveCharacterHotkey,
		arg.CharacterID,
		arg.Subtype,
		arg.SlotIndex,
		arg.Keycode,
	)
	return err
}

const saveCharacterUnifiedOption = `-- name: SaveCharacterUnifiedOption :exec
INSERT INTO character_unified_options(character_id,opt_index,value) VALUES(?1,?2,?3)
 ON CONFLICT(character_id,opt_index) DO UPDATE SET value=EXCLUDED.value,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveCharacterUnifiedOptionParams struct {
	CharacterID int64
	OptIndex    int32
	Value       int32
}

func (q *Queries) SaveCharacterUnifiedOption(ctx context.Context, arg SaveCharacterUnifiedOptionParams) error {
	_, err := q.db.ExecContext(ctx, saveCharacterUnifiedOption, arg.CharacterID, arg.OptIndex, arg.Value)
	return err
}

const saveCharacterUnifiedOptionGroup = `-- name: SaveCharacterUnifiedOptionGroup :exec
INSERT INTO character_unified_option_groups(character_id,subtype,opt_index,value) VALUES(?1,?2,?3,?4)
ON CONFLICT(character_id,subtype,opt_index) DO UPDATE SET value=EXCLUDED.value,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveCharacterUnifiedOptionGroupParams struct {
	CharacterID int64
	Subtype     int16
	OptIndex    int32
	Value       int32
}

func (q *Queries) SaveCharacterUnifiedOptionGroup(ctx context.Context, arg SaveCharacterUnifiedOptionGroupParams) error {
	_, err := q.db.ExecContext(ctx, saveCharacterUnifiedOptionGroup,
		arg.CharacterID,
		arg.Subtype,
		arg.OptIndex,
		arg.Value,
	)
	return err
}

const saveEquipmentCommands = `-- name: SaveEquipmentCommands :exec
INSERT INTO character_equipment_skill(character_id,commands,updated_at)
VALUES(?1,?2,(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))) ON CONFLICT(character_id)
DO UPDATE SET commands=EXCLUDED.commands,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveEquipmentCommandsParams struct {
	CharacterID int64
	Commands    []byte
}

func (q *Queries) SaveEquipmentCommands(ctx context.Context, arg SaveEquipmentCommandsParams) error {
	_, err := q.db.ExecContext(ctx, saveEquipmentCommands, arg.CharacterID, arg.Commands)
	return err
}

const saveEquipmentSkills = `-- name: SaveEquipmentSkills :exec
INSERT INTO character_equipment_skill(character_id,skills,updated_at)
VALUES(?1,?2,(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))) ON CONFLICT(character_id)
DO UPDATE SET skills=EXCLUDED.skills,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveEquipmentSkillsParams struct {
	CharacterID int64
	Skills      []byte
}

func (q *Queries) SaveEquipmentSkills(ctx context.Context, arg SaveEquipmentSkillsParams) error {
	_, err := q.db.ExecContext(ctx, saveEquipmentSkills, arg.CharacterID, arg.Skills)
	return err
}

const saveTutorialFlag = `-- name: SaveTutorialFlag :execrows
INSERT INTO character_tutorial_flags(character_id,flag,completed)
SELECT id,?1,?2 FROM characters
WHERE account_id=?3 AND id=?4
ON CONFLICT(character_id,flag) DO UPDATE SET completed=EXCLUDED.completed,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SaveTutorialFlagParams struct {
	Flag        int32
	Completed   bool
	AccountID   int64
	CharacterID int64
}

// flag and completed are typed by the INSERT target columns (INTEGER, BOOLEAN),
// which is exactly the PostgreSQL `::integer` / `::boolean` width.
func (q *Queries) SaveTutorialFlag(ctx context.Context, arg SaveTutorialFlagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveTutorialFlag,
		arg.Flag,
		arg.Completed,
		arg.AccountID,
		arg.CharacterID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectRosterBackground = `-- name: SelectRosterBackground :exec
INSERT INTO account_roster_backgrounds(account_id,page,category,background_id)
VALUES(?1,?2,?3,?4)
ON CONFLICT(account_id,page) DO UPDATE SET category=EXCLUDED.category,background_id=EXCLUDED.background_id,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SelectRosterBackgroundParams struct {
	AccountID    int64
	Page         int16
	Category     int16
	BackgroundID int32
}

func (q *Queries) SelectRosterBackground(ctx context.Context, arg SelectRosterBackgroundParams) error {
	_, err := q.db.ExecContext(ctx, selectRosterBackground,
		arg.AccountID,
		arg.Page,
		arg.Category,
		arg.BackgroundID,
	)
	return err
}

const selectSkin = `-- name: SelectSkin :exec
INSERT INTO character_skin_selection(character_id,page,skin_key)
VALUES(?1,?2,?3)
ON CONFLICT(character_id,page) DO UPDATE SET skin_key=EXCLUDED.skin_key,updated_at=(CAST((julianday('now') - 2440587.5) * 86400000000 AS INTEGER))
`

type SelectSkinParams struct {
	CharacterID int64
	Page        int64
	SkinKey     int64
}

func (q *Queries) SelectSkin(ctx context.Context, arg SelectSkinParams) error {
	_, err := q.db.ExecContext(ctx, selectSkin, arg.CharacterID, arg.Page, arg.SkinKey)
	return err
}

const selectedSkin = `-- name: SelectedSkin :one
SELECT skin_key FROM character_skin_selection
WHERE character_id=?1 AND page=?2
`

type SelectedSkinParams struct {
	CharacterID int64
	Page        int64
}

func (q *Queries) SelectedSkin(ctx context.Context, arg SelectedSkinParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectedSkin, arg.CharacterID, arg.Page)
	var skin_key int64
	err := row.Scan(&skin_key)
	return skin_key, err
}

const skillLocks = `-- name: SkillLocks :many
SELECT skill_id FROM character_skill_locks WHERE character_id=?1 ORDER BY skill_id
`

func (q *Queries) SkillLocks(ctx context.Context, characterID int64) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, skillLocks, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var skill_id int32
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skinFavorites = `-- name: SkinFavorites :many
SELECT page,skin_key FROM character_skin_favorite WHERE character_id=?1 AND page<CAST(?2 AS INTEGER) ORDER BY page,skin_key
`

type SkinFavoritesParams struct {
	CharacterID int64
	Groups      int64
}

type SkinFavoritesRow struct {
	Page    int64
	SkinKey int64
}

func (q *Queries) SkinFavorites(ctx context.Context, arg SkinFavoritesParams) ([]SkinFavoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, skinFavorites, arg.CharacterID, arg.Groups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkinFavoritesRow
	for rows.Next() {
		var i SkinFavoritesRow
		if err := rows.Scan(&i.Page, &i.SkinKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skinSelectionList = `-- name: SkinSelectionList :many
SELECT skin_key FROM character_skin_selection_list WHERE character_id=?1 AND category=?2 ORDER BY skin_key
`

type SkinSelectionListParams struct {
	CharacterID int64
	Category    int64
}

func (q *Queries) SkinSelectionList(ctx context.Context, arg SkinSelectionListParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, skinSelectionList, arg.CharacterID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var skin_key int64
		if err := rows.Scan(&skin_key); err != nil {
			return nil, err
		}
		items = append(items, skin_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skinSelectionSlots = `-- name: SkinSelectionSlots :many
SELECT slot,skin_key FROM character_skin_selection_slot WHERE character_id=?1 AND category=?2
`

type SkinSelectionSlotsParams struct {
	CharacterID int64
	Category    int64
}

type SkinSelectionSlotsRow struct {
	Slot    int64
	SkinKey int64
}

func (q *Queries) SkinSelectionSlots(ctx context.Context, arg SkinSelectionSlotsParams) ([]SkinSelectionSlotsRow, error) {
	rows, err := q.db.QueryContext(ctx, skinSelectionSlots, arg.CharacterID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkinSelectionSlotsRow
	for rows.Next() {
		var i SkinSelectionSlotsRow
		if err := rows.Scan(&i.Slot, &i.SkinKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tutorialFlags = `-- name: TutorialFlags :many
SELECT flag FROM character_tutorial_flags WHERE character_id=?1 AND completed ORDER BY flag
`

func (q *Queries) TutorialFlags(ctx context.Context, characterID int64) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, tutorialFlags, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var flag int32
		if err := rows.Scan(&flag); err != nil {
			return nil, err
		}
		items = append(items, flag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlockRosterBackground = `-- name: UnlockRosterBackground :execrows
INSERT INTO account_roster_background_unlocks(account_id,category,background_id,expires_at)
SELECT ?1,?2,?3,?4
WHERE NOT EXISTS(SELECT 1 FROM account_roster_background_unlocks u
 WHERE u.account_id=?1
 AND u.category=?2
 AND u.background_id=?3
 AND (u.expires_at=0 OR u.expires_at>CAST(?5 AS INTEGER)))
ON CONFLICT(account_id,category,background_id) DO UPDATE SET expires_at=EXCLUDED.expires_at
`

type UnlockRosterBackgroundParams struct {
	AccountID    int64
	Category     int16
	BackgroundID int32
	ExpiresAt    int64
	NowUnix      int64
}

// The PostgreSQL guard (`... expires_at>0 AND expires_at<=sqlc.arg(now_unix)::bigint`)
// lives in the DO UPDATE WHERE clause, which the SQLite engine copies verbatim
// without binding its parameter. The guard is therefore moved into the parsed
// SELECT of the INSERT: a row is offered for insertion only when the stored
// unlock is absent, non-expiring (0) or already expired -- the exact complement
// of the PostgreSQL guard -- and the conflict clause keeps the same
// parameter-free DO UPDATE. Resulting row-counts are identical: no stored row
// or an expired one updates (1), a still-valid one is left alone (0).
func (q *Queries) UnlockRosterBackground(ctx context.Context, arg UnlockRosterBackgroundParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unlockRosterBackground,
		arg.AccountID,
		arg.Category,
		arg.BackgroundID,
		arg.ExpiresAt,
		arg.NowUnix,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unlockSkin = `-- name: UnlockSkin :exec
INSERT INTO account_skin_cargo(account_id,source_template,skin_key) VALUES(?1,?2,?3) ON CONFLICT(account_id,source_template) DO NOTHING
`

type UnlockSkinParams struct {
	AccountID      int64
	SourceTemplate int64
	SkinKey        int64
}

func (q *Queries) UnlockSkin(ctx context.Context, arg UnlockSkinParams) error {
	_, err := q.db.ExecContext(ctx, unlockSkin, arg.AccountID, arg.SourceTemplate, arg.SkinKey)
	return err
}

const unmarkCharacterNotice = `-- name: UnmarkCharacterNotice :exec
DELETE FROM character_notice_seen WHERE account_id=?1 AND character_id=?2
AND tree=?3 AND notice_id=?4
`

type UnmarkCharacterNoticeParams struct {
	AccountID   int64
	CharacterID int64
	Tree        int16
	NoticeID    int16
}

func (q *Queries) UnmarkCharacterNotice(ctx context.Context, arg UnmarkCharacterNoticeParams) error {
	_, err := q.db.ExecContext(ctx, unmarkCharacterNotice,
		arg.AccountID,
		arg.CharacterID,
		arg.Tree,
		arg.NoticeID,
	)
	return err
}
