// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adventure.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const adventureCollectionEquipment = `-- name: AdventureCollectionEquipment :one
SELECT COALESCE(a.data->'collection_equipment','{}'::jsonb)::jsonb AS equipment FROM characters c
LEFT JOIN account_adventures a ON a.account_id=c.account_id
WHERE c.account_id=$1 AND c.id=$2 AND c.deleted_at IS NULL
`

type AdventureCollectionEquipmentParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) AdventureCollectionEquipment(ctx context.Context, arg AdventureCollectionEquipmentParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, adventureCollectionEquipment, arg.AccountID, arg.CharacterID)
	var equipment json.RawMessage
	err := row.Scan(&equipment)
	return equipment, err
}

const adventureEquipmentRegistered = `-- name: AdventureEquipmentRegistered :one
SELECT COALESCE((a.data->'collection_equipment'->>($1::bigint::text))::boolean,false)::boolean AS registered
FROM characters c LEFT JOIN account_adventures a ON a.account_id=c.account_id
WHERE c.account_id=$2 AND c.id=$3 AND c.deleted_at IS NULL
`

type AdventureEquipmentRegisteredParams struct {
	Template    int64
	AccountID   int64
	CharacterID int64
}

func (q *Queries) AdventureEquipmentRegistered(ctx context.Context, arg AdventureEquipmentRegisteredParams) (bool, error) {
	row := q.db.QueryRow(ctx, adventureEquipmentRegistered, arg.Template, arg.AccountID, arg.CharacterID)
	var registered bool
	err := row.Scan(&registered)
	return registered, err
}

const adventureEventReceipt = `-- name: AdventureEventReceipt :one
SELECT outcome FROM character_events WHERE character_id=$1
AND event_key=$2 AND model='account-adventure-v1'
`

type AdventureEventReceiptParams struct {
	CharacterID int64
	EventKey    string
}

func (q *Queries) AdventureEventReceipt(ctx context.Context, arg AdventureEventReceiptParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, adventureEventReceipt, arg.CharacterID, arg.EventKey)
	var outcome json.RawMessage
	err := row.Scan(&outcome)
	return outcome, err
}

const adventureLevel = `-- name: AdventureLevel :one
SELECT COALESCE(a.level,1)::integer AS level FROM characters c
LEFT JOIN account_adventures a ON a.account_id=c.account_id
WHERE c.account_id=$1 AND c.id=$2 AND c.deleted_at IS NULL
`

type AdventureLevelParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) AdventureLevel(ctx context.Context, arg AdventureLevelParams) (int32, error) {
	row := q.db.QueryRow(ctx, adventureLevel, arg.AccountID, arg.CharacterID)
	var level int32
	err := row.Scan(&level)
	return level, err
}

const bleedingMineTeams = `-- name: BleedingMineTeams :many
SELECT team,members FROM account_bleeding_mine_teams WHERE account_id=$1
`

type BleedingMineTeamsRow struct {
	Team    int32
	Members []int64
}

func (q *Queries) BleedingMineTeams(ctx context.Context, accountID int64) ([]BleedingMineTeamsRow, error) {
	rows, err := q.db.Query(ctx, bleedingMineTeams, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BleedingMineTeamsRow
	for rows.Next() {
		var i BleedingMineTeamsRow
		if err := rows.Scan(&i.Team, &i.Members); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureAdventure = `-- name: EnsureAdventure :exec
INSERT INTO account_adventures(account_id,name,created_at)
SELECT id,$1::text,created_at FROM accounts WHERE id=$2::bigint ON CONFLICT DO NOTHING
`

type EnsureAdventureParams struct {
	Name      string
	AccountID int64
}

func (q *Queries) EnsureAdventure(ctx context.Context, arg EnsureAdventureParams) error {
	_, err := q.db.Exec(ctx, ensureAdventure, arg.Name, arg.AccountID)
	return err
}

const ensureBleedingMineRewards = `-- name: EnsureBleedingMineRewards :exec
INSERT INTO account_bleeding_mine_rewards(account_id) VALUES($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureBleedingMineRewards(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, ensureBleedingMineRewards, accountID)
	return err
}

const ensureOwnedAdventure = `-- name: EnsureOwnedAdventure :exec
INSERT INTO account_adventures(account_id,name,created_at)
SELECT a.id,$1::text,a.created_at FROM accounts a JOIN characters c ON c.account_id=a.id
WHERE a.id=$2::bigint AND c.id=$3::bigint AND c.deleted_at IS NULL
ON CONFLICT(account_id) DO NOTHING
`

type EnsureOwnedAdventureParams struct {
	Name        string
	AccountID   int64
	CharacterID int64
}

func (q *Queries) EnsureOwnedAdventure(ctx context.Context, arg EnsureOwnedAdventureParams) error {
	_, err := q.db.Exec(ctx, ensureOwnedAdventure, arg.Name, arg.AccountID, arg.CharacterID)
	return err
}

const firstActiveCharacterName = `-- name: FirstActiveCharacterName :one
SELECT name FROM characters WHERE account_id=$1 AND deleted_at IS NULL ORDER BY id LIMIT 1
`

func (q *Queries) FirstActiveCharacterName(ctx context.Context, accountID int64) (string, error) {
	row := q.db.QueryRow(ctx, firstActiveCharacterName, accountID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listFavor = `-- name: ListFavor :many
SELECT npc_id,point FROM npc_favor WHERE character_id=$1 AND point>0 ORDER BY npc_id
`

type ListFavorRow struct {
	NpcID int64
	Point int64
}

func (q *Queries) ListFavor(ctx context.Context, characterID int64) ([]ListFavorRow, error) {
	rows, err := q.db.Query(ctx, listFavor, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavorRow
	for rows.Next() {
		var i ListFavorRow
		if err := rows.Scan(&i.NpcID, &i.Point); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAdventure = `-- name: LoadAdventure :one
SELECT a.name,a.level,a.experience,a.created_at,a.data FROM account_adventures a JOIN characters c ON c.account_id=a.account_id
WHERE a.account_id=$1 AND c.id=$2 AND c.deleted_at IS NULL
`

type LoadAdventureParams struct {
	AccountID   int64
	CharacterID int64
}

type LoadAdventureRow struct {
	Name       string
	Level      int32
	Experience int64
	CreatedAt  time.Time
	Data       json.RawMessage
}

func (q *Queries) LoadAdventure(ctx context.Context, arg LoadAdventureParams) (LoadAdventureRow, error) {
	row := q.db.QueryRow(ctx, loadAdventure, arg.AccountID, arg.CharacterID)
	var i LoadAdventureRow
	err := row.Scan(
		&i.Name,
		&i.Level,
		&i.Experience,
		&i.CreatedAt,
		&i.Data,
	)
	return i, err
}

const lockAdventure = `-- name: LockAdventure :one
SELECT name,level,experience,created_at,data FROM account_adventures WHERE account_id=$1 FOR UPDATE
`

type LockAdventureRow struct {
	Name       string
	Level      int32
	Experience int64
	CreatedAt  time.Time
	Data       json.RawMessage
}

func (q *Queries) LockAdventure(ctx context.Context, accountID int64) (LockAdventureRow, error) {
	row := q.db.QueryRow(ctx, lockAdventure, accountID)
	var i LockAdventureRow
	err := row.Scan(
		&i.Name,
		&i.Level,
		&i.Experience,
		&i.CreatedAt,
		&i.Data,
	)
	return i, err
}

const lockBleedingMineRewards = `-- name: LockBleedingMineRewards :one
SELECT state FROM account_bleeding_mine_rewards WHERE account_id=$1 FOR UPDATE
`

func (q *Queries) LockBleedingMineRewards(ctx context.Context, accountID int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, lockBleedingMineRewards, accountID)
	var state json.RawMessage
	err := row.Scan(&state)
	return state, err
}

const reserveFavorGift = `-- name: ReserveFavorGift :one
INSERT INTO npc_favor(character_id,npc_id,point,daily_count,last_gift_day)
VALUES($1,$2,0,1,$3::text::date)
ON CONFLICT(character_id,npc_id) DO UPDATE SET
daily_count=CASE WHEN EXCLUDED.last_gift_day>npc_favor.last_gift_day OR npc_favor.last_gift_day IS NULL THEN 1 ELSE npc_favor.daily_count+1 END,
last_gift_day=GREATEST(EXCLUDED.last_gift_day,npc_favor.last_gift_day),point=npc_favor.point,updated_at=now()
RETURNING point,daily_count,last_gift_day::text
`

type ReserveFavorGiftParams struct {
	CharacterID int64
	NpcID       int64
	Day         string
}

type ReserveFavorGiftRow struct {
	Point       int64
	DailyCount  int32
	LastGiftDay string
}

func (q *Queries) ReserveFavorGift(ctx context.Context, arg ReserveFavorGiftParams) (ReserveFavorGiftRow, error) {
	row := q.db.QueryRow(ctx, reserveFavorGift, arg.CharacterID, arg.NpcID, arg.Day)
	var i ReserveFavorGiftRow
	err := row.Scan(&i.Point, &i.DailyCount, &i.LastGiftDay)
	return i, err
}

const saveAdventure = `-- name: SaveAdventure :exec
UPDATE account_adventures SET level=$1::bigint,experience=$2,data=$3
WHERE account_id=$4
`

type SaveAdventureParams struct {
	Level      int64
	Experience int64
	Data       json.RawMessage
	AccountID  int64
}

func (q *Queries) SaveAdventure(ctx context.Context, arg SaveAdventureParams) error {
	_, err := q.db.Exec(ctx, saveAdventure,
		arg.Level,
		arg.Experience,
		arg.Data,
		arg.AccountID,
	)
	return err
}

const saveBleedingMineRewards = `-- name: SaveBleedingMineRewards :exec
UPDATE account_bleeding_mine_rewards SET state=$1,updated_at=now() WHERE account_id=$2
`

type SaveBleedingMineRewardsParams struct {
	State     json.RawMessage
	AccountID int64
}

func (q *Queries) SaveBleedingMineRewards(ctx context.Context, arg SaveBleedingMineRewardsParams) error {
	_, err := q.db.Exec(ctx, saveBleedingMineRewards, arg.State, arg.AccountID)
	return err
}

const saveBleedingMineTeam = `-- name: SaveBleedingMineTeam :exec
INSERT INTO account_bleeding_mine_teams(account_id,team,members)
VALUES($1,$2,$3)
ON CONFLICT(account_id,team) DO UPDATE SET members=EXCLUDED.members,updated_at=now()
`

type SaveBleedingMineTeamParams struct {
	AccountID int64
	Team      int32
	Members   []int64
}

func (q *Queries) SaveBleedingMineTeam(ctx context.Context, arg SaveBleedingMineTeamParams) error {
	_, err := q.db.Exec(ctx, saveBleedingMineTeam, arg.AccountID, arg.Team, arg.Members)
	return err
}

const saveFavorPoint = `-- name: SaveFavorPoint :exec
UPDATE npc_favor SET point=$1,updated_at=now()
WHERE character_id=$2 AND npc_id=$3
`

type SaveFavorPointParams struct {
	Point       int64
	CharacterID int64
	NpcID       int64
}

func (q *Queries) SaveFavorPoint(ctx context.Context, arg SaveFavorPointParams) error {
	_, err := q.db.Exec(ctx, saveFavorPoint, arg.Point, arg.CharacterID, arg.NpcID)
	return err
}
