// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commerce.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountCera = `-- name: AccountCera :one
SELECT coalesce((SELECT cera FROM account_currency WHERE account_id=$1),0)::bigint
`

func (q *Queries) AccountCera(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, accountCera, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const activePremiums = `-- name: ActivePremiums :many
SELECT premium_type,end_time FROM account_premiums
WHERE account_id=$1 AND end_time>$2::bigint ORDER BY premium_type
`

type ActivePremiumsParams struct {
	AccountID int64
	NowEpoch  int64
}

type ActivePremiumsRow struct {
	PremiumType int16
	EndTime     int64
}

func (q *Queries) ActivePremiums(ctx context.Context, arg ActivePremiumsParams) ([]ActivePremiumsRow, error) {
	rows, err := q.db.Query(ctx, activePremiums, arg.AccountID, arg.NowEpoch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivePremiumsRow
	for rows.Next() {
		var i ActivePremiumsRow
		if err := rows.Scan(&i.PremiumType, &i.EndTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adjustAccountCurrency = `-- name: AdjustAccountCurrency :one
UPDATE account_currency SET cera=cera+$1::bigint,updated_at=now()
WHERE account_id=$2 RETURNING cera
`

type AdjustAccountCurrencyParams struct {
	Adjustment int64
	AccountID  int64
}

func (q *Queries) AdjustAccountCurrency(ctx context.Context, arg AdjustAccountCurrencyParams) (int64, error) {
	row := q.db.QueryRow(ctx, adjustAccountCurrency, arg.Adjustment, arg.AccountID)
	var cera int64
	err := row.Scan(&cera)
	return cera, err
}

const adminGrantReceipt = `-- name: AdminGrantReceipt :one
SELECT receipt FROM admin_grants WHERE grant_id=$1
`

func (q *Queries) AdminGrantReceipt(ctx context.Context, grantID string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, adminGrantReceipt, grantID)
	var receipt json.RawMessage
	err := row.Scan(&receipt)
	return receipt, err
}

const cashInventory = `-- name: CashInventory :many
SELECT i.id,i.product,i.template,i.amount FROM cash_inventory i JOIN characters c ON c.id=i.character_id
WHERE i.account_id=$1 AND i.character_id=$2
AND c.account_id=$1 AND c.deleted_at IS NULL AND i.claimed_at IS NULL ORDER BY i.id
`

type CashInventoryParams struct {
	AccountID   int64
	CharacterID int64
}

type CashInventoryRow struct {
	ID       int64
	Product  int64
	Template int64
	Amount   int64
}

func (q *Queries) CashInventory(ctx context.Context, arg CashInventoryParams) ([]CashInventoryRow, error) {
	rows, err := q.db.Query(ctx, cashInventory, arg.AccountID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashInventoryRow
	for rows.Next() {
		var i CashInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Product,
			&i.Template,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cashOrderReceipt = `-- name: CashOrderReceipt :one
SELECT digest,receipt FROM cash_orders WHERE account_id=$1 AND order_key=$2
`

type CashOrderReceiptParams struct {
	AccountID int64
	OrderKey  string
}

type CashOrderReceiptRow struct {
	Digest  string
	Receipt json.RawMessage
}

func (q *Queries) CashOrderReceipt(ctx context.Context, arg CashOrderReceiptParams) (CashOrderReceiptRow, error) {
	row := q.db.QueryRow(ctx, cashOrderReceipt, arg.AccountID, arg.OrderKey)
	var i CashOrderReceiptRow
	err := row.Scan(&i.Digest, &i.Receipt)
	return i, err
}

const cashOrderVaultSpace = `-- name: CashOrderVaultSpace :one
SELECT coalesce((request->>'vault_space')::integer,0)::integer AS vault_space FROM cash_orders
WHERE account_id=$1 AND character_id=$2 AND order_key=$3
`

type CashOrderVaultSpaceParams struct {
	AccountID   int64
	CharacterID int64
	OrderKey    string
}

func (q *Queries) CashOrderVaultSpace(ctx context.Context, arg CashOrderVaultSpaceParams) (int32, error) {
	row := q.db.QueryRow(ctx, cashOrderVaultSpace, arg.AccountID, arg.CharacterID, arg.OrderKey)
	var vault_space int32
	err := row.Scan(&vault_space)
	return vault_space, err
}

const claimAdminGrant = `-- name: ClaimAdminGrant :execrows
INSERT INTO admin_grants(grant_id,account_id,character_id,request,receipt,operator,reason)
VALUES($1,$2,$3::bigint,
$4,'{}'::jsonb,$5,$6) ON CONFLICT(grant_id) DO NOTHING
`

type ClaimAdminGrantParams struct {
	GrantID     string
	AccountID   int64
	CharacterID pgtype.Int8
	Request     json.RawMessage
	Operator    string
	Reason      string
}

func (q *Queries) ClaimAdminGrant(ctx context.Context, arg ClaimAdminGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimAdminGrant,
		arg.GrantID,
		arg.AccountID,
		arg.CharacterID,
		arg.Request,
		arg.Operator,
		arg.Reason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const coinItemMigrationCandidates = `-- name: CoinItemMigrationCandidates :many
SELECT id,state FROM characters WHERE state->'inventory'->'items' @> '[{"Template": 1}]'
`

type CoinItemMigrationCandidatesRow struct {
	ID    int64
	State json.RawMessage
}

func (q *Queries) CoinItemMigrationCandidates(ctx context.Context) ([]CoinItemMigrationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, coinItemMigrationCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoinItemMigrationCandidatesRow
	for rows.Next() {
		var i CoinItemMigrationCandidatesRow
		if err := rows.Scan(&i.ID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAccountShopPurchases = `-- name: CountAccountShopPurchases :one
SELECT count(*) FROM character_shop_purchases WHERE account_id=$1
AND npc_id=$2 AND template=$3 AND bought_at>=$4::timestamptz
`

type CountAccountShopPurchasesParams struct {
	AccountID   int64
	NpcID       int32
	Template    int32
	WindowStart time.Time
}

func (q *Queries) CountAccountShopPurchases(ctx context.Context, arg CountAccountShopPurchasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountShopPurchases,
		arg.AccountID,
		arg.NpcID,
		arg.Template,
		arg.WindowStart,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCharacterShopPurchases = `-- name: CountCharacterShopPurchases :one
SELECT count(*) FROM character_shop_purchases WHERE character_id=$1
AND npc_id=$2 AND template=$3 AND bought_at>=$4::timestamptz
`

type CountCharacterShopPurchasesParams struct {
	CharacterID int64
	NpcID       int32
	Template    int32
	WindowStart time.Time
}

func (q *Queries) CountCharacterShopPurchases(ctx context.Context, arg CountCharacterShopPurchasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCharacterShopPurchases,
		arg.CharacterID,
		arg.NpcID,
		arg.Template,
		arg.WindowStart,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureAccountCurrency = `-- name: EnsureAccountCurrency :exec
INSERT INTO account_currency(account_id,cera) VALUES($1,0) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureAccountCurrency(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, ensureAccountCurrency, accountID)
	return err
}

const grantHistory = `-- name: GrantHistory :many
SELECT grant_id,coalesce(character_id,0)::bigint AS character_id,operator,reason,request,created_at
FROM admin_grants WHERE account_id=$1 ORDER BY created_at DESC LIMIT $2::integer
`

type GrantHistoryParams struct {
	AccountID  int64
	MaxEntries int32
}

type GrantHistoryRow struct {
	GrantID     string
	CharacterID int64
	Operator    string
	Reason      string
	Request     json.RawMessage
	CreatedAt   time.Time
}

func (q *Queries) GrantHistory(ctx context.Context, arg GrantHistoryParams) ([]GrantHistoryRow, error) {
	rows, err := q.db.Query(ctx, grantHistory, arg.AccountID, arg.MaxEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrantHistoryRow
	for rows.Next() {
		var i GrantHistoryRow
		if err := rows.Scan(
			&i.GrantID,
			&i.CharacterID,
			&i.Operator,
			&i.Reason,
			&i.Request,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasActivePremium = `-- name: HasActivePremium :one
SELECT EXISTS(SELECT 1 FROM account_premiums WHERE account_id=$1
AND premium_type=$2 AND end_time>$3::bigint)
`

type HasActivePremiumParams struct {
	AccountID   int64
	PremiumType int16
	NowEpoch    int64
}

func (q *Queries) HasActivePremium(ctx context.Context, arg HasActivePremiumParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActivePremium, arg.AccountID, arg.PremiumType, arg.NowEpoch)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockAccountCurrency = `-- name: LockAccountCurrency :one
SELECT cera FROM account_currency WHERE account_id=$1 FOR UPDATE
`

func (q *Queries) LockAccountCurrency(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockAccountCurrency, accountID)
	var cera int64
	err := row.Scan(&cera)
	return cera, err
}

const lockPremiumExpiry = `-- name: LockPremiumExpiry :one
SELECT end_time FROM account_premiums WHERE account_id=$1
AND premium_type=$2 FOR UPDATE
`

type LockPremiumExpiryParams struct {
	AccountID   int64
	PremiumType int16
}

func (q *Queries) LockPremiumExpiry(ctx context.Context, arg LockPremiumExpiryParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockPremiumExpiry, arg.AccountID, arg.PremiumType)
	var end_time int64
	err := row.Scan(&end_time)
	return end_time, err
}

const markCashOrderDelivered = `-- name: MarkCashOrderDelivered :exec
UPDATE cash_inventory SET claimed_at=now() WHERE account_id=$1 AND order_key=$2
`

type MarkCashOrderDeliveredParams struct {
	AccountID int64
	OrderKey  string
}

func (q *Queries) MarkCashOrderDelivered(ctx context.Context, arg MarkCashOrderDeliveredParams) error {
	_, err := q.db.Exec(ctx, markCashOrderDelivered, arg.AccountID, arg.OrderKey)
	return err
}

const packagePlaceholderMigrationCandidates = `-- name: PackagePlaceholderMigrationCandidates :many
SELECT id,state FROM characters WHERE state->'inventory'->'items' @> '[{"Template": 590722921}]'
OR state->'inventory'->'items' @> '[{"Template": 590722922}]'
`

type PackagePlaceholderMigrationCandidatesRow struct {
	ID    int64
	State json.RawMessage
}

func (q *Queries) PackagePlaceholderMigrationCandidates(ctx context.Context) ([]PackagePlaceholderMigrationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, packagePlaceholderMigrationCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PackagePlaceholderMigrationCandidatesRow
	for rows.Next() {
		var i PackagePlaceholderMigrationCandidatesRow
		if err := rows.Scan(&i.ID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCashInventory = `-- name: RecordCashInventory :one
INSERT INTO cash_inventory(account_id,character_id,order_key,line_index,product,template,amount)
VALUES($1,$2,$3,$4,
$5,$6,$7) RETURNING id
`

type RecordCashInventoryParams struct {
	AccountID   int64
	CharacterID int64
	OrderKey    string
	LineIndex   int32
	Product     int64
	Template    int64
	Amount      int64
}

func (q *Queries) RecordCashInventory(ctx context.Context, arg RecordCashInventoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordCashInventory,
		arg.AccountID,
		arg.CharacterID,
		arg.OrderKey,
		arg.LineIndex,
		arg.Product,
		arg.Template,
		arg.Amount,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const recordCashOrder = `-- name: RecordCashOrder :exec
INSERT INTO cash_orders(account_id,order_key,character_id,digest,request,receipt)
VALUES($1,$2,$3,$4,$5,'{}')
`

type RecordCashOrderParams struct {
	AccountID   int64
	OrderKey    string
	CharacterID int64
	Digest      string
	Request     json.RawMessage
}

func (q *Queries) RecordCashOrder(ctx context.Context, arg RecordCashOrderParams) error {
	_, err := q.db.Exec(ctx, recordCashOrder,
		arg.AccountID,
		arg.OrderKey,
		arg.CharacterID,
		arg.Digest,
		arg.Request,
	)
	return err
}

const recordShopPurchase = `-- name: RecordShopPurchase :exec
INSERT INTO character_shop_purchases(account_id,character_id,npc_id,template)
VALUES($1,$2,$3,$4)
`

type RecordShopPurchaseParams struct {
	AccountID   int64
	CharacterID int64
	NpcID       int32
	Template    int32
}

func (q *Queries) RecordShopPurchase(ctx context.Context, arg RecordShopPurchaseParams) error {
	_, err := q.db.Exec(ctx, recordShopPurchase,
		arg.AccountID,
		arg.CharacterID,
		arg.NpcID,
		arg.Template,
	)
	return err
}

const saveAccountCurrency = `-- name: SaveAccountCurrency :exec
UPDATE account_currency SET cera=$1,updated_at=now() WHERE account_id=$2
`

type SaveAccountCurrencyParams struct {
	Cera      int64
	AccountID int64
}

func (q *Queries) SaveAccountCurrency(ctx context.Context, arg SaveAccountCurrencyParams) error {
	_, err := q.db.Exec(ctx, saveAccountCurrency, arg.Cera, arg.AccountID)
	return err
}

const saveAdminGrantReceipt = `-- name: SaveAdminGrantReceipt :exec
UPDATE admin_grants SET receipt=$1 WHERE grant_id=$2
`

type SaveAdminGrantReceiptParams struct {
	Receipt json.RawMessage
	GrantID string
}

func (q *Queries) SaveAdminGrantReceipt(ctx context.Context, arg SaveAdminGrantReceiptParams) error {
	_, err := q.db.Exec(ctx, saveAdminGrantReceipt, arg.Receipt, arg.GrantID)
	return err
}

const saveCashOrderReceipt = `-- name: SaveCashOrderReceipt :exec
UPDATE cash_orders SET receipt=$1 WHERE account_id=$2 AND order_key=$3
`

type SaveCashOrderReceiptParams struct {
	Receipt   json.RawMessage
	AccountID int64
	OrderKey  string
}

func (q *Queries) SaveCashOrderReceipt(ctx context.Context, arg SaveCashOrderReceiptParams) error {
	_, err := q.db.Exec(ctx, saveCashOrderReceipt, arg.Receipt, arg.AccountID, arg.OrderKey)
	return err
}

const savePremiumExpiry = `-- name: SavePremiumExpiry :exec
INSERT INTO account_premiums(account_id,premium_type,end_time,updated_at)
VALUES($1,$2,$3,now())
ON CONFLICT(account_id,premium_type) DO UPDATE SET end_time=EXCLUDED.end_time,updated_at=now()
`

type SavePremiumExpiryParams struct {
	AccountID   int64
	PremiumType int16
	EndTime     int64
}

func (q *Queries) SavePremiumExpiry(ctx context.Context, arg SavePremiumExpiryParams) error {
	_, err := q.db.Exec(ctx, savePremiumExpiry, arg.AccountID, arg.PremiumType, arg.EndTime)
	return err
}
