// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
//
// Hand-adapted on 2026-10-05: the PostgreSQL entry was removed from sqlc.yaml when
// PostgreSQL support was dropped (owner decision, see root AGENTS.md §0.6), so this
// package is no longer regenerated. It is kept as the internal query/type layer the
// SQLite adapter is written against (queryset.go asserts *Queries satisfies querySet,
// and sqlite_adapter_gen.go converts its parameter/row types).
//
// Only the driver plumbing moved: DBTX speaks database/sql, and the sibling *.sql.go
// bodies call its *Context methods and take RowsAffected's second return value. Their
// SQL text, parameter/row types and control flow are otherwise untouched.

package sqlcgen

import (
	"context"
	"database/sql"
)

// DBTX is the driver surface the generated queries call. database/sql's *sql.DB and
// *sql.Tx both satisfy it, which is what the SQLite engine hands over.
type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
