// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const blackPurgatoryEntryCounts = `-- name: BlackPurgatoryEntryCounts :one
SELECT count(*) FILTER(WHERE created_at >= $1::timestamptz) AS daily,
count(*) AS weekly FROM character_events
WHERE character_id=$2 AND model='black-purgatory-entry-v1'
AND created_at >= $3::timestamptz AND outcome->>'stage' IN ('entered','cleared')
`

type BlackPurgatoryEntryCountsParams struct {
	DayStart    time.Time
	CharacterID int64
	WeekStart   time.Time
}

type BlackPurgatoryEntryCountsRow struct {
	Daily  int64
	Weekly int64
}

func (q *Queries) BlackPurgatoryEntryCounts(ctx context.Context, arg BlackPurgatoryEntryCountsParams) (BlackPurgatoryEntryCountsRow, error) {
	row := q.db.QueryRowContext(ctx, blackPurgatoryEntryCounts, arg.DayStart, arg.CharacterID, arg.WeekStart)
	var i BlackPurgatoryEntryCountsRow
	err := row.Scan(&i.Daily, &i.Weekly)
	return i, err
}

const blackPurgatoryEntryStage = `-- name: BlackPurgatoryEntryStage :one
SELECT (outcome->>'stage')::text AS stage FROM character_events
WHERE character_id=$1 AND event_key=$2 AND model='black-purgatory-entry-v1'
`

type BlackPurgatoryEntryStageParams struct {
	CharacterID int64
	EventKey    string
}

func (q *Queries) BlackPurgatoryEntryStage(ctx context.Context, arg BlackPurgatoryEntryStageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, blackPurgatoryEntryStage, arg.CharacterID, arg.EventKey)
	var stage string
	err := row.Scan(&stage)
	return stage, err
}

const characterEventStage = `-- name: CharacterEventStage :one
SELECT model,(outcome->>'stage')::text AS stage FROM character_events
WHERE character_id=$1 AND event_key=$2
`

type CharacterEventStageParams struct {
	CharacterID int64
	EventKey    string
}

type CharacterEventStageRow struct {
	Model string
	Stage string
}

func (q *Queries) CharacterEventStage(ctx context.Context, arg CharacterEventStageParams) (CharacterEventStageRow, error) {
	row := q.db.QueryRowContext(ctx, characterEventStage, arg.CharacterID, arg.EventKey)
	var i CharacterEventStageRow
	err := row.Scan(&i.Model, &i.Stage)
	return i, err
}

const normalizeCharacterIdentity = `-- name: NormalizeCharacterIdentity :execrows
UPDATE characters SET config_version=$1::text WHERE config_version IS DISTINCT FROM $1::text
`

func (q *Queries) NormalizeCharacterIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeCharacterIdentity, identity)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const normalizeEventIdentity = `-- name: NormalizeEventIdentity :execrows
UPDATE character_events SET config_version=$1::text WHERE config_version IS DISTINCT FROM $1::text
`

func (q *Queries) NormalizeEventIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeEventIdentity, identity)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const normalizeMapClearIdentity = `-- name: NormalizeMapClearIdentity :execrows
UPDATE character_map_clears SET source_version=$1::text WHERE source_version IS DISTINCT FROM $1::text
`

func (q *Queries) NormalizeMapClearIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeMapClearIdentity, identity)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const normalizeQuestIdentity = `-- name: NormalizeQuestIdentity :execrows
UPDATE character_quests SET config_version=$1::text WHERE config_version IS DISTINCT FROM $1::text
`

func (q *Queries) NormalizeQuestIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeQuestIdentity, identity)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const normalizeQuestRewardIdentity = `-- name: NormalizeQuestRewardIdentity :execrows
UPDATE character_quest_rewards SET source_version=$1::text WHERE source_version IS DISTINCT FROM $1::text
`

func (q *Queries) NormalizeQuestRewardIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeQuestRewardIdentity, identity)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const normalizeWorldIdentity = `-- name: NormalizeWorldIdentity :execrows
UPDATE character_world SET config_version=$1::text WHERE config_version IS DISTINCT FROM $1::text
`

func (q *Queries) NormalizeWorldIdentity(ctx context.Context, identity string) (int64, error) {
	result, err := q.db.ExecContext(ctx, normalizeWorldIdentity, identity)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const pendingBlackPurgatoryRewards = `-- name: PendingBlackPurgatoryRewards :many
SELECT e.outcome FROM character_events e JOIN characters c ON c.id=e.character_id
WHERE c.account_id=$1 AND c.id=$2 AND e.model=$3
AND e.event_key LIKE 'cardplan:%'
AND NOT EXISTS(SELECT 1 FROM character_events g WHERE g.character_id=e.character_id
AND g.event_key='black-purgatory-recovered:'||substr(e.event_key,10)) ORDER BY e.created_at LIMIT 16
`

type PendingBlackPurgatoryRewardsParams struct {
	AccountID   int64
	CharacterID int64
	Model       string
}

func (q *Queries) PendingBlackPurgatoryRewards(ctx context.Context, arg PendingBlackPurgatoryRewardsParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, pendingBlackPurgatoryRewards, arg.AccountID, arg.CharacterID, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []json.RawMessage
	for rows.Next() {
		var outcome json.RawMessage
		if err := rows.Scan(&outcome); err != nil {
			return nil, err
		}
		items = append(items, outcome)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundPendingBlackPurgatoryEntries = `-- name: RefundPendingBlackPurgatoryEntries :exec
UPDATE character_events SET outcome=jsonb_set(outcome,'{stage}','"refunded"')
WHERE character_id=$1 AND model='black-purgatory-entry-v1' AND outcome->>'stage'='entered'
`

func (q *Queries) RefundPendingBlackPurgatoryEntries(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, refundPendingBlackPurgatoryEntries, characterID)
	return err
}

const setCharacterEventStage = `-- name: SetCharacterEventStage :exec
UPDATE character_events SET outcome=jsonb_set(outcome,'{stage}',to_jsonb($1::text))
WHERE character_id=$2 AND event_key=$3
`

type SetCharacterEventStageParams struct {
	Stage       string
	CharacterID int64
	EventKey    string
}

func (q *Queries) SetCharacterEventStage(ctx context.Context, arg SetCharacterEventStageParams) error {
	_, err := q.db.ExecContext(ctx, setCharacterEventStage, arg.Stage, arg.CharacterID, arg.EventKey)
	return err
}

const storedCharacterEvent = `-- name: StoredCharacterEvent :one
SELECT model,outcome FROM character_events
WHERE character_id=$1 AND event_key=$2
`

type StoredCharacterEventParams struct {
	CharacterID int64
	EventKey    string
}

type StoredCharacterEventRow struct {
	Model   string
	Outcome json.RawMessage
}

func (q *Queries) StoredCharacterEvent(ctx context.Context, arg StoredCharacterEventParams) (StoredCharacterEventRow, error) {
	row := q.db.QueryRowContext(ctx, storedCharacterEvent, arg.CharacterID, arg.EventKey)
	var i StoredCharacterEventRow
	err := row.Scan(&i.Model, &i.Outcome)
	return i, err
}
