// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixtures.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const fixtureAccountCurrency = `-- name: FixtureAccountCurrency :exec
INSERT INTO account_currency(account_id,cera) VALUES($1,$2)
ON CONFLICT(account_id) DO UPDATE SET cera=EXCLUDED.cera
`

type FixtureAccountCurrencyParams struct {
	AccountID int64
	Cera      int64
}

func (q *Queries) FixtureAccountCurrency(ctx context.Context, arg FixtureAccountCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, fixtureAccountCurrency, arg.AccountID, arg.Cera)
	return err
}

const fixtureArchivedCharacter = `-- name: FixtureArchivedCharacter :one
SELECT (deleted_at IS NOT NULL)::boolean AS archived,state FROM characters WHERE id=$1
`

type FixtureArchivedCharacterRow struct {
	Archived bool
	State    json.RawMessage
}

func (q *Queries) FixtureArchivedCharacter(ctx context.Context, characterID int64) (FixtureArchivedCharacterRow, error) {
	row := q.db.QueryRowContext(ctx, fixtureArchivedCharacter, characterID)
	var i FixtureArchivedCharacterRow
	err := row.Scan(&i.Archived, &i.State)
	return i, err
}

const fixtureCashInventoryCount = `-- name: FixtureCashInventoryCount :one
SELECT count(*) FROM cash_inventory WHERE account_id=$1
AND ($2::integer=0
 OR ($2::integer=1 AND claimed_at IS NULL)
 OR ($2::integer=2 AND claimed_at IS NOT NULL))
AND ($3::bigint=0 OR template=$3::bigint)
AND ($4::integer=0 OR amount=$4::integer)
`

type FixtureCashInventoryCountParams struct {
	AccountID  int64
	ClaimState int32
	Template   int64
	Amount     int32
}

func (q *Queries) FixtureCashInventoryCount(ctx context.Context, arg FixtureCashInventoryCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureCashInventoryCount,
		arg.AccountID,
		arg.ClaimState,
		arg.Template,
		arg.Amount,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureCashOrderCount = `-- name: FixtureCashOrderCount :one
SELECT count(*) FROM cash_orders WHERE account_id=$1
`

func (q *Queries) FixtureCashOrderCount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureCashOrderCount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureCashOrderSource = `-- name: FixtureCashOrderSource :one
SELECT coalesce(request->>'source','')::text FROM cash_orders
WHERE account_id=$1 AND order_key=$2
`

type FixtureCashOrderSourceParams struct {
	AccountID int64
	OrderKey  string
}

func (q *Queries) FixtureCashOrderSource(ctx context.Context, arg FixtureCashOrderSourceParams) (string, error) {
	row := q.db.QueryRowContext(ctx, fixtureCashOrderSource, arg.AccountID, arg.OrderKey)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const fixtureCharacterSnapshot = `-- name: FixtureCharacterSnapshot :exec
UPDATE characters SET state=$1,config_version=$2
WHERE id=$3
`

type FixtureCharacterSnapshotParams struct {
	State         json.RawMessage
	ConfigVersion string
	CharacterID   int64
}

func (q *Queries) FixtureCharacterSnapshot(ctx context.Context, arg FixtureCharacterSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, fixtureCharacterSnapshot, arg.State, arg.ConfigVersion, arg.CharacterID)
	return err
}

const fixtureCharacterState = `-- name: FixtureCharacterState :one
SELECT state FROM characters WHERE id=$1
`

func (q *Queries) FixtureCharacterState(ctx context.Context, characterID int64) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, fixtureCharacterState, characterID)
	var state json.RawMessage
	err := row.Scan(&state)
	return state, err
}

const fixtureCompletedQuest = `-- name: FixtureCompletedQuest :exec
INSERT INTO character_quests(character_id,quest_id,status,progress,config_version,progress_model)
VALUES($1,$2::integer,'completed',0,$3,$4)
`

type FixtureCompletedQuestParams struct {
	CharacterID   int64
	QuestID       int32
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) FixtureCompletedQuest(ctx context.Context, arg FixtureCompletedQuestParams) error {
	_, err := q.db.ExecContext(ctx, fixtureCompletedQuest,
		arg.CharacterID,
		arg.QuestID,
		arg.ConfigVersion,
		arg.ProgressModel,
	)
	return err
}

const fixtureDeleteBirth = `-- name: FixtureDeleteBirth :exec
DELETE FROM character_birth WHERE character_id=$1
`

func (q *Queries) FixtureDeleteBirth(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, fixtureDeleteBirth, characterID)
	return err
}

const fixtureEventCount = `-- name: FixtureEventCount :one
SELECT count(*) FROM character_events WHERE ($1::bigint=0 OR character_id=$1::bigint)
`

func (q *Queries) FixtureEventCount(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureEventCount, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureFatigueRoomStats = `-- name: FixtureFatigueRoomStats :one
SELECT count(*) AS count,coalesce(sum(cost),0)::bigint AS cost
FROM character_fatigue_rooms WHERE character_id=$1
`

type FixtureFatigueRoomStatsRow struct {
	Count int64
	Cost  int64
}

func (q *Queries) FixtureFatigueRoomStats(ctx context.Context, characterID int64) (FixtureFatigueRoomStatsRow, error) {
	row := q.db.QueryRowContext(ctx, fixtureFatigueRoomStats, characterID)
	var i FixtureFatigueRoomStatsRow
	err := row.Scan(&i.Count, &i.Cost)
	return i, err
}

const fixtureFatigueUsage = `-- name: FixtureFatigueUsage :exec
UPDATE character_fatigue SET used=$1::integer,used_max=$2::integer
WHERE character_id=$3
`

type FixtureFatigueUsageParams struct {
	Used        int32
	UsedMax     int32
	CharacterID int64
}

func (q *Queries) FixtureFatigueUsage(ctx context.Context, arg FixtureFatigueUsageParams) error {
	_, err := q.db.ExecContext(ctx, fixtureFatigueUsage, arg.Used, arg.UsedMax, arg.CharacterID)
	return err
}

const fixtureFatigueUsed = `-- name: FixtureFatigueUsed :exec
UPDATE character_fatigue SET used=$1::integer WHERE character_id=$2
`

type FixtureFatigueUsedParams struct {
	Used        int32
	CharacterID int64
}

func (q *Queries) FixtureFatigueUsed(ctx context.Context, arg FixtureFatigueUsedParams) error {
	_, err := q.db.ExecContext(ctx, fixtureFatigueUsed, arg.Used, arg.CharacterID)
	return err
}

const fixtureInventoryItems = `-- name: FixtureInventoryItems :exec
UPDATE characters SET state=jsonb_set(state,'{inventory,items}',$1::jsonb)
WHERE id=$2
`

type FixtureInventoryItemsParams struct {
	Items       json.RawMessage
	CharacterID int64
}

func (q *Queries) FixtureInventoryItems(ctx context.Context, arg FixtureInventoryItemsParams) error {
	_, err := q.db.ExecContext(ctx, fixtureInventoryItems, arg.Items, arg.CharacterID)
	return err
}

const fixtureLegacyQuest = `-- name: FixtureLegacyQuest :exec
UPDATE character_quests SET progress=0,progress_model='legacy-zero'
WHERE character_id=$1 AND quest_id=$2::integer
`

type FixtureLegacyQuestParams struct {
	CharacterID int64
	QuestID     int32
}

func (q *Queries) FixtureLegacyQuest(ctx context.Context, arg FixtureLegacyQuestParams) error {
	_, err := q.db.ExecContext(ctx, fixtureLegacyQuest, arg.CharacterID, arg.QuestID)
	return err
}

const fixtureMapClearCount = `-- name: FixtureMapClearCount :one
SELECT count(*) FROM character_map_clears WHERE character_id=$1 AND run_id=$2
`

type FixtureMapClearCountParams struct {
	CharacterID int64
	RunID       string
}

func (q *Queries) FixtureMapClearCount(ctx context.Context, arg FixtureMapClearCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureMapClearCount, arg.CharacterID, arg.RunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureMergeCharacterFields = `-- name: FixtureMergeCharacterFields :exec
UPDATE characters SET state=state||$1::jsonb WHERE id=$2
`

type FixtureMergeCharacterFieldsParams struct {
	Fields      json.RawMessage
	CharacterID int64
}

func (q *Queries) FixtureMergeCharacterFields(ctx context.Context, arg FixtureMergeCharacterFieldsParams) error {
	_, err := q.db.ExecContext(ctx, fixtureMergeCharacterFields, arg.Fields, arg.CharacterID)
	return err
}

const fixtureMonsterEventCount = `-- name: FixtureMonsterEventCount :one
SELECT count(*) FROM character_events
WHERE character_id=$1 AND event_key LIKE 'monster:%'
`

func (q *Queries) FixtureMonsterEventCount(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureMonsterEventCount, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureQuestCount = `-- name: FixtureQuestCount :one
SELECT count(*) FROM character_quests
WHERE ($1::bigint=0 OR character_id=$1::bigint)
`

func (q *Queries) FixtureQuestCount(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureQuestCount, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureQuestProgress = `-- name: FixtureQuestProgress :exec
UPDATE character_quests SET progress=$1::bigint
WHERE character_id=$2 AND quest_id=$3::integer
`

type FixtureQuestProgressParams struct {
	Progress    int64
	CharacterID int64
	QuestID     int32
}

func (q *Queries) FixtureQuestProgress(ctx context.Context, arg FixtureQuestProgressParams) error {
	_, err := q.db.ExecContext(ctx, fixtureQuestProgress, arg.Progress, arg.CharacterID, arg.QuestID)
	return err
}

const fixtureQuestRecord = `-- name: FixtureQuestRecord :one
SELECT status,progress_model FROM character_quests
WHERE character_id=$1 AND quest_id=$2::integer
`

type FixtureQuestRecordParams struct {
	CharacterID int64
	QuestID     int32
}

type FixtureQuestRecordRow struct {
	Status        string
	ProgressModel string
}

func (q *Queries) FixtureQuestRecord(ctx context.Context, arg FixtureQuestRecordParams) (FixtureQuestRecordRow, error) {
	row := q.db.QueryRowContext(ctx, fixtureQuestRecord, arg.CharacterID, arg.QuestID)
	var i FixtureQuestRecordRow
	err := row.Scan(&i.Status, &i.ProgressModel)
	return i, err
}

const fixtureQuestRecordSeed = `-- name: FixtureQuestRecordSeed :exec
INSERT INTO character_quests(character_id,quest_id,status,config_version,progress_model)
VALUES($1,$2::integer,$3,$4,$5)
`

type FixtureQuestRecordSeedParams struct {
	CharacterID   int64
	QuestID       int32
	Status        string
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) FixtureQuestRecordSeed(ctx context.Context, arg FixtureQuestRecordSeedParams) error {
	_, err := q.db.ExecContext(ctx, fixtureQuestRecordSeed,
		arg.CharacterID,
		arg.QuestID,
		arg.Status,
		arg.ConfigVersion,
		arg.ProgressModel,
	)
	return err
}

const fixtureQuestRepairCount = `-- name: FixtureQuestRepairCount :one
SELECT count(*) FROM character_quest_repairs WHERE character_id=$1
`

func (q *Queries) FixtureQuestRepairCount(ctx context.Context, characterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureQuestRepairCount, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureQuestRewardCount = `-- name: FixtureQuestRewardCount :one
SELECT count(*) FROM character_quest_rewards WHERE character_id=$1
AND ($2::integer=0 OR quest_id=$2::integer)
`

type FixtureQuestRewardCountParams struct {
	CharacterID int64
	QuestID     int32
}

func (q *Queries) FixtureQuestRewardCount(ctx context.Context, arg FixtureQuestRewardCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, fixtureQuestRewardCount, arg.CharacterID, arg.QuestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fixtureReadCharacterSnapshot = `-- name: FixtureReadCharacterSnapshot :one
SELECT state,config_version FROM characters WHERE id=$1
`

type FixtureReadCharacterSnapshotRow struct {
	State         json.RawMessage
	ConfigVersion string
}

func (q *Queries) FixtureReadCharacterSnapshot(ctx context.Context, characterID int64) (FixtureReadCharacterSnapshotRow, error) {
	row := q.db.QueryRowContext(ctx, fixtureReadCharacterSnapshot, characterID)
	var i FixtureReadCharacterSnapshotRow
	err := row.Scan(&i.State, &i.ConfigVersion)
	return i, err
}

const fixtureSchema = `-- name: FixtureSchema :one
SELECT current_schema()::text
`

// These queries are used only by the isolated charactercheck fixture.
func (q *Queries) FixtureSchema(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, fixtureSchema)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const fixtureVaultItems = `-- name: FixtureVaultItems :exec
UPDATE character_vaults SET items=$1 WHERE character_id=$2
`

type FixtureVaultItemsParams struct {
	Items       json.RawMessage
	CharacterID int64
}

func (q *Queries) FixtureVaultItems(ctx context.Context, arg FixtureVaultItemsParams) error {
	_, err := q.db.ExecContext(ctx, fixtureVaultItems, arg.Items, arg.CharacterID)
	return err
}

const fixtureWalletGold = `-- name: FixtureWalletGold :exec
UPDATE characters SET state=jsonb_set(state,'{inventory,gold}',$1::jsonb)
WHERE id=$2
`

type FixtureWalletGoldParams struct {
	Gold        json.RawMessage
	CharacterID int64
}

func (q *Queries) FixtureWalletGold(ctx context.Context, arg FixtureWalletGoldParams) error {
	_, err := q.db.ExecContext(ctx, fixtureWalletGold, arg.Gold, arg.CharacterID)
	return err
}
