// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gm.sql

package sqlcgen

import (
	"context"
	"time"
)

const listGMMail = `-- name: ListGMMail :many
SELECT id,to_account_id,to_character_id,template,amount,title,status,created_at
FROM gm_mail
WHERE ($1::bigint <= 0 OR to_account_id=$1)
AND ($2::text='' OR status=$2)
ORDER BY id DESC LIMIT 200
`

type ListGMMailParams struct {
	AccountID int64
	Status    string
}

type ListGMMailRow struct {
	ID            int64
	ToAccountID   int64
	ToCharacterID int64
	Template      int64
	Amount        int64
	Title         string
	Status        string
	CreatedAt     time.Time
}

func (q *Queries) ListGMMail(ctx context.Context, arg ListGMMailParams) ([]ListGMMailRow, error) {
	rows, err := q.db.QueryContext(ctx, listGMMail, arg.AccountID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGMMailRow
	for rows.Next() {
		var i ListGMMailRow
		if err := rows.Scan(
			&i.ID,
			&i.ToAccountID,
			&i.ToCharacterID,
			&i.Template,
			&i.Amount,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGMMail = `-- name: RevokeGMMail :one
UPDATE gm_mail SET status='revoked'
WHERE id=$1 AND status IN ('unread','read') RETURNING id
`

func (q *Queries) RevokeGMMail(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, revokeGMMail, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const sendGMMail = `-- name: SendGMMail :one
INSERT INTO gm_mail(to_account_id,to_character_id,template,amount,title,body)
VALUES($1,$2,$3,$4,$5,$6) RETURNING id
`

type SendGMMailParams struct {
	AccountID   int64
	CharacterID int64
	Template    int64
	Amount      int64
	Title       string
	Body        string
}

func (q *Queries) SendGMMail(ctx context.Context, arg SendGMMailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sendGMMail,
		arg.AccountID,
		arg.CharacterID,
		arg.Template,
		arg.Amount,
		arg.Title,
		arg.Body,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
