// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const accountMaterials = `-- name: AccountMaterials :one
SELECT counts FROM account_material_storage WHERE account_id=$1
`

func (q *Queries) AccountMaterials(ctx context.Context, accountID int64) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, accountMaterials, accountID)
	var counts json.RawMessage
	err := row.Scan(&counts)
	return counts, err
}

const accountVaultEvent = `-- name: AccountVaultEvent :one
SELECT character_id,operation FROM account_vault_events WHERE account_id=$1 AND event_key=$2
`

type AccountVaultEventParams struct {
	AccountID int64
	EventKey  string
}

type AccountVaultEventRow struct {
	CharacterID int64
	Operation   int32
}

func (q *Queries) AccountVaultEvent(ctx context.Context, arg AccountVaultEventParams) (AccountVaultEventRow, error) {
	row := q.db.QueryRowContext(ctx, accountVaultEvent, arg.AccountID, arg.EventKey)
	var i AccountVaultEventRow
	err := row.Scan(&i.CharacterID, &i.Operation)
	return i, err
}

const ensureAccountVault = `-- name: EnsureAccountVault :exec
INSERT INTO account_vaults(account_id) VALUES($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureAccountVault(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, ensureAccountVault, accountID)
	return err
}

const ensurePrimaryVault = `-- name: EnsurePrimaryVault :exec
INSERT INTO character_vaults(character_id,slots,config_version)
SELECT id,$1::integer,$2::text FROM characters
WHERE id=$3::bigint AND account_id=$4::bigint AND deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type EnsurePrimaryVaultParams struct {
	Slots         int32
	ConfigVersion string
	CharacterID   int64
	AccountID     int64
}

func (q *Queries) EnsurePrimaryVault(ctx context.Context, arg EnsurePrimaryVaultParams) error {
	_, err := q.db.ExecContext(ctx, ensurePrimaryVault,
		arg.Slots,
		arg.ConfigVersion,
		arg.CharacterID,
		arg.AccountID,
	)
	return err
}

const ensureSecondaryVault = `-- name: EnsureSecondaryVault :exec
INSERT INTO character_secondary_vaults(character_id,slots,config_version)
SELECT id,$1::integer,$2::text FROM characters
WHERE id=$3::bigint AND account_id=$4::bigint AND deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type EnsureSecondaryVaultParams struct {
	Slots         int32
	ConfigVersion string
	CharacterID   int64
	AccountID     int64
}

func (q *Queries) EnsureSecondaryVault(ctx context.Context, arg EnsureSecondaryVaultParams) error {
	_, err := q.db.ExecContext(ctx, ensureSecondaryVault,
		arg.Slots,
		arg.ConfigVersion,
		arg.CharacterID,
		arg.AccountID,
	)
	return err
}

const initializeAccountMaterials = `-- name: InitializeAccountMaterials :exec
INSERT INTO account_material_storage(account_id) VALUES($1) ON CONFLICT(account_id) DO NOTHING
`

func (q *Queries) InitializeAccountMaterials(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, initializeAccountMaterials, accountID)
	return err
}

const loadAccountVault = `-- name: LoadAccountVault :one
SELECT coalesce(v.slots,0)::integer AS slots,coalesce(v.gold,0)::bigint AS gold,
coalesce(v.items,'[]'::jsonb)::jsonb AS items FROM characters c LEFT JOIN account_vaults v ON v.account_id=c.account_id
WHERE c.id=$1 AND c.account_id=$2 AND c.deleted_at IS NULL
`

type LoadAccountVaultParams struct {
	CharacterID int64
	AccountID   int64
}

type LoadAccountVaultRow struct {
	Slots int32
	Gold  int64
	Items json.RawMessage
}

func (q *Queries) LoadAccountVault(ctx context.Context, arg LoadAccountVaultParams) (LoadAccountVaultRow, error) {
	row := q.db.QueryRowContext(ctx, loadAccountVault, arg.CharacterID, arg.AccountID)
	var i LoadAccountVaultRow
	err := row.Scan(&i.Slots, &i.Gold, &i.Items)
	return i, err
}

const lockAccountMaterials = `-- name: LockAccountMaterials :one
SELECT counts FROM account_material_storage WHERE account_id=$1 FOR UPDATE
`

func (q *Queries) LockAccountMaterials(ctx context.Context, accountID int64) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, lockAccountMaterials, accountID)
	var counts json.RawMessage
	err := row.Scan(&counts)
	return counts, err
}

const lockAccountVault = `-- name: LockAccountVault :one
SELECT slots,gold,items FROM account_vaults WHERE account_id=$1 FOR UPDATE
`

type LockAccountVaultRow struct {
	Slots int32
	Gold  int64
	Items json.RawMessage
}

func (q *Queries) LockAccountVault(ctx context.Context, accountID int64) (LockAccountVaultRow, error) {
	row := q.db.QueryRowContext(ctx, lockAccountVault, accountID)
	var i LockAccountVaultRow
	err := row.Scan(&i.Slots, &i.Gold, &i.Items)
	return i, err
}

const lockPrimaryVault = `-- name: LockPrimaryVault :one
SELECT slots,items,config_version FROM character_vaults WHERE character_id=$1 FOR UPDATE
`

type LockPrimaryVaultRow struct {
	Slots         int32
	Items         json.RawMessage
	ConfigVersion string
}

func (q *Queries) LockPrimaryVault(ctx context.Context, characterID int64) (LockPrimaryVaultRow, error) {
	row := q.db.QueryRowContext(ctx, lockPrimaryVault, characterID)
	var i LockPrimaryVaultRow
	err := row.Scan(&i.Slots, &i.Items, &i.ConfigVersion)
	return i, err
}

const lockSecondaryVault = `-- name: LockSecondaryVault :one
SELECT slots,items,config_version FROM character_secondary_vaults WHERE character_id=$1 FOR UPDATE
`

type LockSecondaryVaultRow struct {
	Slots         int32
	Items         json.RawMessage
	ConfigVersion string
}

func (q *Queries) LockSecondaryVault(ctx context.Context, characterID int64) (LockSecondaryVaultRow, error) {
	row := q.db.QueryRowContext(ctx, lockSecondaryVault, characterID)
	var i LockSecondaryVaultRow
	err := row.Scan(&i.Slots, &i.Items, &i.ConfigVersion)
	return i, err
}

const ownedPrimaryVault = `-- name: OwnedPrimaryVault :one
SELECT v.slots,v.items,v.config_version FROM character_vaults v JOIN characters c ON c.id=v.character_id
WHERE c.id=$1 AND c.account_id=$2 AND c.deleted_at IS NULL
`

type OwnedPrimaryVaultParams struct {
	CharacterID int64
	AccountID   int64
}

type OwnedPrimaryVaultRow struct {
	Slots         int32
	Items         json.RawMessage
	ConfigVersion string
}

func (q *Queries) OwnedPrimaryVault(ctx context.Context, arg OwnedPrimaryVaultParams) (OwnedPrimaryVaultRow, error) {
	row := q.db.QueryRowContext(ctx, ownedPrimaryVault, arg.CharacterID, arg.AccountID)
	var i OwnedPrimaryVaultRow
	err := row.Scan(&i.Slots, &i.Items, &i.ConfigVersion)
	return i, err
}

const ownedSecondaryVault = `-- name: OwnedSecondaryVault :one
SELECT v.slots,v.items,v.config_version FROM character_secondary_vaults v JOIN characters c ON c.id=v.character_id
WHERE c.id=$1 AND c.account_id=$2 AND c.deleted_at IS NULL
`

type OwnedSecondaryVaultParams struct {
	CharacterID int64
	AccountID   int64
}

type OwnedSecondaryVaultRow struct {
	Slots         int32
	Items         json.RawMessage
	ConfigVersion string
}

func (q *Queries) OwnedSecondaryVault(ctx context.Context, arg OwnedSecondaryVaultParams) (OwnedSecondaryVaultRow, error) {
	row := q.db.QueryRowContext(ctx, ownedSecondaryVault, arg.CharacterID, arg.AccountID)
	var i OwnedSecondaryVaultRow
	err := row.Scan(&i.Slots, &i.Items, &i.ConfigVersion)
	return i, err
}

const recordAccountVaultEvent = `-- name: RecordAccountVaultEvent :exec
INSERT INTO account_vault_events(account_id,event_key,character_id,operation)
VALUES($1,$2,$3,$4)
`

type RecordAccountVaultEventParams struct {
	AccountID   int64
	EventKey    string
	CharacterID int64
	Operation   int32
}

func (q *Queries) RecordAccountVaultEvent(ctx context.Context, arg RecordAccountVaultEventParams) error {
	_, err := q.db.ExecContext(ctx, recordAccountVaultEvent,
		arg.AccountID,
		arg.EventKey,
		arg.CharacterID,
		arg.Operation,
	)
	return err
}

const saveAccountMaterials = `-- name: SaveAccountMaterials :exec
UPDATE account_material_storage SET counts=$1,updated_at=now() WHERE account_id=$2
`

type SaveAccountMaterialsParams struct {
	Counts    json.RawMessage
	AccountID int64
}

func (q *Queries) SaveAccountMaterials(ctx context.Context, arg SaveAccountMaterialsParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountMaterials, arg.Counts, arg.AccountID)
	return err
}

const saveAccountVault = `-- name: SaveAccountVault :exec
UPDATE account_vaults SET slots=$1,gold=$2,items=$3,updated_at=now()
WHERE account_id=$4
`

type SaveAccountVaultParams struct {
	Slots     int32
	Gold      int64
	Items     json.RawMessage
	AccountID int64
}

func (q *Queries) SaveAccountVault(ctx context.Context, arg SaveAccountVaultParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountVault,
		arg.Slots,
		arg.Gold,
		arg.Items,
		arg.AccountID,
	)
	return err
}

const saveAccountVaultItems = `-- name: SaveAccountVaultItems :exec
UPDATE account_vaults SET items=$1,updated_at=now() WHERE account_id=$2
`

type SaveAccountVaultItemsParams struct {
	Items     json.RawMessage
	AccountID int64
}

func (q *Queries) SaveAccountVaultItems(ctx context.Context, arg SaveAccountVaultItemsParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountVaultItems, arg.Items, arg.AccountID)
	return err
}

const saveAccountVaultSlots = `-- name: SaveAccountVaultSlots :exec
UPDATE account_vaults SET slots=$1,updated_at=now() WHERE account_id=$2
`

type SaveAccountVaultSlotsParams struct {
	Slots     int32
	AccountID int64
}

func (q *Queries) SaveAccountVaultSlots(ctx context.Context, arg SaveAccountVaultSlotsParams) error {
	_, err := q.db.ExecContext(ctx, saveAccountVaultSlots, arg.Slots, arg.AccountID)
	return err
}

const savePrimaryVaultItems = `-- name: SavePrimaryVaultItems :exec
UPDATE character_vaults SET items=$1,updated_at=now() WHERE character_id=$2
`

type SavePrimaryVaultItemsParams struct {
	Items       json.RawMessage
	CharacterID int64
}

func (q *Queries) SavePrimaryVaultItems(ctx context.Context, arg SavePrimaryVaultItemsParams) error {
	_, err := q.db.ExecContext(ctx, savePrimaryVaultItems, arg.Items, arg.CharacterID)
	return err
}

const savePrimaryVaultSlots = `-- name: SavePrimaryVaultSlots :exec
UPDATE character_vaults SET slots=$1,updated_at=now() WHERE character_id=$2
`

type SavePrimaryVaultSlotsParams struct {
	Slots       int32
	CharacterID int64
}

func (q *Queries) SavePrimaryVaultSlots(ctx context.Context, arg SavePrimaryVaultSlotsParams) error {
	_, err := q.db.ExecContext(ctx, savePrimaryVaultSlots, arg.Slots, arg.CharacterID)
	return err
}

const saveSecondaryVaultItems = `-- name: SaveSecondaryVaultItems :exec
UPDATE character_secondary_vaults SET items=$1,updated_at=now() WHERE character_id=$2
`

type SaveSecondaryVaultItemsParams struct {
	Items       json.RawMessage
	CharacterID int64
}

func (q *Queries) SaveSecondaryVaultItems(ctx context.Context, arg SaveSecondaryVaultItemsParams) error {
	_, err := q.db.ExecContext(ctx, saveSecondaryVaultItems, arg.Items, arg.CharacterID)
	return err
}

const saveSecondaryVaultSlots = `-- name: SaveSecondaryVaultSlots :exec
UPDATE character_secondary_vaults SET slots=$1,updated_at=now() WHERE character_id=$2
`

type SaveSecondaryVaultSlotsParams struct {
	Slots       int32
	CharacterID int64
}

func (q *Queries) SaveSecondaryVaultSlots(ctx context.Context, arg SaveSecondaryVaultSlotsParams) error {
	_, err := q.db.ExecContext(ctx, saveSecondaryVaultSlots, arg.Slots, arg.CharacterID)
	return err
}
