// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPlayerMail = `-- name: InsertPlayerMail :one
INSERT INTO character_mail(sender_id,recipient_id,sender_name,body,assets,expires_at)
VALUES($1,$2,$3,$4,$5,now()+interval '15 days') RETURNING id
`

type InsertPlayerMailParams struct {
	SenderID    pgtype.Int8
	RecipientID int64
	SenderName  string
	Body        string
	Assets      json.RawMessage
}

func (q *Queries) InsertPlayerMail(ctx context.Context, arg InsertPlayerMailParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPlayerMail,
		arg.SenderID,
		arg.RecipientID,
		arg.SenderName,
		arg.Body,
		arg.Assets,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSystemMail = `-- name: InsertSystemMail :one
INSERT INTO character_mail(recipient_id,sender_name,body,assets,expires_at)
VALUES($1,$2,$3,$4,now()+interval '15 days') RETURNING id
`

type InsertSystemMailParams struct {
	RecipientID int64
	SenderName  string
	Body        string
	Assets      json.RawMessage
}

func (q *Queries) InsertSystemMail(ctx context.Context, arg InsertSystemMailParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSystemMail,
		arg.RecipientID,
		arg.SenderName,
		arg.Body,
		arg.Assets,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockMailCharacters = `-- name: LockMailCharacters :many
SELECT id,account_id,wire_id,name,profession,create_request,config_version,state,created_at,
0::smallint AS fixed_slot FROM characters WHERE id=ANY($1::bigint[])
AND deleted_at IS NULL ORDER BY id FOR UPDATE
`

type LockMailCharactersRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	CreatedAt     time.Time
	FixedSlot     int16
}

func (q *Queries) LockMailCharacters(ctx context.Context, characterIds []int64) ([]LockMailCharactersRow, error) {
	rows, err := q.db.Query(ctx, lockMailCharacters, characterIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockMailCharactersRow
	for rows.Next() {
		var i LockMailCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.WireID,
			&i.Name,
			&i.Profession,
			&i.CreateRequest,
			&i.ConfigVersion,
			&i.State,
			&i.CreatedAt,
			&i.FixedSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMailbox = `-- name: LockMailbox :many
SELECT m.id,coalesce(m.sender_id,0)::bigint AS sender_id,m.recipient_id,m.sender_name,
m.body,m.status,m.assets,m.expires_at,(m.deleted_at IS NOT NULL)::boolean AS deleted
FROM character_mail m WHERE recipient_id=$1
AND ($2::boolean OR (deleted_at IS NULL AND (expires_at>now() OR status=3)))
AND ($3::bigint[] IS NULL OR id=ANY($3::bigint[])) ORDER BY id FOR UPDATE
`

type LockMailboxParams struct {
	RecipientID    int64
	IncludeDeleted bool
	MessageIds     []int64
}

type LockMailboxRow struct {
	ID          int64
	SenderID    int64
	RecipientID int64
	SenderName  string
	Body        string
	Status      int16
	Assets      json.RawMessage
	ExpiresAt   time.Time
	Deleted     bool
}

func (q *Queries) LockMailbox(ctx context.Context, arg LockMailboxParams) ([]LockMailboxRow, error) {
	rows, err := q.db.Query(ctx, lockMailbox, arg.RecipientID, arg.IncludeDeleted, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockMailboxRow
	for rows.Next() {
		var i LockMailboxRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.SenderName,
			&i.Body,
			&i.Status,
			&i.Assets,
			&i.ExpiresAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailRecipient = `-- name: MailRecipient :one
SELECT id,account_id,wire_id,name,profession,create_request,config_version,state,created_at,
0::smallint AS fixed_slot FROM characters WHERE lower(name)=lower($1::text) AND deleted_at IS NULL
`

type MailRecipientRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	CreatedAt     time.Time
	FixedSlot     int16
}

func (q *Queries) MailRecipient(ctx context.Context, name string) (MailRecipientRow, error) {
	row := q.db.QueryRow(ctx, mailRecipient, name)
	var i MailRecipientRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.WireID,
		&i.Name,
		&i.Profession,
		&i.CreateRequest,
		&i.ConfigVersion,
		&i.State,
		&i.CreatedAt,
		&i.FixedSlot,
	)
	return i, err
}

const mailRecipientID = `-- name: MailRecipientID :one
SELECT id FROM characters WHERE lower(name)=lower($1::text) AND deleted_at IS NULL
`

func (q *Queries) MailRecipientID(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, mailRecipientID, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const mailSendReceipt = `-- name: MailSendReceipt :one
SELECT outcome FROM character_events WHERE character_id=$1
AND event_key=$2 AND model='mail-send-v1'
`

type MailSendReceiptParams struct {
	CharacterID int64
	EventKey    string
}

func (q *Queries) MailSendReceipt(ctx context.Context, arg MailSendReceiptParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, mailSendReceipt, arg.CharacterID, arg.EventKey)
	var outcome json.RawMessage
	err := row.Scan(&outcome)
	return outcome, err
}

const mailbox = `-- name: Mailbox :many
SELECT m.id,coalesce(m.sender_id,0)::bigint AS sender_id,m.recipient_id,m.sender_name,
m.body,m.status,m.assets,m.expires_at,(m.deleted_at IS NOT NULL)::boolean AS deleted
FROM character_mail m JOIN characters c ON c.id=m.recipient_id
WHERE c.account_id=$1 AND c.id=$2 AND c.deleted_at IS NULL
AND m.deleted_at IS NULL AND (m.expires_at>now() OR m.status=3) ORDER BY m.id
`

type MailboxParams struct {
	AccountID   int64
	CharacterID int64
}

type MailboxRow struct {
	ID          int64
	SenderID    int64
	RecipientID int64
	SenderName  string
	Body        string
	Status      int16
	Assets      json.RawMessage
	ExpiresAt   time.Time
	Deleted     bool
}

func (q *Queries) Mailbox(ctx context.Context, arg MailboxParams) ([]MailboxRow, error) {
	rows, err := q.db.Query(ctx, mailbox, arg.AccountID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailboxRow
	for rows.Next() {
		var i MailboxRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.SenderName,
			&i.Body,
			&i.Status,
			&i.Assets,
			&i.ExpiresAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailboxCapacity = `-- name: MailboxCapacity :one
SELECT count(*) AS messages,coalesce(sum((SELECT count(*) FROM jsonb_array_elements(m.assets) a
WHERE NOT coalesce((a->>'claimed')::boolean,false))),0)::bigint AS unclaimed_assets
FROM character_mail m WHERE recipient_id=$1 AND deleted_at IS NULL AND (expires_at>now() OR status=3)
`

type MailboxCapacityRow struct {
	Messages        int64
	UnclaimedAssets int64
}

func (q *Queries) MailboxCapacity(ctx context.Context, recipientID int64) (MailboxCapacityRow, error) {
	row := q.db.QueryRow(ctx, mailboxCapacity, recipientID)
	var i MailboxCapacityRow
	err := row.Scan(&i.Messages, &i.UnclaimedAssets)
	return i, err
}

const mailboxDeliveryState = `-- name: MailboxDeliveryState :one
SELECT coalesce(max(m.id),0)::bigint AS latest_id,count(*) FILTER (WHERE m.status=1) AS unread
FROM character_mail m JOIN characters c ON c.id=m.recipient_id
WHERE c.account_id=$1 AND c.id=$2 AND c.deleted_at IS NULL
AND m.deleted_at IS NULL AND m.expires_at>now()
`

type MailboxDeliveryStateParams struct {
	AccountID   int64
	CharacterID int64
}

type MailboxDeliveryStateRow struct {
	LatestID int64
	Unread   int64
}

func (q *Queries) MailboxDeliveryState(ctx context.Context, arg MailboxDeliveryStateParams) (MailboxDeliveryStateRow, error) {
	row := q.db.QueryRow(ctx, mailboxDeliveryState, arg.AccountID, arg.CharacterID)
	var i MailboxDeliveryStateRow
	err := row.Scan(&i.LatestID, &i.Unread)
	return i, err
}

const nextMailID = `-- name: NextMailID :one
SELECT nextval('mailbox_id_seq')::bigint AS id
`

func (q *Queries) NextMailID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextMailID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateMail = `-- name: UpdateMail :execrows
UPDATE character_mail SET assets=$1,status=$2::integer,
deleted_at=CASE WHEN $3::boolean THEN now() ELSE NULL END
WHERE id=$4 AND recipient_id=$5 AND deleted_at IS NULL
`

type UpdateMailParams struct {
	Assets      json.RawMessage
	Status      int32
	Deleted     bool
	MailID      int64
	RecipientID int64
}

func (q *Queries) UpdateMail(ctx context.Context, arg UpdateMailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMail,
		arg.Assets,
		arg.Status,
		arg.Deleted,
		arg.MailID,
		arg.RecipientID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
