// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrations.sql

package sqlcgen

import (
	"context"
)

const lockMigrations = `-- name: LockMigrations :exec
SELECT pg_advisory_xact_lock(11520261004)
`

// Transaction-scoped; released automatically even when initialization fails.
func (q *Queries) LockMigrations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockMigrations)
	return err
}

const migrationChecksum = `-- name: MigrationChecksum :one
SELECT checksum FROM storage_migrations WHERE name=$1
`

func (q *Queries) MigrationChecksum(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, migrationChecksum, name)
	var checksum string
	err := row.Scan(&checksum)
	return checksum, err
}

const recordMigration = `-- name: RecordMigration :exec
INSERT INTO storage_migrations(name,checksum) VALUES($1,$2)
ON CONFLICT(name) DO UPDATE SET last_applied_at=now(),runs=storage_migrations.runs+1
`

type RecordMigrationParams struct {
	Name     string
	Checksum string
}

func (q *Queries) RecordMigration(ctx context.Context, arg RecordMigrationParams) error {
	_, err := q.db.Exec(ctx, recordMigration, arg.Name, arg.Checksum)
	return err
}
