// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oath.sql

package sqlcgen

import (
	"context"
)

const equippedOathSelection = `-- name: EquippedOathSelection :one
SELECT selected_option FROM character_oath_options WHERE character_id=$1 AND core_instance_key=$2
`

type EquippedOathSelectionParams struct {
	CharacterID     int64
	CoreInstanceKey string
}

func (q *Queries) EquippedOathSelection(ctx context.Context, arg EquippedOathSelectionParams) (int32, error) {
	row := q.db.QueryRow(ctx, equippedOathSelection, arg.CharacterID, arg.CoreInstanceKey)
	var selected_option int32
	err := row.Scan(&selected_option)
	return selected_option, err
}

const insertOathOption = `-- name: InsertOathOption :exec
INSERT INTO character_oath_options(character_id,core_instance_key,selected_option,revision,updated_at)
VALUES($1,$2,$3::bigint,$4,now())
`

type InsertOathOptionParams struct {
	CharacterID     int64
	CoreInstanceKey string
	SelectedOption  int64
	Revision        int64
}

func (q *Queries) InsertOathOption(ctx context.Context, arg InsertOathOptionParams) error {
	_, err := q.db.Exec(ctx, insertOathOption,
		arg.CharacterID,
		arg.CoreInstanceKey,
		arg.SelectedOption,
		arg.Revision,
	)
	return err
}

const lockOathOptionRevision = `-- name: LockOathOptionRevision :one
SELECT revision FROM character_oath_options WHERE character_id=$1 AND core_instance_key=$2 FOR UPDATE
`

type LockOathOptionRevisionParams struct {
	CharacterID     int64
	CoreInstanceKey string
}

func (q *Queries) LockOathOptionRevision(ctx context.Context, arg LockOathOptionRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockOathOptionRevision, arg.CharacterID, arg.CoreInstanceKey)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const oathOption = `-- name: OathOption :one
SELECT character_id,core_instance_key,selected_option,revision FROM character_oath_options
WHERE character_id=$1 AND core_instance_key=$2
`

type OathOptionParams struct {
	CharacterID     int64
	CoreInstanceKey string
}

type OathOptionRow struct {
	CharacterID     int64
	CoreInstanceKey string
	SelectedOption  int32
	Revision        int64
}

func (q *Queries) OathOption(ctx context.Context, arg OathOptionParams) (OathOptionRow, error) {
	row := q.db.QueryRow(ctx, oathOption, arg.CharacterID, arg.CoreInstanceKey)
	var i OathOptionRow
	err := row.Scan(
		&i.CharacterID,
		&i.CoreInstanceKey,
		&i.SelectedOption,
		&i.Revision,
	)
	return i, err
}

const selectEquippedOathOption = `-- name: SelectEquippedOathOption :exec
INSERT INTO character_oath_options(character_id,core_instance_key,selected_option,revision,updated_at)
VALUES($1,$2,$3::bigint,1,now())
ON CONFLICT(character_id,core_instance_key) DO UPDATE SET selected_option=EXCLUDED.selected_option,
revision=character_oath_options.revision+1,updated_at=now()
`

type SelectEquippedOathOptionParams struct {
	CharacterID     int64
	CoreInstanceKey string
	SelectedOption  int64
}

func (q *Queries) SelectEquippedOathOption(ctx context.Context, arg SelectEquippedOathOptionParams) error {
	_, err := q.db.Exec(ctx, selectEquippedOathOption, arg.CharacterID, arg.CoreInstanceKey, arg.SelectedOption)
	return err
}

const updateOathOption = `-- name: UpdateOathOption :exec
UPDATE character_oath_options SET selected_option=$1::bigint,revision=$2,updated_at=now()
WHERE character_id=$3 AND core_instance_key=$4
`

type UpdateOathOptionParams struct {
	SelectedOption  int64
	Revision        int64
	CharacterID     int64
	CoreInstanceKey string
}

func (q *Queries) UpdateOathOption(ctx context.Context, arg UpdateOathOptionParams) error {
	_, err := q.db.Exec(ctx, updateOathOption,
		arg.SelectedOption,
		arg.Revision,
		arg.CharacterID,
		arg.CoreInstanceKey,
	)
	return err
}
