// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progression.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const activeCharacterOwned = `-- name: ActiveCharacterOwned :one
SELECT EXISTS(SELECT 1 FROM characters WHERE account_id=$1
AND id=$2 AND deleted_at IS NULL)
`

type ActiveCharacterOwnedParams struct {
	AccountID   int64
	CharacterID int64
}

func (q *Queries) ActiveCharacterOwned(ctx context.Context, arg ActiveCharacterOwnedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, activeCharacterOwned, arg.AccountID, arg.CharacterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const advanceBirth = `-- name: AdvanceBirth :execrows
UPDATE character_birth b SET stage=$1::smallint,dungeon=$2::bigint,updated_at=now()
FROM characters c WHERE c.id=b.character_id AND c.account_id=$3
AND c.id=$4 AND c.deleted_at IS NULL AND b.stage<$1::smallint
`

type AdvanceBirthParams struct {
	Stage       int16
	Dungeon     int64
	AccountID   int64
	CharacterID int64
}

func (q *Queries) AdvanceBirth(ctx context.Context, arg AdvanceBirthParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceBirth,
		arg.Stage,
		arg.Dungeon,
		arg.AccountID,
		arg.CharacterID,
	)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const advanceTowerFloor = `-- name: AdvanceTowerFloor :one
UPDATE account_tower_progress SET highest_cleared=$1::integer,last_run_id=$2
WHERE account_id=$3 AND tower_key=$4
AND highest_cleared=$1::integer-1 AND entries_today>0
RETURNING highest_cleared,COALESCE(entry_day::text,'')::text AS entry_day,entries_today,last_run_id
`

type AdvanceTowerFloorParams struct {
	Floor     int32
	RunID     string
	AccountID int64
	TowerKey  string
}

type AdvanceTowerFloorRow struct {
	HighestCleared int16
	EntryDay       string
	EntriesToday   int16
	LastRunID      string
}

func (q *Queries) AdvanceTowerFloor(ctx context.Context, arg AdvanceTowerFloorParams) (AdvanceTowerFloorRow, error) {
	row := q.db.QueryRowContext(ctx, advanceTowerFloor,
		arg.Floor,
		arg.RunID,
		arg.AccountID,
		arg.TowerKey,
	)
	var i AdvanceTowerFloorRow
	err := row.Scan(
		&i.HighestCleared,
		&i.EntryDay,
		&i.EntriesToday,
		&i.LastRunID,
	)
	return i, err
}

const advanceTowerGrief = `-- name: AdvanceTowerGrief :one
UPDATE account_tower_grief_progress SET highest_cleared=$1::integer,
cleared_day=$2::text::date,last_run_id=$3
WHERE account_id=$4 AND highest_cleared=$1::integer-1
AND (cleared_day IS NULL OR cleared_day<>$2::text::date)
RETURNING highest_cleared,cleared_day::text,last_run_id
`

type AdvanceTowerGriefParams struct {
	Floor     int32
	Day       string
	RunID     string
	AccountID int64
}

type AdvanceTowerGriefRow struct {
	HighestCleared int16
	ClearedDay     string
	LastRunID      string
}

func (q *Queries) AdvanceTowerGrief(ctx context.Context, arg AdvanceTowerGriefParams) (AdvanceTowerGriefRow, error) {
	row := q.db.QueryRowContext(ctx, advanceTowerGrief,
		arg.Floor,
		arg.Day,
		arg.RunID,
		arg.AccountID,
	)
	var i AdvanceTowerGriefRow
	err := row.Scan(&i.HighestCleared, &i.ClearedDay, &i.LastRunID)
	return i, err
}

const backfillBirth = `-- name: BackfillBirth :exec
INSERT INTO character_birth(character_id,stage)
SELECT id,$1::smallint FROM characters ON CONFLICT(character_id) DO NOTHING
`

func (q *Queries) BackfillBirth(ctx context.Context, stage int16) error {
	_, err := q.db.ExecContext(ctx, backfillBirth, stage)
	return err
}

const birthStage = `-- name: BirthStage :one
SELECT b.stage,b.dungeon FROM character_birth b JOIN characters c ON c.id=b.character_id
WHERE c.account_id=$1 AND c.id=$2 AND c.deleted_at IS NULL
`

type BirthStageParams struct {
	AccountID   int64
	CharacterID int64
}

type BirthStageRow struct {
	Stage   int16
	Dungeon int64
}

func (q *Queries) BirthStage(ctx context.Context, arg BirthStageParams) (BirthStageRow, error) {
	row := q.db.QueryRowContext(ctx, birthStage, arg.AccountID, arg.CharacterID)
	var i BirthStageRow
	err := row.Scan(&i.Stage, &i.Dungeon)
	return i, err
}

const ensureTowerGriefProgress = `-- name: EnsureTowerGriefProgress :exec
INSERT INTO account_tower_grief_progress(account_id,highest_cleared)
VALUES($1,$2::integer) ON CONFLICT(account_id) DO NOTHING
`

type EnsureTowerGriefProgressParams struct {
	AccountID      int64
	HighestCleared int32
}

func (q *Queries) EnsureTowerGriefProgress(ctx context.Context, arg EnsureTowerGriefProgressParams) error {
	_, err := q.db.ExecContext(ctx, ensureTowerGriefProgress, arg.AccountID, arg.HighestCleared)
	return err
}

const ensureTowerProgress = `-- name: EnsureTowerProgress :exec
INSERT INTO account_tower_progress(account_id,tower_key,highest_cleared)
VALUES($1,$2,$3::integer) ON CONFLICT(account_id,tower_key) DO NOTHING
`

type EnsureTowerProgressParams struct {
	AccountID      int64
	TowerKey       string
	HighestCleared int32
}

func (q *Queries) EnsureTowerProgress(ctx context.Context, arg EnsureTowerProgressParams) error {
	_, err := q.db.ExecContext(ctx, ensureTowerProgress, arg.AccountID, arg.TowerKey, arg.HighestCleared)
	return err
}

const ensureWorld = `-- name: EnsureWorld :exec
INSERT INTO character_world(character_id,position,config_version)
SELECT id,$1,$2 FROM characters
WHERE id=$3 AND account_id=$4 ON CONFLICT DO NOTHING
`

type EnsureWorldParams struct {
	Position      json.RawMessage
	ConfigVersion string
	CharacterID   int64
	AccountID     int64
}

func (q *Queries) EnsureWorld(ctx context.Context, arg EnsureWorldParams) error {
	_, err := q.db.ExecContext(ctx, ensureWorld,
		arg.Position,
		arg.ConfigVersion,
		arg.CharacterID,
		arg.AccountID,
	)
	return err
}

const enterChannelWorld = `-- name: EnterChannelWorld :exec
INSERT INTO character_channel_world(character_id,channel_type,position,config_version)
SELECT id,$1::integer,$2,$3 FROM characters
WHERE id=$4 AND account_id=$5
ON CONFLICT (character_id,channel_type) DO UPDATE SET position=EXCLUDED.position,updated_at=now()
`

type EnterChannelWorldParams struct {
	ChannelType   int32
	Position      json.RawMessage
	ConfigVersion string
	CharacterID   int64
	AccountID     int64
}

func (q *Queries) EnterChannelWorld(ctx context.Context, arg EnterChannelWorldParams) error {
	_, err := q.db.ExecContext(ctx, enterChannelWorld,
		arg.ChannelType,
		arg.Position,
		arg.ConfigVersion,
		arg.CharacterID,
		arg.AccountID,
	)
	return err
}

const fatigueRecoveryUsage = `-- name: FatigueRecoveryUsage :one
SELECT count(*) FILTER(WHERE day=$1::text::date)::bigint AS daily_uses,
COALESCE(max(used_at),'epoch'::timestamptz)::timestamptz AS last_used,
count(*)>0 AS has_last_used FROM character_fatigue_recovery
WHERE character_id=$2 AND template=$3
`

type FatigueRecoveryUsageParams struct {
	Day         string
	CharacterID int64
	Template    int64
}

type FatigueRecoveryUsageRow struct {
	DailyUses   int64
	LastUsed    time.Time
	HasLastUsed bool
}

func (q *Queries) FatigueRecoveryUsage(ctx context.Context, arg FatigueRecoveryUsageParams) (FatigueRecoveryUsageRow, error) {
	row := q.db.QueryRowContext(ctx, fatigueRecoveryUsage, arg.Day, arg.CharacterID, arg.Template)
	var i FatigueRecoveryUsageRow
	err := row.Scan(&i.DailyUses, &i.LastUsed, &i.HasLastUsed)
	return i, err
}

const fatigueRoomRecorded = `-- name: FatigueRoomRecorded :one
SELECT EXISTS(SELECT 1 FROM character_fatigue_rooms WHERE character_id=$1
AND run_id=$2 AND map_id=$3)
`

type FatigueRoomRecordedParams struct {
	CharacterID int64
	RunID       string
	MapID       int64
}

func (q *Queries) FatigueRoomRecorded(ctx context.Context, arg FatigueRoomRecordedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, fatigueRoomRecorded, arg.CharacterID, arg.RunID, arg.MapID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ispinsWeeklyUsed = `-- name: IspinsWeeklyUsed :one
SELECT EXISTS(SELECT 1 FROM character_events e JOIN characters c ON c.id=e.character_id
WHERE c.id=$1 AND c.account_id=$2 AND c.deleted_at IS NULL
AND e.model=$3 AND e.outcome->>'week'=$4::text)
`

type IspinsWeeklyUsedParams struct {
	CharacterID int64
	AccountID   int64
	Model       string
	Week        string
}

func (q *Queries) IspinsWeeklyUsed(ctx context.Context, arg IspinsWeeklyUsedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, ispinsWeeklyUsed,
		arg.CharacterID,
		arg.AccountID,
		arg.Model,
		arg.Week,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const loadFatigue = `-- name: LoadFatigue :one
INSERT INTO character_fatigue(character_id,day,daily_limit)
SELECT id,$1::text::date,$2::integer FROM characters
WHERE account_id=$3 AND id=$4
ON CONFLICT(character_id) DO UPDATE SET
used=CASE WHEN EXCLUDED.day>character_fatigue.day THEN 0 ELSE character_fatigue.used END,
used_max=CASE WHEN EXCLUDED.day>character_fatigue.day THEN 0 ELSE character_fatigue.used_max END,
daily_limit=CASE WHEN EXCLUDED.day>=character_fatigue.day THEN EXCLUDED.daily_limit ELSE character_fatigue.daily_limit END,
day=GREATEST(EXCLUDED.day,character_fatigue.day),updated_at=now()
RETURNING day::text,used,daily_limit,used_max
`

type LoadFatigueParams struct {
	Day         string
	DailyLimit  int32
	AccountID   int64
	CharacterID int64
}

type LoadFatigueRow struct {
	Day        string
	Used       int32
	DailyLimit int32
	UsedMax    int32
}

func (q *Queries) LoadFatigue(ctx context.Context, arg LoadFatigueParams) (LoadFatigueRow, error) {
	row := q.db.QueryRowContext(ctx, loadFatigue,
		arg.Day,
		arg.DailyLimit,
		arg.AccountID,
		arg.CharacterID,
	)
	var i LoadFatigueRow
	err := row.Scan(
		&i.Day,
		&i.Used,
		&i.DailyLimit,
		&i.UsedMax,
	)
	return i, err
}

const loadLockedCharacterFatigue = `-- name: LoadLockedCharacterFatigue :one
INSERT INTO character_fatigue(character_id,day,daily_limit)
VALUES($1,$2::text::date,$3::integer)
ON CONFLICT(character_id) DO UPDATE SET
used=CASE WHEN EXCLUDED.day>character_fatigue.day THEN 0 ELSE character_fatigue.used END,
used_max=CASE WHEN EXCLUDED.day>character_fatigue.day THEN 0 ELSE character_fatigue.used_max END,
daily_limit=CASE WHEN EXCLUDED.day>=character_fatigue.day THEN EXCLUDED.daily_limit ELSE character_fatigue.daily_limit END,
day=GREATEST(EXCLUDED.day,character_fatigue.day),updated_at=now()
RETURNING day::text,used,daily_limit,used_max
`

type LoadLockedCharacterFatigueParams struct {
	CharacterID int64
	Day         string
	DailyLimit  int32
}

type LoadLockedCharacterFatigueRow struct {
	Day        string
	Used       int32
	DailyLimit int32
	UsedMax    int32
}

func (q *Queries) LoadLockedCharacterFatigue(ctx context.Context, arg LoadLockedCharacterFatigueParams) (LoadLockedCharacterFatigueRow, error) {
	row := q.db.QueryRowContext(ctx, loadLockedCharacterFatigue, arg.CharacterID, arg.Day, arg.DailyLimit)
	var i LoadLockedCharacterFatigueRow
	err := row.Scan(
		&i.Day,
		&i.Used,
		&i.DailyLimit,
		&i.UsedMax,
	)
	return i, err
}

const loadWorld = `-- name: LoadWorld :one
SELECT w.position,w.revision,w.config_version FROM character_world w JOIN characters c ON c.id=w.character_id
WHERE c.account_id=$1 AND c.id=$2
`

type LoadWorldParams struct {
	AccountID   int64
	CharacterID int64
}

type LoadWorldRow struct {
	Position      json.RawMessage
	Revision      int64
	ConfigVersion string
}

func (q *Queries) LoadWorld(ctx context.Context, arg LoadWorldParams) (LoadWorldRow, error) {
	row := q.db.QueryRowContext(ctx, loadWorld, arg.AccountID, arg.CharacterID)
	var i LoadWorldRow
	err := row.Scan(&i.Position, &i.Revision, &i.ConfigVersion)
	return i, err
}

const lockOathProgress = `-- name: LockOathProgress :one
SELECT clears FROM character_oath_progress WHERE character_id=$1 AND dungeon_id=$2 FOR UPDATE
`

type LockOathProgressParams struct {
	CharacterID int64
	DungeonID   int64
}

func (q *Queries) LockOathProgress(ctx context.Context, arg LockOathProgressParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, lockOathProgress, arg.CharacterID, arg.DungeonID)
	var clears int32
	err := row.Scan(&clears)
	return clears, err
}

const lockedIspinsWeeklyUsed = `-- name: LockedIspinsWeeklyUsed :one
SELECT EXISTS(SELECT 1 FROM character_events WHERE character_id=$1
AND model=$2 AND outcome->>'week'=$3::text)
`

type LockedIspinsWeeklyUsedParams struct {
	CharacterID int64
	Model       string
	Week        string
}

func (q *Queries) LockedIspinsWeeklyUsed(ctx context.Context, arg LockedIspinsWeeklyUsedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, lockedIspinsWeeklyUsed, arg.CharacterID, arg.Model, arg.Week)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const oathProgressClears = `-- name: OathProgressClears :one
SELECT clears FROM character_oath_progress WHERE character_id=$1 AND dungeon_id=$2
`

type OathProgressClearsParams struct {
	CharacterID int64
	DungeonID   int64
}

func (q *Queries) OathProgressClears(ctx context.Context, arg OathProgressClearsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, oathProgressClears, arg.CharacterID, arg.DungeonID)
	var clears int32
	err := row.Scan(&clears)
	return clears, err
}

const odysseyGraduationAlreadyPaid = `-- name: OdysseyGraduationAlreadyPaid :one
SELECT EXISTS(SELECT 1 FROM character_events WHERE character_id=$1
AND event_key IN('odyssey-graduate-reward-v1','odyssey-honor-mail-v1'))
`

func (q *Queries) OdysseyGraduationAlreadyPaid(ctx context.Context, characterID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, odysseyGraduationAlreadyPaid, characterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const omenState = `-- name: OmenState :one
SELECT held,orthaire_pending FROM character_omen_state WHERE character_id=$1 AND dungeon_id=$2
`

type OmenStateParams struct {
	CharacterID int64
	DungeonID   int64
}

type OmenStateRow struct {
	Held            int32
	OrthairePending bool
}

func (q *Queries) OmenState(ctx context.Context, arg OmenStateParams) (OmenStateRow, error) {
	row := q.db.QueryRowContext(ctx, omenState, arg.CharacterID, arg.DungeonID)
	var i OmenStateRow
	err := row.Scan(&i.Held, &i.OrthairePending)
	return i, err
}

const readTowerGriefProgress = `-- name: ReadTowerGriefProgress :one
SELECT highest_cleared,COALESCE(cleared_day::text,'')::text AS cleared_day,last_run_id
FROM account_tower_grief_progress WHERE account_id=$1
`

type ReadTowerGriefProgressRow struct {
	HighestCleared int16
	ClearedDay     string
	LastRunID      string
}

func (q *Queries) ReadTowerGriefProgress(ctx context.Context, accountID int64) (ReadTowerGriefProgressRow, error) {
	row := q.db.QueryRowContext(ctx, readTowerGriefProgress, accountID)
	var i ReadTowerGriefProgressRow
	err := row.Scan(&i.HighestCleared, &i.ClearedDay, &i.LastRunID)
	return i, err
}

const readTowerProgress = `-- name: ReadTowerProgress :one
SELECT highest_cleared,COALESCE(entry_day::text,'')::text AS entry_day,entries_today,last_run_id
FROM account_tower_progress WHERE account_id=$1 AND tower_key=$2
`

type ReadTowerProgressParams struct {
	AccountID int64
	TowerKey  string
}

type ReadTowerProgressRow struct {
	HighestCleared int16
	EntryDay       string
	EntriesToday   int16
	LastRunID      string
}

func (q *Queries) ReadTowerProgress(ctx context.Context, arg ReadTowerProgressParams) (ReadTowerProgressRow, error) {
	row := q.db.QueryRowContext(ctx, readTowerProgress, arg.AccountID, arg.TowerKey)
	var i ReadTowerProgressRow
	err := row.Scan(
		&i.HighestCleared,
		&i.EntryDay,
		&i.EntriesToday,
		&i.LastRunID,
	)
	return i, err
}

const recordFatigueRecovery = `-- name: RecordFatigueRecovery :exec
INSERT INTO character_fatigue_recovery(character_id,template,day,ordinal,restored,used_at)
VALUES($1,$2,$3::text::date,
$4::bigint,$5,$6)
`

type RecordFatigueRecoveryParams struct {
	CharacterID int64
	Template    int64
	Day         string
	Ordinal     int64
	Restored    int32
	UsedAt      time.Time
}

func (q *Queries) RecordFatigueRecovery(ctx context.Context, arg RecordFatigueRecoveryParams) error {
	_, err := q.db.ExecContext(ctx, recordFatigueRecovery,
		arg.CharacterID,
		arg.Template,
		arg.Day,
		arg.Ordinal,
		arg.Restored,
		arg.UsedAt,
	)
	return err
}

const recordFatigueRoom = `-- name: RecordFatigueRoom :exec
INSERT INTO character_fatigue_rooms(character_id,run_id,map_id,day,cost)
VALUES($1,$2,$3,$4::text::date,$5)
`

type RecordFatigueRoomParams struct {
	CharacterID int64
	RunID       string
	MapID       int64
	Day         string
	Cost        int32
}

func (q *Queries) RecordFatigueRoom(ctx context.Context, arg RecordFatigueRoomParams) error {
	_, err := q.db.ExecContext(ctx, recordFatigueRoom,
		arg.CharacterID,
		arg.RunID,
		arg.MapID,
		arg.Day,
		arg.Cost,
	)
	return err
}

const recordIspinsWeeklyClear = `-- name: RecordIspinsWeeklyClear :exec
INSERT INTO character_events(character_id,event_key,config_version,model,outcome)
VALUES($1,$2,$3,$4,
jsonb_build_object('week',$5::text,'run',$6::text))
`

type RecordIspinsWeeklyClearParams struct {
	CharacterID   int64
	EventKey      string
	ConfigVersion string
	Model         string
	Week          string
	Run           string
}

func (q *Queries) RecordIspinsWeeklyClear(ctx context.Context, arg RecordIspinsWeeklyClearParams) error {
	_, err := q.db.ExecContext(ctx, recordIspinsWeeklyClear,
		arg.CharacterID,
		arg.EventKey,
		arg.ConfigVersion,
		arg.Model,
		arg.Week,
		arg.Run,
	)
	return err
}

const reserveTowerEntry = `-- name: ReserveTowerEntry :one
UPDATE account_tower_progress SET entry_day=$1::text::date,
entries_today=CASE WHEN entry_day=$1::text::date THEN entries_today+1 ELSE 1 END
WHERE account_id=$2 AND tower_key=$3 AND highest_cleared+1=$4::integer
RETURNING highest_cleared,entry_day::text,entries_today,last_run_id
`

type ReserveTowerEntryParams struct {
	Day       string
	AccountID int64
	TowerKey  string
	Floor     int32
}

type ReserveTowerEntryRow struct {
	HighestCleared int16
	EntryDay       string
	EntriesToday   int16
	LastRunID      string
}

func (q *Queries) ReserveTowerEntry(ctx context.Context, arg ReserveTowerEntryParams) (ReserveTowerEntryRow, error) {
	row := q.db.QueryRowContext(ctx, reserveTowerEntry,
		arg.Day,
		arg.AccountID,
		arg.TowerKey,
		arg.Floor,
	)
	var i ReserveTowerEntryRow
	err := row.Scan(
		&i.HighestCleared,
		&i.EntryDay,
		&i.EntriesToday,
		&i.LastRunID,
	)
	return i, err
}

const runFatigueLedger = `-- name: RunFatigueLedger :one
SELECT COALESCE(SUM(f.cost),0)::bigint AS charged,COUNT(*)::bigint AS rooms
FROM character_fatigue_rooms f JOIN characters c ON c.id=f.character_id
WHERE c.account_id=$1 AND c.id=$2 AND f.run_id=$3
`

type RunFatigueLedgerParams struct {
	AccountID   int64
	CharacterID int64
	RunID       string
}

type RunFatigueLedgerRow struct {
	Charged int64
	Rooms   int64
}

func (q *Queries) RunFatigueLedger(ctx context.Context, arg RunFatigueLedgerParams) (RunFatigueLedgerRow, error) {
	row := q.db.QueryRowContext(ctx, runFatigueLedger, arg.AccountID, arg.CharacterID, arg.RunID)
	var i RunFatigueLedgerRow
	err := row.Scan(&i.Charged, &i.Rooms)
	return i, err
}

const runMonsterExperience = `-- name: RunMonsterExperience :one
SELECT COALESCE(SUM((e.outcome->>'gain')::bigint),0)::bigint AS total
FROM character_events e JOIN characters c ON c.id=e.character_id
WHERE c.account_id=$1 AND c.id=$2 AND e.event_key LIKE $3
`

type RunMonsterExperienceParams struct {
	AccountID    int64
	CharacterID  int64
	EventPattern string
}

func (q *Queries) RunMonsterExperience(ctx context.Context, arg RunMonsterExperienceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, runMonsterExperience, arg.AccountID, arg.CharacterID, arg.EventPattern)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const runPaidFatigue = `-- name: RunPaidFatigue :one
SELECT EXISTS(SELECT 1 FROM character_fatigue_rooms WHERE character_id=$1
AND run_id=$2 AND cost>0)
`

type RunPaidFatigueParams struct {
	CharacterID int64
	RunID       string
}

func (q *Queries) RunPaidFatigue(ctx context.Context, arg RunPaidFatigueParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, runPaidFatigue, arg.CharacterID, arg.RunID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const saveFatigueCharge = `-- name: SaveFatigueCharge :exec
UPDATE character_fatigue SET used=$1,used_max=$2,updated_at=now()
WHERE character_id=$3
`

type SaveFatigueChargeParams struct {
	Used        int32
	UsedMax     int32
	CharacterID int64
}

func (q *Queries) SaveFatigueCharge(ctx context.Context, arg SaveFatigueChargeParams) error {
	_, err := q.db.ExecContext(ctx, saveFatigueCharge, arg.Used, arg.UsedMax, arg.CharacterID)
	return err
}

const saveFatigueRecovery = `-- name: SaveFatigueRecovery :exec
UPDATE character_fatigue SET used=$1,updated_at=now() WHERE character_id=$2
`

type SaveFatigueRecoveryParams struct {
	Used        int32
	CharacterID int64
}

func (q *Queries) SaveFatigueRecovery(ctx context.Context, arg SaveFatigueRecoveryParams) error {
	_, err := q.db.ExecContext(ctx, saveFatigueRecovery, arg.Used, arg.CharacterID)
	return err
}

const saveOathProgress = `-- name: SaveOathProgress :exec
INSERT INTO character_oath_progress(character_id,dungeon_id,clears,updated_at)
VALUES($1,$2,$3::bigint,now())
ON CONFLICT(character_id,dungeon_id) DO UPDATE SET clears=EXCLUDED.clears,updated_at=now()
`

type SaveOathProgressParams struct {
	CharacterID int64
	DungeonID   int64
	Clears      int64
}

func (q *Queries) SaveOathProgress(ctx context.Context, arg SaveOathProgressParams) error {
	_, err := q.db.ExecContext(ctx, saveOathProgress, arg.CharacterID, arg.DungeonID, arg.Clears)
	return err
}

const saveOmenHeld = `-- name: SaveOmenHeld :exec
INSERT INTO character_omen_state(character_id,dungeon_id,held,updated_at)
VALUES($1,$2,$3::bigint,now())
ON CONFLICT(character_id,dungeon_id) DO UPDATE SET held=EXCLUDED.held,updated_at=now()
`

type SaveOmenHeldParams struct {
	CharacterID int64
	DungeonID   int64
	Held        int64
}

func (q *Queries) SaveOmenHeld(ctx context.Context, arg SaveOmenHeldParams) error {
	_, err := q.db.ExecContext(ctx, saveOmenHeld, arg.CharacterID, arg.DungeonID, arg.Held)
	return err
}

const saveWorld = `-- name: SaveWorld :execrows
UPDATE character_world w SET position=$1,revision=revision+1,updated_at=now()
FROM characters c WHERE c.id=w.character_id AND c.account_id=$2
AND c.id=$3 AND w.revision=$4
`

type SaveWorldParams struct {
	Position    json.RawMessage
	AccountID   int64
	CharacterID int64
	Revision    int64
}

func (q *Queries) SaveWorld(ctx context.Context, arg SaveWorldParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveWorld,
		arg.Position,
		arg.AccountID,
		arg.CharacterID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const scrubPollutedWorldPositions = `-- name: ScrubPollutedWorldPositions :execrows
DELETE FROM character_world WHERE (position->>'town')::bigint=ANY($1::bigint[])
`

func (q *Queries) ScrubPollutedWorldPositions(ctx context.Context, towns []int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, scrubPollutedWorldPositions, towns)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const setOmenPending = `-- name: SetOmenPending :exec
INSERT INTO character_omen_state(character_id,dungeon_id,orthaire_pending,updated_at)
VALUES($1,$2,$3,now())
ON CONFLICT(character_id,dungeon_id) DO UPDATE SET orthaire_pending=EXCLUDED.orthaire_pending,updated_at=now()
`

type SetOmenPendingParams struct {
	CharacterID int64
	DungeonID   int64
	Pending     bool
}

func (q *Queries) SetOmenPending(ctx context.Context, arg SetOmenPendingParams) error {
	_, err := q.db.ExecContext(ctx, setOmenPending, arg.CharacterID, arg.DungeonID, arg.Pending)
	return err
}

const startBirth = `-- name: StartBirth :execrows
INSERT INTO character_birth(character_id,stage)
SELECT id,$1::smallint FROM characters
WHERE account_id=$2 AND id=$3 ON CONFLICT(character_id) DO NOTHING
`

type StartBirthParams struct {
	Stage       int16
	AccountID   int64
	CharacterID int64
}

func (q *Queries) StartBirth(ctx context.Context, arg StartBirthParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startBirth, arg.Stage, arg.AccountID, arg.CharacterID)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}
