// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quests.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const abandonQuest = `-- name: AbandonQuest :execrows
DELETE FROM character_quests q USING characters c WHERE q.character_id=c.id
AND c.id=$1 AND c.account_id=$2
AND q.quest_id=$3 AND q.status='accepted'
`

type AbandonQuestParams struct {
	CharacterID int64
	AccountID   int64
	QuestID     int32
}

func (q *Queries) AbandonQuest(ctx context.Context, arg AbandonQuestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, abandonQuest, arg.CharacterID, arg.AccountID, arg.QuestID)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const acceptQuest = `-- name: AcceptQuest :exec
INSERT INTO character_quests(character_id,quest_id,status,config_version,progress,progress_model)
VALUES($1,$2,'accepted',$3,$4,$5)
`

type AcceptQuestParams struct {
	CharacterID   int64
	QuestID       int32
	ConfigVersion string
	Progress      int64
	ProgressModel string
}

func (q *Queries) AcceptQuest(ctx context.Context, arg AcceptQuestParams) error {
	_, err := q.db.ExecContext(ctx, acceptQuest,
		arg.CharacterID,
		arg.QuestID,
		arg.ConfigVersion,
		arg.Progress,
		arg.ProgressModel,
	)
	return err
}

const clearActQuests = `-- name: ClearActQuests :execrows
UPDATE character_quests SET status='completed',progress=0,progress_model='act-clear-v2',completed_at=now()
WHERE character_id=$1 AND quest_id=ANY($2::integer[])
AND status='accepted' AND config_version=$3
`

type ClearActQuestsParams struct {
	CharacterID   int64
	QuestIds      []int32
	ConfigVersion string
}

func (q *Queries) ClearActQuests(ctx context.Context, arg ClearActQuestsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearActQuests, arg.CharacterID, arg.QuestIds, arg.ConfigVersion)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const clearQuests = `-- name: ClearQuests :execrows
INSERT INTO character_quests(character_id,quest_id,status,config_version,progress,progress_model)
SELECT c.id,q.id,'completed',$1::text,0,'odyssey-skip-v1'
FROM unnest($2::integer[]) AS q(id)
JOIN characters c ON c.id=$3::bigint AND c.account_id=$4::bigint AND c.deleted_at IS NULL
ON CONFLICT(character_id,quest_id) DO NOTHING
`

type ClearQuestsParams struct {
	ConfigVersion string
	QuestIds      []int32
	CharacterID   int64
	AccountID     int64
}

func (q *Queries) ClearQuests(ctx context.Context, arg ClearQuestsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearQuests,
		arg.ConfigVersion,
		arg.QuestIds,
		arg.CharacterID,
		arg.AccountID,
	)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const completeGraduationQuests = `-- name: CompleteGraduationQuests :exec
INSERT INTO character_quests(character_id,quest_id,status,config_version,progress,progress_model,completed_at)
SELECT $1::bigint,q.id,'completed',$2::text,0,$3::text,now()
FROM unnest($4::integer[]) AS q(id)
ON CONFLICT(character_id,quest_id) DO UPDATE SET status='completed',progress=0,
progress_model=EXCLUDED.progress_model,config_version=EXCLUDED.config_version,completed_at=now()
WHERE character_quests.status='accepted'
`

type CompleteGraduationQuestsParams struct {
	CharacterID   int64
	ConfigVersion string
	ProgressModel string
	QuestIds      []int32
}

func (q *Queries) CompleteGraduationQuests(ctx context.Context, arg CompleteGraduationQuestsParams) error {
	_, err := q.db.ExecContext(ctx, completeGraduationQuests,
		arg.CharacterID,
		arg.ConfigVersion,
		arg.ProgressModel,
		arg.QuestIds,
	)
	return err
}

const completeQuestMapObjective = `-- name: CompleteQuestMapObjective :exec
UPDATE character_quests SET progress=0 WHERE character_id=$1
AND quest_id=$2 AND status='accepted' AND progress=1
AND config_version=$3 AND progress_model=$4
`

type CompleteQuestMapObjectiveParams struct {
	CharacterID   int64
	QuestID       int32
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) CompleteQuestMapObjective(ctx context.Context, arg CompleteQuestMapObjectiveParams) error {
	_, err := q.db.ExecContext(ctx, completeQuestMapObjective,
		arg.CharacterID,
		arg.QuestID,
		arg.ConfigVersion,
		arg.ProgressModel,
	)
	return err
}

const completeQuestObjective = `-- name: CompleteQuestObjective :execrows
UPDATE character_quests q SET progress=0 FROM characters c
WHERE c.id=q.character_id AND c.account_id=$1 AND c.id=$2 AND c.deleted_at IS NULL
AND q.quest_id=$3 AND q.status='accepted' AND q.config_version=$4
AND q.progress_model=$5 AND q.progress<>0
`

type CompleteQuestObjectiveParams struct {
	AccountID     int64
	CharacterID   int64
	QuestID       int32
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) CompleteQuestObjective(ctx context.Context, arg CompleteQuestObjectiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeQuestObjective,
		arg.AccountID,
		arg.CharacterID,
		arg.QuestID,
		arg.ConfigVersion,
		arg.ProgressModel,
	)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const completeQuestUseObjective = `-- name: CompleteQuestUseObjective :execrows
UPDATE character_quests q SET progress=0 FROM characters c,character_events e
WHERE c.id=q.character_id AND c.account_id=$1 AND c.id=$2 AND c.deleted_at IS NULL
AND e.character_id=c.id AND e.event_key=$3 AND e.config_version=$4
AND e.outcome->>'template'=$5::text AND e.created_at>=q.accepted_at
AND q.quest_id=$6 AND q.status='accepted' AND q.config_version=$4
AND q.progress_model=$7 AND q.progress=1
`

type CompleteQuestUseObjectiveParams struct {
	AccountID     int64
	CharacterID   int64
	EventKey      string
	ConfigVersion string
	Template      string
	QuestID       int32
	ProgressModel string
}

func (q *Queries) CompleteQuestUseObjective(ctx context.Context, arg CompleteQuestUseObjectiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeQuestUseObjective,
		arg.AccountID,
		arg.CharacterID,
		arg.EventKey,
		arg.ConfigVersion,
		arg.Template,
		arg.QuestID,
		arg.ProgressModel,
	)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const completeRewardedQuest = `-- name: CompleteRewardedQuest :exec
UPDATE character_quests SET status='completed',completed_at=now()
WHERE character_id=$1 AND quest_id=$2
`

type CompleteRewardedQuestParams struct {
	CharacterID int64
	QuestID     int32
}

func (q *Queries) CompleteRewardedQuest(ctx context.Context, arg CompleteRewardedQuestParams) error {
	_, err := q.db.ExecContext(ctx, completeRewardedQuest, arg.CharacterID, arg.QuestID)
	return err
}

const completedQuestIDs = `-- name: CompletedQuestIDs :many
SELECT q.character_id,q.quest_id FROM character_quests q JOIN characters c ON c.id=q.character_id
WHERE c.account_id=$1 AND c.deleted_at IS NULL
AND q.status='completed' AND q.config_version=$2 AND q.quest_id=ANY($3::integer[])
`

type CompletedQuestIDsParams struct {
	AccountID     int64
	ConfigVersion string
	QuestIds      []int32
}

type CompletedQuestIDsRow struct {
	CharacterID int64
	QuestID     int32
}

func (q *Queries) CompletedQuestIDs(ctx context.Context, arg CompletedQuestIDsParams) ([]CompletedQuestIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, completedQuestIDs, arg.AccountID, arg.ConfigVersion, arg.QuestIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompletedQuestIDsRow
	for rows.Next() {
		var i CompletedQuestIDsRow
		if err := rows.Scan(&i.CharacterID, &i.QuestID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasCompletedQuest = `-- name: HasCompletedQuest :one
SELECT EXISTS(SELECT 1 FROM character_quests WHERE character_id=$1
AND quest_id=$2::bigint AND status='completed')
`

type HasCompletedQuestParams struct {
	CharacterID int64
	QuestID     int64
}

func (q *Queries) HasCompletedQuest(ctx context.Context, arg HasCompletedQuestParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasCompletedQuest, arg.CharacterID, arg.QuestID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockOwnedCharacterIncludingDeleted = `-- name: LockOwnedCharacterIncludingDeleted :one
SELECT id,account_id,wire_id,name,profession,create_request,config_version,state,created_at,
0::smallint AS fixed_slot FROM characters
WHERE account_id=$1 AND id=$2 FOR UPDATE
`

type LockOwnedCharacterIncludingDeletedParams struct {
	AccountID   int64
	CharacterID int64
}

type LockOwnedCharacterIncludingDeletedRow struct {
	ID            int64
	AccountID     int64
	WireID        int32
	Name          string
	Profession    int32
	CreateRequest []byte
	ConfigVersion string
	State         json.RawMessage
	CreatedAt     time.Time
	FixedSlot     int16
}

func (q *Queries) LockOwnedCharacterIncludingDeleted(ctx context.Context, arg LockOwnedCharacterIncludingDeletedParams) (LockOwnedCharacterIncludingDeletedRow, error) {
	row := q.db.QueryRowContext(ctx, lockOwnedCharacterIncludingDeleted, arg.AccountID, arg.CharacterID)
	var i LockOwnedCharacterIncludingDeletedRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.WireID,
		&i.Name,
		&i.Profession,
		&i.CreateRequest,
		&i.ConfigVersion,
		&i.State,
		&i.CreatedAt,
		&i.FixedSlot,
	)
	return i, err
}

const lockOwnedCharacterState = `-- name: LockOwnedCharacterState :one
SELECT state FROM characters WHERE id=$1 AND account_id=$2 FOR UPDATE
`

type LockOwnedCharacterStateParams struct {
	CharacterID int64
	AccountID   int64
}

func (q *Queries) LockOwnedCharacterState(ctx context.Context, arg LockOwnedCharacterStateParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, lockOwnedCharacterState, arg.CharacterID, arg.AccountID)
	var state json.RawMessage
	err := row.Scan(&state)
	return state, err
}

const lockQuest = `-- name: LockQuest :one
SELECT status,progress,config_version,progress_model FROM character_quests
WHERE character_id=$1 AND quest_id=$2 FOR UPDATE
`

type LockQuestParams struct {
	CharacterID int64
	QuestID     int32
}

type LockQuestRow struct {
	Status        string
	Progress      int64
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) LockQuest(ctx context.Context, arg LockQuestParams) (LockQuestRow, error) {
	row := q.db.QueryRowContext(ctx, lockQuest, arg.CharacterID, arg.QuestID)
	var i LockQuestRow
	err := row.Scan(
		&i.Status,
		&i.Progress,
		&i.ConfigVersion,
		&i.ProgressModel,
	)
	return i, err
}

const markMeetNPCQuest = `-- name: MarkMeetNPCQuest :execrows
UPDATE character_quests q SET progress=0 FROM characters c WHERE c.id=q.character_id
AND c.account_id=$1 AND c.id=$2 AND c.deleted_at IS NULL
AND q.quest_id=$3 AND q.status='accepted' AND q.config_version=$4
AND q.progress_model=$5 AND q.progress IN(0,1)
`

type MarkMeetNPCQuestParams struct {
	AccountID     int64
	CharacterID   int64
	QuestID       int32
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) MarkMeetNPCQuest(ctx context.Context, arg MarkMeetNPCQuestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMeetNPCQuest,
		arg.AccountID,
		arg.CharacterID,
		arg.QuestID,
		arg.ConfigVersion,
		arg.ProgressModel,
	)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const quest = `-- name: Quest :one
SELECT status,progress,config_version,progress_model FROM character_quests
WHERE character_id=$1 AND quest_id=$2
`

type QuestParams struct {
	CharacterID int64
	QuestID     int32
}

type QuestRow struct {
	Status        string
	Progress      int64
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) Quest(ctx context.Context, arg QuestParams) (QuestRow, error) {
	row := q.db.QueryRowContext(ctx, quest, arg.CharacterID, arg.QuestID)
	var i QuestRow
	err := row.Scan(
		&i.Status,
		&i.Progress,
		&i.ConfigVersion,
		&i.ProgressModel,
	)
	return i, err
}

const questRewardReceipt = `-- name: QuestRewardReceipt :one
SELECT receipt FROM character_quest_rewards WHERE character_id=$1
AND quest_id=$2 AND source_version=$3
`

type QuestRewardReceiptParams struct {
	CharacterID   int64
	QuestID       int32
	SourceVersion string
}

func (q *Queries) QuestRewardReceipt(ctx context.Context, arg QuestRewardReceiptParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, questRewardReceipt, arg.CharacterID, arg.QuestID, arg.SourceVersion)
	var receipt json.RawMessage
	err := row.Scan(&receipt)
	return receipt, err
}

const quests = `-- name: Quests :many
SELECT quest_id,status,progress,config_version,progress_model FROM character_quests
WHERE character_id=$1 ORDER BY quest_id
`

type QuestsRow struct {
	QuestID       int32
	Status        string
	Progress      int64
	ConfigVersion string
	ProgressModel string
}

func (q *Queries) Quests(ctx context.Context, characterID int64) ([]QuestsRow, error) {
	rows, err := q.db.QueryContext(ctx, quests, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsRow
	for rows.Next() {
		var i QuestsRow
		if err := rows.Scan(
			&i.QuestID,
			&i.Status,
			&i.Progress,
			&i.ConfigVersion,
			&i.ProgressModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLegacyQuestRepair = `-- name: RecordLegacyQuestRepair :exec
INSERT INTO character_quest_repairs(character_id,quest_id,reason,before_state,after_state)
VALUES($1,$2,'initial-zero-false-completion',$3,$4)
`

type RecordLegacyQuestRepairParams struct {
	CharacterID int64
	QuestID     int32
	BeforeState json.RawMessage
	AfterState  json.RawMessage
}

func (q *Queries) RecordLegacyQuestRepair(ctx context.Context, arg RecordLegacyQuestRepairParams) error {
	_, err := q.db.ExecContext(ctx, recordLegacyQuestRepair,
		arg.CharacterID,
		arg.QuestID,
		arg.BeforeState,
		arg.AfterState,
	)
	return err
}

const recordQuestMapClear = `-- name: RecordQuestMapClear :execrows
INSERT INTO character_map_clears(character_id,run_id,map_id,source_version)
VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING
`

type RecordQuestMapClearParams struct {
	CharacterID   int64
	RunID         string
	MapID         int64
	SourceVersion string
}

func (q *Queries) RecordQuestMapClear(ctx context.Context, arg RecordQuestMapClearParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordQuestMapClear,
		arg.CharacterID,
		arg.RunID,
		arg.MapID,
		arg.SourceVersion,
	)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}

const recordQuestReward = `-- name: RecordQuestReward :exec
INSERT INTO character_quest_rewards(character_id,quest_id,source_version,model,receipt)
VALUES($1,$2,$3,$4,$5)
`

type RecordQuestRewardParams struct {
	CharacterID   int64
	QuestID       int32
	SourceVersion string
	Model         string
	Receipt       json.RawMessage
}

func (q *Queries) RecordQuestReward(ctx context.Context, arg RecordQuestRewardParams) error {
	_, err := q.db.ExecContext(ctx, recordQuestReward,
		arg.CharacterID,
		arg.QuestID,
		arg.SourceVersion,
		arg.Model,
		arg.Receipt,
	)
	return err
}

const repairLegacyQuest = `-- name: RepairLegacyQuest :execrows
UPDATE character_quests q SET progress=$1,progress_model=$2 FROM characters c
WHERE q.character_id=c.id AND c.account_id=$3 AND c.id=$4
AND q.quest_id=$5 AND q.status='accepted' AND q.progress=0
AND q.progress_model='legacy-zero' AND q.config_version=$6
`

type RepairLegacyQuestParams struct {
	Progress      int64
	ProgressModel string
	AccountID     int64
	CharacterID   int64
	QuestID       int32
	ConfigVersion string
}

func (q *Queries) RepairLegacyQuest(ctx context.Context, arg RepairLegacyQuestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, repairLegacyQuest,
		arg.Progress,
		arg.ProgressModel,
		arg.AccountID,
		arg.CharacterID,
		arg.QuestID,
		arg.ConfigVersion,
	)
	if err != nil {
		return 0, err
	}
affected, affectedErr := result.RowsAffected()
	if affectedErr != nil {
		return 0, affectedErr
	}
	return affected, nil
}
